### ISSUE TITLE
Make  minimap to be draggable

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1001]
We need to make our minimap on the graph view page to be draggable

![Image](https://user-images.githubusercontent.com/5725840/181292159-a3ecba93-f068-4195-ba9b-6758be37797e.png)

**Comment by cescoferraro** [comment]
it seems that react-flow still does not support this feature
https://github.com/wbkd/react-flow/discussions/2166

**Comment by cescoferraro** [comment]
@kdhamric this is a feature not supported by our current DAG library.
Should we close this?

**Comment by xoscar** [comment]
Yeah I think we should just close it, implementing it right now would be a pain

**Comment by kdhamric** [comment]
Closed - we can readdress if needed in the future. @olly
