### ISSUE TITLE
Update unknown span type to general

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1005]
Currently, the front-end application is mapping the `unknown`  span type coming from the backend to general when displaying it on both the DAG and the timeline view.

But when creating assertions we default back to the backend SOT and instead of showing `general`, it goes back to `unknown`. We need to discuss if we want to use `general` as a new fallback for the backend or if we want to remove the FE mapping.

**Comment by xoscar** [comment]
The backend team would be updating the default value to general

**Comment by mathnogueira** [comment]
#1051 implemented this change in the backend

**Comment by mathnogueira** [comment]
Maybe we can close this card now. Is there anything else to be done here, @xoscar ?

**Comment by xoscar** [comment]
Yeah I think we should be able to close this one

**Comment by kdhamric** [comment]
Verified this change works in beta. Closing:
![image](https://user-images.githubusercontent.com/1385894/184706193-28797d2d-7adc-4d2e-9848-c83704bbfd68.png)
