### ISSUE TITLE
support expressions in assertions on the frontend

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1009]
**Is your feature request related to a problem? Please describe.**
#1007 added support to expressions and span attribute referencing in the backend and CLI. We should support it on the frontend as well.

**Describe the solution you'd like**
The custom language editor should autocomplete span attributes when writing the assertions and should start using the `expression` field instead of `value` when creating a new assertion.

**Comment by kdhamric** [comment]
When should we tackle this? We have the FE resources - is this something that can be done now?

**Comment by cescoferraro** [comment]
I am on it
