### ISSUE TITLE
[docs] Rename Introduction menu to Concepts

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1047]
### Docs
Rename `Introduction` menu to `Concepts`, 
and include sections like: 
- Introduction to Trace based Testing
- Assertions
- Selectors

**Comment by kdhamric** [comment]
@jfermi The team went through the marketing site, github readme, and docs while we were together in Colombia. These issues marked Documentation are the items we thought needed addressing. Can you triage these and do the ones you can alter?

**Comment by jfermi** [comment]
Sure - working with the Kubefirst team today - I can work on that on
Thursday.

**Comment by kdhamric** [comment]
Done via #1057
