### ISSUE TITLE
[website] Content improvements

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1050]
### Hero section:
- Update the style of the `Documentation` button. Now it has a transparent background and seems to be disabled.
- Link the `Get Tracetest` button directly to the Readme https://github.com/kubeshop/tracetest#readme
- Update the `sub-heading` text to match our new goal (socialize the new slogan with the leadership team).
- Redo the Intro video.

### Value proposition section:
- Add a value proposition about the `CLI`.
- Change: `"less technical users can create tests"`.
- Make it clear that we work with your existing tools.
- Include the term `trace based testing`. We want to position Tracetest as a trace based testing tool.

### New section: How does Tracetest work?
- Explain how it works with an `illustration/animation`.

### New section: Backends we support:
- Add a section with the backends (trace datastores) we support.

### Quotes section:
- Get more quotes. 😅

**Comment by DigitalH2Ofall** [comment]
Hello.

Regarding...

- Update the style of the Documentation button. Now it has a transparent background and seems to be disabled.
_https://kubeshop.atlassian.net/browse/DESIGN-219 has been created to attend to that._

- Link the Get Tracetest button directly to the Readme https://github.com/kubeshop/tracetest#readme
_DONE_

- Update the sub-heading text to match our new goal (socialize the new slogan with the leadership team).
_Tell us the new slogan when you have it crafted...!_

- Redo the Intro video.
_Supply the new YouTube URL when you have it uploaded. Be sure to work with Kei M if you need help in production. Tina can help with video too if needed of course._

- Add a value proposition about the CLI.
_Looking forward to the new content. Reach out for help for word-smithing and visuals if you need._

- Change: "less technical users can create tests".
_What will it be changed to ...?_

- Make it clear that we work with your existing tools.
_If the existing tools are recognizable, this might be an opportunity for a band of icons of technologies we integrate with._

- Include the term trace based testing. We want to position Tracetest as a trace based testing tool.
_Grammar remark: There needs to be a hyphen on **Trace-based** testing. :-)
Happy to insert, please provide the new copy when you are ready._

- New section: How does Tracetest work?
_When you say "section" you mean a new sub-page (e.g. trace test.io/how-tracetest-works), correct? All in all: great!_

- Explain how it works with an illustration/animation.
_Please rough out a sketch that we can clean up and have you check for technical accuracy._

- Add a section with the backends (trace datastores) we support.
_Again "section" means new sub-page (e.g. trace test.io/backends), yes? Just making sure._

_All in all, when ready to move on these website items, just spin up Jira tasks here https://kubeshop.atlassian.net/jira/software/c/projects/DESIGN/boards/8 and the Design team will get tracetest.io updated accordingly. Thank you._

**Comment by kdhamric** [comment]
Old... closing
