### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by ljo327** [kubeshop/tracetest#1056]
Hello,

I'm not sure this is a bug or something I'm doing wrong. I'm having some issues installing tracetest and getting it to work. 
I'd appreciate it if you could point me in the right direction.

**Describe the bug**
I tried installing using the setup script. Installation seems to be successful(no error log seen)

**Log**
I tried the port forwarding as instructed after the installation but I get this error:
```
○ → kubectl port-forward --namespace my-test-namespace svc/tracetest 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
E0811 17:42:18.939952   50154 portforward.go:406] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 5800e8116a0baed5cf9fa336ae06ba13febe37dfa2dd6b6b7bddd8b63bf593a9, uid : exit status 1: 2022/08/11 16:42:18 socat[64005] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
E0811 17:42:18.940455   50154 portforward.go:234] lost connection to pod
Handling connection for 8080
E0811 17:42:18.941192   50154 portforward.go:346] error creating error stream for port 8080 -> 8080: EOF
```

Upon inspecting tracetest pod log, it's in `CrashLoopBackOff` state:
```
○ → k get pods --namespace my-test-namespace
NAME                         READY   STATUS             RESTARTS       AGE
jaeger-748ccdcff7-xwkbm      1/1     Running            0              36m
tracetest-5648f7bff7-lwjnz   0/1     CrashLoopBackOff   12 (74s ago)   37m
tracetest-postgresql-0       1/1     Running            0              37m
```
So the tracetest pod is having trouble here, looking at the pod log, I see.

```
○ → kubectl logs --namespace my-test-namespace -f svc/tracetest
2022/08/11 16:52:44 could not get trace provider: could not create exporter: could not create gRPC connection to collector: context deadline exceeded
```

otel collector pod seemed ok:

```
○ → k get pods
NAME                              READY   STATUS    RESTARTS   AGE
otel-collector-5d475cfc6b-snznq   1/1     Running   0          61m
```

But the log says it's not:

```
○ → k logs otel-collector-5d475cfc6b-snznq
...
2022-08-11T16:16:24.531Z	info	pipelines/pipelines.go:106	Exporter started.	{"kind": "receiver", "name": "otlp", "pipeline": "traces"}
2022-08-11T16:16:24.531Z	info	service/collector.go:220	Starting otelcol...	{"Version": "0.54.0", "NumCPU": 4}
2022-08-11T16:16:24.531Z	info	service/collector.go:128	Everything is ready. Begin running and processing data.
2022-08-11T16:16:24.532Z	warn	zapgrpc/zapgrpc.go:191	[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "jaeger-collector.tracetest.svc.cluster.local:14250",
  "ServerName": "jaeger-collector.tracetest.svc.cluster.local:14250",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup jaeger-collector.tracetest.svc.cluster.local on 10.96.0.10:53: no such host"	{"grpc_log": true}
2022-08-11T16:16:25.530Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "TRANSIENT_FAILURE"}
2022-08-11T16:16:26.531Z	info	jaegerexporter@v0.54.0/exporter.go:186	State of the connection with the Jaeger Collector backend	{"kind": "exporter", "data_type": "traces", "name": "jaeger", "state": "IDLE"}
```

**To Reproduce**
Run setup script as instructed.
`curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/setup.sh | bash -s -- --namespace my-test-namespace`

**Comment by schoren** [comment]
Hi @ljo-jones. thanks for this report. This is a bug with our installer script, which we are currently reworking to make it more robust and helpful. I think the problem is in the otel collector address in the Tracetest config. I see that you get the otel collector pod from the `default` ns, but our script doesn't let you configure that address.  You can check the value by checking Tracetest's ConfigMap:

```
kubectl get configmap -n my-test-namespace tracetest -o yaml
```

You should see something like this:

```yaml
exporters:
  collector:
    exporter:
      collector:
        endpoint: otel-collector.tracetest.svc.cluster.local:4317 # this is the line.
      type: collector
    sampling: 100
    serviceName: tracetest
```

If your otel collector is running on default, you can `kubectl edit cm  -n my-test-namespace tracetest` and fix the value to read `otel-collector.default.svc.cluster.local:4317`

**Comment by ljo-jones** [comment]
Thank you for your prompt reply @schoren. I can continue with the workaround. One question though, these errors from otel collector log, are they safe to ignore?
```
2022-08-11T16:16:24.532Z	warn	zapgrpc/zapgrpc.go:191	[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "jaeger-collector.tracetest.svc.cluster.local:14250",
  "ServerName": "jaeger-collector.tracetest.svc.cluster.local:14250",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup jaeger-collector.tracetest.svc.cluster.local on 10.96.0.10:53: no such host"	{"grpc_log": true}
```
Thanks!

**Comment by ljo-jones** [comment]
Ah, looks like `jaeger-collector` lives in `observability` namespace and not `tracetest`

**Comment by schoren** [comment]
Oh, good catch. Were you able to fix it? I just realize that the otel install is not namespaced in the setup script, so in my case I have it running on the default namespace, so I had to update the config with this command:

```sh 
kubectl edit cm -n default collector-config
```

and edit this:

```yaml
// ...
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      # Data sources: traces
      probabilistic_sampler:
        hash_seed: 22
        sampling_percentage: 100

      batch:
        timeout: 100ms

    exporters:
      logging:
        logLevel: debug
      jaeger:
        endpoint: jaeger-collector.tracetest.svc.cluster.local:14250 # change to jaeger-collector.default.svc.cluster.local
        tls:
          insecure: true
      otlphttp:
        traces_endpoint: https://ingest.lightstep.com:443/traces/otlp/v0.6
        metrics_endpoint: https://ingest.lightstep.com:443/metrics/otlp/v0.9
        headers: {"lightstep-access-token": "${LIGHTSTEP_TOKEN}"}
        compression: gzip

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [probabilistic_sampler, batch]
          exporters: [jaeger, otlphttp]
// ...
```

Then you need to restart the otel collector pods:

```
kubectl delete pods -n default -lapp.kubernetes.io/name=otel-collector
```

**Comment by ljo-jones** [comment]
Yes, I manually modified the otel-collector and I was able to run tracetest in my simple cluster. Now I've moved on to getting it working in my local dev environment, but tracetest pod is failing to run:

```
± |develop {48} ?:5 ✗| → k get pods -n tracetest
NAME                         READY   STATUS             RESTARTS     AGE
jaeger-748ccdcff7-rr8t6      1/1     Running            0            4m
tracetest-7df56d56fc-mdvl5   0/1     CrashLoopBackOff   3 (5s ago)   51s
tracetest-postgresql-0       0/1     Pending            0            5s
```

```
± |develop {48} ?:5 ✗| → k logs tracetest-7df56d56fc-mdvl5 -n tracetest
2022/08/12 15:38:52 could not execute migrations: could not get driver from postgres connection: dial tcp 10.96.14.37:5432: connect: connection refused
```

Do you know what might be causing this or how to get around this? Looks like it's caused by Postgresql, is it required by `tracetest` for it to work, or is it just for the demo app? (I tried both with/without installing the demo app)

And let me know if you need me to create a new issue 🙂

**Comment by schoren** [comment]
Postgres is a Tracetest requirement. It usually takes around 1 min for pg to start the first time, so if you wait a bit you should see the Postgres pod become ready and shortly after the Tracetest pod will restart. In our fresh deployments, it takes around 10-12 restarts for the tracetest pod to become ready, mainly because it needs to wait for pg.

Let me know if this works for you

**Comment by ljo-jones** [comment]
```
± |develop {48} ?:5 ✗| → k get pods -n tracetest
NAME                         READY   STATUS             RESTARTS        AGE
jaeger-748ccdcff7-rr8t6      1/1     Running            0               28m
tracetest-7df56d56fc-mdvl5   0/1     CrashLoopBackOff   9 (4m37s ago)   25m
tracetest-postgresql-0       0/1     Pending            0               6m28s
```
😢

**Comment by schoren** [comment]
What's the output for `kubectl describe pods -n tracetest tracetest-postgresql-0`? It shuldn't take that long to start.
Also, make sure your cluster has enough capacity for all the pods. Usually having `Pending` pod that long means that the cluster doesn't have a node available with enough resources to schedule the pod

**Comment by ljo-jones** [comment]
Aha, that's it, I see this from the pod log.

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  51s (x3 over 11m)  default-scheduler  0/1 nodes are available: 1 Insufficient memory. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
```
Thanks, let me find a way to allocate more memory and see if that helps.

**Comment by schoren** [comment]
Great, at least we found the cause! Just curious, what kind of cluster are you using? cloud provider, minikube/docker desktop? Just to get an idea of the cluster sizes we can find our users have

**Comment by ljo-jones** [comment]
We use `Kind` and `Docker desktop` 🙂

**Comment by schoren** [comment]
Oh, it's weird you're hitting memory limits. My Docker Desktop cluster has a total memory request of 880mb, only running tracetest and the demo. Are you running on limited environments?

**Comment by ljo-jones** [comment]
We've got some other services and things running and I'm thinking if it almost maxed out already even before trying running `tracetest` but will see, I'll have to have a look a bit more.

**Comment by ljo-jones** [comment]
I've got it working, thank you very much for your help.
I was hoping to see more calling relationships in the Graph view but I'm only seeing 1 service so I will investigate a bit further to see if we have missing instrumentation.
In the meantime, I think it'd be super powerful to have some e2e framework integrated, such as Cypress(which Testkube has), and have trace id collected during the UI interaction. Maybe some time in the future 🙂

**Comment by kdhamric** [comment]
@ljo-jones Glad to see you got Tracetest installed successfully. Ping me (KenHamric) over on Discord - would like to hear how you are using Tracetest & get more thoughts from you on how you would like to see it integrated with Cypress. Also wanted to send you some swag!!

**Comment by schoren** [comment]
> I was hoping to see more calling relationships in the Graph view but I'm only seeing 1 service so I will investigate a bit further.

We're having a conversation about this issue on discord: https://discord.com/channels/884464549347074049/1006621406819266680/1009044489194713151
