### ISSUE TITLE
cli: output improvements

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1067]
I'm opening this issue to document what I think would be the best way of displaying the CLI outputs. I'm focusing on the `run test`:

**Success case**:

:heavy_check_mark: Test name 1 (`https://my-tracetest-instance.io/test/<test_id>/run/<run_id>`)
:heavy_check_mark: Test name 2 (`https://my-tracetest-instance.io/test/<test_id>/run/<run_id>`)
:heavy_check_mark: Test name 3 (`https://my-tracetest-instance.io/test/<test_id>/run/<run_id>`)

**Failure case**

:x:  Test name 1 (`https://my-tracetest-instance.io/test/<test_id>/run/<run_id>`)
.... :heavy_check_mark:  span[name = "my span"]
.... .... :heavy_check_mark: # meta
.... .... .... :heavy_check_mark: tracetest.selected_spans.count = 1 (1)
.... .... :heavy_check_mark: # a47ed57c
.... .... .... :heavy_check_mark: tracetest.duration.span < 200ms (187ms)
.... .... .... :heavy_check_mark: http.status = 200 (200)
.... :x: span[name = "my other span"]
.... .... :x: # a47ed57c
.... .... .... :heavy_check_mark: tracetest.duration.span < 200ms (68ms)
.... .... .... :x: http.status = 200 (404)
:heavy_check_mark: Test name 2
:heavy_check_mark: Test name 3

**Notes**:
- Colors would be applied to the text to make it easier to see in a console. I didn't include it here because markdown doesn't allow it
- `....` means a tab character

EDIT:

* added the link to the test run

**Comment by kdhamric** [comment]
Is this for running one test @mathnogueira - ie the Test name 1, test name 2, etc that you are referencing are really test specs?

**Comment by kdhamric** [comment]
We will also want to have a link to the test run detail page as part of this per our planning notes:
_As a developer, when viewing CLI output from test results we should show the most important stuff, including a link to the UI of Tracetest so you can easily jump to the test, show a summary of the test result that looks good, etc._

**Comment by mathnogueira** [comment]
@kdhamric "Test name 1" would be the name of the test.

```yaml
name: Test name 1 # <<-- this value
trigger:
    # trigger
testDefinitions:
    # specs
