### ISSUE TITLE
[test run details] Implement Trigger mode

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1070]
**Context:** as part of v0.7 we want to improve the UX/UI around the Test Run Details page.

**Objective:** the goal of this ticket is to implement the new Trigger mode.

**AC1**
As a user in the Trigger mode,
I want to `Edit` the test and `Save` it
_**Note:** we need to support our different trigger types (HTTP, GRPC)_

**AC2**
As a user in the Trigger mode,
I want to see the `Response` of the trigger request,
so I can understand what happened with my test request.

**Comment by xoscar** [comment]
Hey @jorgeepc let's add something around the expected behavior when the user clicks save, what needs to change or/and what happens next.
