### ISSUE TITLE
[test run details] Implement Test mode

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1072]
**Context:** as part of v0.7 we want to improve the UX/UI around the Test Run Details page.

**Objective:** the goal of this ticket is to implement the new Test mode.

**AC1**
As a user in the Test mode,
I want to see the DAG visualization with its controls (zoom, fit view, minimap),
so I can interact with it while adding/viewing specs.

**AC2**
As a user in the Test view of a Test Run with no Specs,
I want to see a `No Specs` message with an `Add Test Spec` CTA,
so I can start adding specs to my test.

**AC3**
As a user in the `Add Test Spec` form,
I want to see two steps to create the spec (`1. Select Spans`, `2. Add Assertions`)
so I can start adding specs to my test.

**AC4**
As a user in the `Add Test Spec` form,
I want to type queries using the `Selector Language` and see the affected spans in the DAG,
so I can understand which spans will be affected by my spec.
_I should be able to navigate through the spans in the trace._

**AC5**
As a user in the `Add Test Spec` form,
I want to `Save` the Test Spec,
so I can validate my assertions.

**AC6**
As a user in the `Add Test Spec` form,
I want to `Cancel` the Test Spec process,
so I can return to the previous view without saving the spec.

**AC7**
As a user in the Test mode of a Test Run with recently added Specs,
I want to see them in a `Pending` mode with actions to `Revert`, `Revert All` and `Save`,
so I can verify and publish a new version of my test.

**AC8**
As a user in the Test mode of a Test Run with added Specs,
I want to `Edit`/`Delete` one single spec,
so I can iterate over my test and publish a new version of it.

**AC9**
As a user in the Test mode of a Test Run with added Specs,
I want to click on a spec card,
so I can see the details of the spec including the selector, assertions and affected spans in the DAG.

**AC10**
As a user in the Test mode of a Test Run,
I want to click on a span,
so I can see the details of the span including the list of attributes.

**Comment by xoscar** [comment]
Should we include something regarding the attribute popup?
