### ISSUE TITLE
[test run details] Implement Trace mode

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1073]
**Context:** as part of v0.7 we want to improve the UX/UI around the Test Run Details page.

**Objective:** the goal of this ticket is to implement the new Trace mode.

**AC1**
As a user in the Trace mode,
I want to see two visualization option (`Graph` and `Timeline`),
so I can understand my trace using any of the representations.

**AC2**
As a user in the Trace mode,
I want to `Search` in the trace using a text term,
so I can see which spans have matches.

**AC3**
As a user in the Trace mode,
I want to type a query using the `Selector Language`,
so I can see which spans are selected by the query.
_I should be able to navigate through the spans in the trace._

**AC4**
As a user in the Trace mode,
I want to select a specific Span,
so I can see the attributes associated with the span.

**Comment by xoscar** [comment]
Should we add something regarding the attribute popup here as well?
