### ISSUE TITLE
Manual trigger/test run details page

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1078]
As a developer, I want to be able to specify an API to trigger, and then repeatedly run that trigger as I change code. This will allow me to see both the trigger response (such as API response & status) as well as seeing how my instrumentation of the trace is appearing in the trace (and see timing, etc)

**Comment by kdhamric** [comment]
Spike for the UI research is on #1055

**Comment by jorgeepc** [comment]
Tickets for the UI implementation:
- https://github.com/kubeshop/tracetest/issues/1068
- https://github.com/kubeshop/tracetest/issues/1070
- https://github.com/kubeshop/tracetest/issues/1072
- https://github.com/kubeshop/tracetest/issues/1073
