### ISSUE TITLE
Support SignalFX APM backend

### ISSUE THREAD

**Issue by ljo-jones** [kubeshop/tracetest#1090]
We use SignalFX APM as trace storage platform. Would this be straightforward to add support for? Could you look into it?

Thank you!

**Comment by mathnogueira** [comment]
Hey @ljo-jones, thanks for opening this issue. I never used SignalFX before, maybe you can help us understand if it is possible to write a backend for it.

The only requirement to add a new backend is that this backend provides a way for Tracetest to get a trace by either its `traceID` or the root `spanID`. Here's the [Opensearch backend code](https://github.com/kubeshop/tracetest/blob/3eed1eec0b07dee709c6b6c4ce705109cfaa6ac1/server/tracedb/opensearchdb.go) that we added this week for example.

Do you know if SignalFX provides an API to retrieve traces from it?

**Comment by ljo-jones** [comment]
Thank you for looking into this @mathnogueira. We use APM java agent and have the collector running which then communicates to Splunk Cloud. (some architecture diagrams here https://github.com/signalfx/splunk-otel-collector/blob/main/docs/architecture.md).
I see some APM APIs to retreive traces here;
https://dev.splunk.com/observability/docs/apm/download_traces
But I don't have enough knowledge about this so not sure if this is what you need. Also, I don't know about the authentication aspect either. I'm looking but it seems complicated 😐

**Comment by mathnogueira** [comment]
That's a good start. Their API seems simple enough and I think it would be possible to add support for it. And I just checked and they have a trial plan that I could use to test and implement the solution.

**Comment by mathnogueira** [comment]
Good news @ljo-jones. I just merged the PR to add support to SignalFX and it will be available in version `v0.6.5`. There's an example of how you configure tracetest to connect to your SignalFX account [here](https://github.com/kubeshop/tracetest/tree/main/examples/tracetest-signalfx).

It is also important to know that SignalFX is not that fast to make traces available in the API, so you might want to set a long polling timeout in your tracetest configuration. While testing the integration, some traces were available 2 minutes after the collector had sent them to SignalFX.

If you need any help, let me know.

**Comment by kdhamric** [comment]
@mathnogueira @ljo-jones If SignalFX is that slow, @ljo-jones may still be interested in a OTel collector based solution where a second pipeline is used to route Tracetest triggered spans to Tracetest.

**Comment by ljo-jones** [comment]
Thank you @mathnogueira for adding SignalFX support quickly and thanks @kdhamric for the suggestions, will try SignalFX and explore other options depending on the outcome.
