### ISSUE TITLE
Home page redesign (Tests/Transactions/Enviroments)

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1114]
Redesign based on this https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/596901910/No+more+BS+Plan

**Comment by olha23** [comment]
Design here 👉 https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=0%3A1

**Comment by kdhamric** [comment]
@olha23 This design was implemented as part of adding transactions. I am closing this.
