### ISSUE TITLE
Add confirmation popup for deletions

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1126]
Everywhere there is a resource deletion process, we should have a confirmation warning.

It should include:
- Tests.
- Test Runs.
- Test Specs.
- etc...

Acceptance Criteria:

AC1:
As a user wanting to delete any of the following entities (Test, Test Run, Test Spec)
I should see a confirmation popup with the following information:
1. A copy of the resource I want to delete. i.e: You are about to delete test <test name> from the system. Do you wish to continue?
2. A cancel and confirmation button.

AC2:
As a user looking at the confirmation popup
I should be able to cancel out from the confirmation and the entity should NOT be removed.

AC3:
As a user looking at the confirmation popup
I should be able to click the confirmation button and the entity should be removed.

AC4:
Modal should be configurable and reusable across the different windows and use cases.

**Comment by xoscar** [comment]
@olha23 this one should be ready, let me know what you think

**Comment by olha23** [comment]
@xoscar design is here: https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/tracetest?node-id=1776%3A32642
<img width="913" alt="Screenshot 2022-08-31 at 12 21 30 PM" src="https://user-images.githubusercontent.com/5725840/187645118-315503df-428b-45c0-a252-3ccc8683ef39.png">
