### ISSUE TITLE
Resizing size of span detail attributes area

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1153]
There are times I want more screen real estate to be able to view the span details (ie look at the attributes for a span). Would be nice to have a way to make it wider.

https://www.loom.com/share/72a43a5199a646339cb301dbe0138273

**Comment by olha23** [comment]
By hover we need to show arrow which mean you can resize span details part.

See design here 👉 https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=25%3A4095
