### ISSUE TITLE
When search the interface should indicate when there are no matches

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1154]
When you do a search for 'fdfdsfdsffsf' all spans stay selected, none are disabled, and there is no indication you did a search.

**Comment by kdhamric** [comment]
@olha23 @jorgeepc @xoscar This is a small UX issue, but it still exists. https://www.loom.com/share/cedeb02a760d477e972f51aebb3bde55. 

@olha23 Can you decide if we want to alter the current behavior and come up with a design if we do? Otherwise, please make a comment and close the issue.

**Comment by olha23** [comment]
@kdhamric i propose to add this small improvement -https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2480%3A34557&t=0OK5o8YuXmC9lVQX-1
