### ISSUE TITLE
[SPIKE] db schema proposal

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#1161]
Create a proposal of a new DB schema. It will be more structured and relational, so it's easier to migrate, and we reduce the issues from updating the JSON schemas

**Comment by schoren** [comment]
Proposal:

https://dbdiagram.io/d/6318cd800911f91ba558fc1e

![Image](https://user-images.githubusercontent.com/314548/188940134-7866b765-fa33-4441-bf79-f42705daa4ce.png)

**Comment by xoscar** [comment]
@schoren @mathnogueira @cescoferraro let's discuss this during tomorrow's planning 😄
