### ISSUE TITLE
[test run details] Create new onboarding

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1166]
**AC1**
As a user in the `Test Run Detail` page,
I want to see a new `Onboarding` experience based on the new flow.

**AC2**
As a user in the `Test Run Detail` page,
I want to see the Onboarding modal with a proper design.
Right now it has UI issues about spacing:

<img width="346" alt="Screen Shot 2022-09-07 at 21 14 05" src="https://user-images.githubusercontent.com/3879892/188958943-0c6df4c9-284d-43d9-801f-5d0bb68771fc.png">

**Comment by xoscar** [comment]
@olha23 @kdhamric  can we work on a new set of steps for the onboarding?

**Comment by xoscar** [comment]
@olha23 yes we can 😄 
@cescoferraro if you are looking for work could you take care of hiding it for the moment?

**Comment by cescoferraro** [comment]
@xoscar here it is https://github.com/kubeshop/tracetest/pull/1211

**Comment by olha23** [comment]
design here, but we need to check the copy 👉 https://www.figma.com/file/TMShLwGmcTwX7uRodvyRoE/Onboarding?node-id=252%3A4680
