### ISSUE TITLE
Need to update the introduction video

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1183]
Need to replace the introduction video that was recorded back in April with a modern one.

**Comment by ADITYADAS1999** [comment]
can i work on this issue ?

**Comment by kdhamric** [comment]
Would love to see you create a video on Tracetest and how you are using it. If you produce one, tell us and we will promote & tweet it. I will need to do the main 'intro video' as we use it both here on Github and on Tracetest.io... just put this issue in as a reminder for me to redo it.

**Comment by ADITYADAS1999** [comment]
cool,  but there is already a demo clip on github when click on the image right ?

**Comment by kdhamric** [comment]
Yes - it links off to our YouTube channel. I recorded this video at the beginning of the project - I need to update it so it shows the current (and much improved!) UI, etc,

**Comment by jorgeepc** [comment]
I believe this one is done. Agree @kdhamric ?

**Comment by kdhamric** [comment]
Yes - closing the issue
