### ISSUE TITLE
tracetest CLI export is not including test definitions

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1192]
The tracetest CLI is not including the test definition when doing an export. The definition shown in the app is correctly including the 'specs' area, however

**To Reproduce**
Find a test that has specs defined.  Export the test.

**Expected behavior**
It should include the 'specs' area in the json

Look at this test in the beta env:
https://beta.tracetest.io/test/a96cab71-47d0-4061-b19f-a964187bf812/run/8461b0ee-cee7-47e4-b85a-97e22ef3b3a5

set tracetest cli to point to this env, and try to export the test.
tracetest test export --id a96cab71-47d0-4061-b19f-a964187bf812 -o k.yaml

You will get:
id: a96cab71-47d0-4061-b19f-a964187bf812
name: Pokemon - List
description: Get a Pokemon
trigger:
  type: http
  httpRequest:
    url: http://demo-pokemon-api.demo.svc.cluster.local/pokemon?take=20&skip=0
    method: GET
    headers:
    - key: Content-Type
      value: application/json
  grpc:
    protobufFile: ""
    address: ""
    method: ""

INSTEAD OF: (note that the test specs appear when viewing the test definition from the UI)

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/1385894/189605967-83479294-c64f-45c4-936c-5024bff7f66e.png">

**Comment by mathnogueira** [comment]
@kdhamric I couldn't reproduce this issue. I pointed my CLI to our beta environment and tried to export that specific test you added to the issue description and the specs were exported correctly. Maybe you were using an older CLI version.

**Comment by kdhamric** [comment]
I believe you are correct. I upgraded CLI client yesterday. Repeated the steps above and everything worked. Closing this issue (and thanks!)
