### ISSUE TITLE
Need a 'copy to clipboard' option when viewing a test definition

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1193]
We should have an easy way to copy the test definition file to the clip board when viewing it in the UI. If I want to grab it and paste it in a file, we should make it easy.

**Comment by olha23** [comment]
we need to add "copy" icon to that modal.
See design here 👉 https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/tracetest?node-id=916%3A16396
