### ISSUE TITLE
For non-existing fields matching them using contains causes an error

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1195]
For some scenarios doing equals fails as well, not sure if its because of an extra whitespace or something like that.

**Comment by xoscar** [comment]
![Image](https://user-images.githubusercontent.com/11051031/189676639-aef93707-afc1-4521-ab09-d83596bbed66.png)

**Comment by xoscar** [comment]
![Image](https://user-images.githubusercontent.com/11051031/189677654-e94a975f-3ee7-4f68-82c8-df2a7de2b9b1.png)

**Comment by mathnogueira** [comment]
That was already fixed. This issue was happening due to an outdated server.
