### ISSUE TITLE
Working on the new version of UX for overall app

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#120]
Develop new UX design for the overall app

**Comment by kdhamric** [comment]
#228 and #152 are part of this

**Comment by xoscar** [comment]
The only ticket to be implemented is #152 which is getting moved out from the MVP. I'm moving this ticket out of the project as well 😄

**Comment by xoscar** [comment]
@kdhamric @olha23 let me know if you want to talk about #152 so we can move this ticket forward, thanks!

**Comment by xoscar** [comment]
Bump 🌚

**Comment by kdhamric** [comment]
old - closing
