### ISSUE TITLE
The Body input should be a JSON code editor

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1206]
Currently, we are showing a text area input when creating and editing a test for the request/metadata body. We need to change this to have a better-looking and easier way by updating it to be a code editor.

Acceptance criteria

AC1:
As a user looking at the request details steps part of the create test funnel
When I look at the form
The body input should be a code editor

AC2:
As a user looking at the trigger mode for the test run page
When I look at the form
The body input should be a code editor

**Comment by mathnogueira** [comment]
This was done in #1205

**Comment by xoscar** [comment]
Hey @mathnogueira, the title of this ticket is misleading sorry about that. The work here is to change the body input for both the create and edit steps to match a code editor. Right now we just have a text input that doesn't look good at all.

**Comment by cescoferraro** [comment]
#1221
