### ISSUE TITLE
mermaid.css causes slow load of https://kubeshop.github.io/tracetest/

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1247]
There have been times where trying to access https://kubeshop.github.io/tracetest/ takes a long time (20 seconds or so). Looked at dev tools, and mermaid.css seems to be the issue - it is trying to load it for 21.58 seconds, and it is blocking the rendering. It finally gets a 404 error. We need to determine how to correct the link in the mkdocs file.

![Screen Shot 2022-09-19 at 5 28 00 PM](https://user-images.githubusercontent.com/1385894/191130790-3491e41d-b598-445f-83b8-2d671c7ae63a.png)

**Comment by mathnogueira** [comment]
#1249 might solve it
