### ISSUE TITLE
Implement Sort By functionality in Tests home page

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1306]
**AC1**
As a user in the Tests Home page,
I want to see a `Sort By` dropdown 
with the following options: Recently Created, Last Run, Name A to Z, Name Z to A,
being the default option `Recently Created`.

**AC2**
As a user in the Tests Home page,
I want to choose an option from the `Sort By` dropdown,
so I can see the list of tests ordered by the selected option.

**Designs:** https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=37%3A5305

**Comment by xoscar** [comment]
@schoren @mathnogueira is this something good for one of the FE guys to contribute to the backend code?

**Comment by schoren** [comment]
@xoscar yes, it shouldn't be hard. It's adding a field to the openAPI request, passing it down to the sql query, and change the `order` in that query.
