### ISSUE TITLE
DryRun doesn't return same results as a saved run

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#1307]
**Describe the bug**

When  editing a test from the UI, the Dry Run request passes, but the persisted result is failing. This is caused by:

1.  The FE is sending an assertion object instead of a string.
2. That object is created without taking into account some details, in this case, the "type" is sent as `string`, but since the literalValue is not sent quoted (the BE gets `example` instead of `"example"`) when the value is persisted and subsequently re-parsed when reading from DB, it is then treated as an `attribute` instead of a `string`.
3. This causes the expected value to be interpreted as `[matching span].attributes.example` instead of the literal `example` string. Since the attr doesn't exists, the expected value is interpreted as `""` (empty string). The comparison then fails.

[Example from beta](https://beta.tracetest.io/test/2070e2b7-8226-4261-83fc-d021cf261ef7/run/705e551a-c5bc-4c56-b79b-7c10869e1579/test?selectedSpan=b9beb0d23af2f86a):

Run details:
![Screen Shot 2022-09-29 at 12 19 29](https://user-images.githubusercontent.com/314548/193071734-012bcb32-241e-4085-bcfc-9bf4b881b20a.png)

Run List:
![Screen Shot 2022-09-29 at 12 19 47](https://user-images.githubusercontent.com/314548/193071790-b476ef8d-379d-44df-a433-6607455f1ae0.png)

** Things to be fixed**

1. The FE should send the assertion as a string, so the backend can parse it applying the same rules it will use when reading from the DB
2. the BE should make it more obvious that the assertion refers to an attribute instead of a string. For example, we could use `attr.tracetest.span.type` (the important part being the **attr** prefix), and treat any string that doesn't start with `attr.` as a string. We could support quotes as a way to force a literal value.
3. The FE seems to be calling the `DryRun` endpoint as soon as you land on the test run detail page, which in this case masked the issue. It is also needles work for both the FE and the BE, since the result is already present on the `test run` response. This should not be the case.

**Comment by mathnogueira** [comment]
PR #1308 should fix this

**Comment by mathnogueira** [comment]
Closing this, as it seems that #1308 fixed it.
