### ISSUE TITLE
Panic when publishing new assertions

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#1312]
**Describe the bug**
When trying to publish new assertions, I get a `panic` on the backend when the FE calls the `rerun` endpoint.

**To Reproduce**
1. Go to any test run
2. Add an assertion. I tried to assert `tracetest.span.type`, `equal`, `general` (no quotes on the value)
3. Save the assertion.
4. Click on `Publish`

**Expected behavior**
Get a new test run

**Screenshots**

Backend panic
![Screen Shot 2022-09-30 at 09 53 39](https://user-images.githubusercontent.com/314548/193274424-af157b65-887a-4a58-b8bf-f1a907134fea.png)

Looks like the problem is on this line: https://github.com/kubeshop/tracetest/blob/main/server/assertions/assertions.go#L71, seems like `a.Value` is nil, I imagine because it's not correctly parsed.

**Comment by mathnogueira** [comment]
#1313 prevents invalid requests to be saved and cause the `nil` value to be saved.

**Comment by mathnogueira** [comment]
I don't think this will happen now that we are validating the input. So, I'm closing this
