### ISSUE TITLE
Change check expectation parsing rules

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#1315]
Implement a new format, similar to Javascript [Template Literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). An assertion could look like this:

```
tracetest.response.body contains "the request lasted ${attr:span.tracetest.duration}ms"
```

The main concept is that the expectation part is parsed similar to TS template literals. So everything is a string literal, except anything wrapped within a `${}` block. 

Within a `${}` block, everything is treated as an expression. 

A few examples:

```
// span took less than 100ms
tracetest.span.endTime < "${attr:tracetest.span.startTime + 100ms}" 

// body contains a json literal {"userID":"123"}, if the span has an attr of myapp.myspan.user_id = 123
tracetest.response.body = '{"userID":"${attr:myapp.myspan.user_id}"}' 
```

**Comment by mathnogueira** [comment]
This was implemented and will be merged as soon as we get the frontend working

**Comment by mathnogueira** [comment]
Closing it for now
