### ISSUE TITLE
undefined undefined showing in Timeline View of trace

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1319]
When looking at the timeline view of a trace, both demo site and my local copy show 'undefined undefined' on each span directly after the number of ms for the span. Here is a photo:

![Screen Shot 2022-09-30 at 5 12 50 PM](https://user-images.githubusercontent.com/1385894/193363478-aec7556a-2941-4da3-a2ad-e8f010df5b1e.png)

**Comment by jorgeepc** [comment]
@kdhamric I remember I fixed this in beta. I see it working correctly in my local env. I'll check in beta once we restore the environment.

**Comment by xoscar** [comment]
I confirmed that this should be fixed on the beta env. We can coordinate a deployment to move that fix up to the demo env
