### ISSUE TITLE
[Tech Debt] Improve e2e tests coverage

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1327]
As we keep adding features we haven't been keeping up adding new tests for the new flows and steps on the app. The idea of this ticket is to evaluate what sections of the app require better e2e coverage and start working on it.

Here are a few examples:
1. Trace view -> show the attribute list for a specific span
2. Trace view -> attribute list -> switch between tabs
3. Test view -> create assertion with empty selector
4. Test view -> create assertion with a nonexistent attribute (TDD).
5. Test view -> navigate away with pending changes

**Comment by cescoferraro** [comment]
implemented at #1352
