### ISSUE TITLE
[Tech Debt] Organize custom inputs

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1328]
We are doing a great job by re-utilizing existent inputs that we create for different forms but currently, all of the inputs are spread out across the different directories and sections of the code. 
We need to have a centralized place and a standard for all inputs so they are easier to identify and use across the app.

The outcome of this ticket is to reorganize the different custom input components and create a simple interface to use them across the app.

**Comment by kdhamric** [comment]
@xoscar Can this issue be closed?
