### ISSUE TITLE
[Transactions] Update Test Spec Details Assertions UI

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1408]
As assertions have been changed to be string values and now the FE supports a broader way of features to create different types of expressions, we need to work on a way to display span assertions, alongside both the expected results and the parser value.

Acceptance Criteria:

**AC1:**
As a user looking a the test spec details
I should be able to see the list of span results
Each span result should have the list of assertions applied to it
And every assertion should display the expression, actual value, and expected value

Current Demo UI
<img width="669" alt="Screen Shot 2022-10-24 at 9 18 49" src="https://user-images.githubusercontent.com/11051031/197550017-9456ff56-43b9-4d10-97d6-1d407676b673.png">

New Beta UI
<img width="693" alt="Screen Shot 2022-10-24 at 9 26 35" src="https://user-images.githubusercontent.com/11051031/197550203-2f90a909-8e74-4ae0-9301-ae66d786a627.png">

**Comment by olha23** [comment]
@xoscar check design here please https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=545%3A10649

**Comment by olha23** [comment]
@xoscar check update here please https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=573%3A9920

**Comment by xoscar** [comment]
@olha23 looks good! we'll start with the implementation, thanks!
