### ISSUE TITLE
Download YAML TestCase usage

### ISSUE THREAD

**Issue by gogovan-vincentngai** [kubeshop/tracetest#1409]
Not sure i miss something in here 
What is the purpose of download yaml for the testcase?
As it seems not fully K8S Yaml and it does not have any **kind** ?

What i would like to do is what the cluster bring up everything include the testcase 
But currently seems it only a backup and using back by CLI?

It is there already have the cli installed inside the tracetest pod ? So we can do initicontainer and inject those test from the cluster bringup  state (such like if we doing DR....then we want to know is it all application function normally at least...internally...

or better support directly deploy by k8s yaml and then make the tracetest consume them back ?

btw the tools idea is awesome supported grafana tempo awesome

**Comment by mathnogueira** [comment]
Hello @gogovan-vincentngai ! Thanks for reaching out!

> btw the tools idea is awesome supported grafana tempo awesome
We are very happy to hear that! Feel free to open as many issues you like to provide feedback for us!

> What is the purpose of download yaml for the testcase?
> As it seems not fully K8S Yaml and it does not have any kind ?

The k8s manifest inspires it. But you can't create a test using kubectl for now. 

> But currently seems it only a backup and using back by CLI?

Its purpose is precisely what you mentioned. You can use it to backup a test specification and execute the test using the CLI

> It is there already have the cli installed inside the tracetest pod ?

We don't have the CLI on the docker image, but that makes sense. I'll open a PR to add that today. With that, you would be able to run your tests with initcontainer.

> or better support directly deploy by k8s yaml and then make the tracetest consume them back?

We plan to create a Tracetest test runner for [TestKube](https://testkube.kubeshop.io/). That would enable you to create tests using K8S CRDs.

**Comment by mathnogueira** [comment]
@gogovan-vincentngai yesteday I released version 0.7.6 and it includes the CLI in the docker image.

**Comment by gogovan-vincentngai** [comment]
I think this case can be close now ? i've got the ans for now
