### ISSUE TITLE
[trace visualization] Implement flame graph

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1417]
**AC1:**
As a user interacting with the `Trace` tab in a `test run`, 
I want to see a new visualization option: `Frame graph`,
so I can have a different interpretation of the trace.

**Useful links:**
[Flame graph info](https://www.brendangregg.com/flamegraphs.html)
[Datadog flame graph implementation](https://docs.datadoghq.com/tracing/trace_explorer/trace_view/?tab=spantags)

![Screen Shot 2022-10-24 at 09 50 10](https://user-images.githubusercontent.com/3879892/197556068-4067f095-5dc3-47ad-9748-a395bbbccdda.png)

**Comment by olha23** [comment]
link for design 👉 https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=661%3A20143

**Comment by jorgeepc** [comment]
I did some research around `flamegraphs` and the value of including them in Tracetest. Here some findings:

## A couple of concepts first

Flamegraphs are a way to visualize how a program is spending time. Important things about flamegraphs:

- The **x-axis** on the flamegraph does **NOT** represent time. It represents the stack profile population sorted alphabetically.
- The **y-axis** represents the stack depth.
- Flamegraphs are generated from a **SERIES** of stack traces, not a single trace.
- You can not tell from a flamegraph how many times a function was called. You can only tell how much time was spent in the function.

**Example:**

Let's consider that our profiler has collected 4 stack traces:

```jsx
a -> d (1)
b -> d (1)
a -> b -> c (1)
a -> b -> c -> d (1)
```

<img width="1194" alt="Screenshot 2022-11-25 at 15 17 52" src="https://user-images.githubusercontent.com/3879892/204051784-e8f35955-3fc1-43a4-b7d0-54c196f6098a.png">

The flamegraph is generated by sorting the above stack traces (so that all the `a` are together). We can deduce from the flamegraph that:

- 75% (3/4) of the stack traces we collected started in the `a` function
- 50% (2/4) of the stack traces started with `a` calling `b` and then calling `c`.

## Flamecharts (a flamegraph variation to represent trace using time)

`Flamecharts` were first added by Google Chrome's Web Inspector. While inspired by flamegraphs, flamecharts put the passage of **time** in the **x-axis** instead of the alphabet. 

One aspect of flamecharts is that `multi-threaded` applications can't be shown by a single flame chart. However, flamecharts don't need to deal with this problem, since they are mostly used for `single-threaded` JavaScript analysis.

<img width="622" alt="Screenshot 2022-11-25 at 15 33 38" src="https://user-images.githubusercontent.com/3879892/204052934-077c34e6-a88e-4498-8354-136d95c75d57.png">

## Options to represent a single trace

As mentioned above:

- `Flamegraphs` are used to represent a `series` of stack traces of profiled software.
- `Flamecharts` can't represent `multi-threaded` applications.

We could conclude that pure `flamegraphs`/`flamecharts` are not the best option to represent a single trace of a distributed system. I have found two vendors using "custom" versions of flame graphs:

**Jaeger**

The team behind [Pyroscope](https://pyroscope.io/) contributed with Jaeger to include the [pyroscope-flamegraph](https://www.npmjs.com/package/@pyroscope/flamegraph) component as part of the Jaeger Trace View options. [The PR](https://github.com/jaegertracing/jaeger-ui/issues/525) was merged and now it's part of Jaeger UI, however they were not aware of the challenges around representing `multi-threaded`/`async` traces and the graph does not work when dealing with those types of traces.

As you can see in the image, the representation does not make sense. the `pokeshop: findMany` and `pokeshop: count` are parallel spans (which is not represented in the graph), and the x-axis in this case is time which causes an incorrect visualization. `pokeshop: count` has 4.08ms however in the graph it's smaller than `pokeshop: findMany` with 4.79ms.

There is an [open issue](https://github.com/jaegertracing/jaeger-ui/issues/1012) in the jaeger repo reporting the issue and an [open PR](https://github.com/pyroscope-io/pyroscope/pull/1679) with a “hacky” proposal (not accepted by the core team)  that does not fix the real issue: flamegraphs are not a good option for single multi-threaded traces.

**Datadog**

Datadog has its own “custom” implementation of a flamechart. In my opinion this visualization it's more close to a condensed timeline view.
