### ISSUE TITLE
Have a priority for assertions where the most specific check 'wins'

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#146]
As a User (ie QA, Dev, Operations),
I want to be able to set general assertions, such as all HTTP spans should have a status_code of 200.  I would, however, like to override this for specific spans.  
So that I can have a general check for most spans of a certain type and 'override' it when a more specific check is needed.

For example, I may be doing a user creation via a post, and it returns a 201.  I would be able to add an assertion for HTTP POST saying it will return a 201... the system would pay attention to the most specific assertion and not run the less specific ones.

@mathnogueira idea

**Comment by mathnogueira** [comment]
Now that I have a better understanding about tracetest, I don't think this is a good idea. I'm going to close it for now, we can reopen it if we think that is relevant.
