### ISSUE TITLE
Time for response to return shows wrong initially

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1467]
The time shown at the top right of the response screen shows a wrong value until the test is finished running. This needs to be corrected.

![image](https://user-images.githubusercontent.com/1385894/200948601-d3601e38-94cb-4658-9b2f-a821d3ecce75.png)

**Comment by jorgeepc** [comment]
The API is returning a wrong value for the `executionTime`. Needs to be fixed in the backend.

![Screenshot 2022-11-11 at 13 11 36](https://user-images.githubusercontent.com/3879892/201402864-029555d8-71ff-4b28-a15b-efb79edbdd75.png)

**Comment by schoren** [comment]
@jorgeepc what is the expected value if the test is not completed? If I return `0` in the api, I can still see this

![Screenshot 2022-11-15 at 14 55 19](https://user-images.githubusercontent.com/314548/201991482-13797098-1ded-4253-8b58-6cc9ea5af23f.png)

The exeuction time is calculated with the completedAt, which is filled when the tests fails or successfully asserts. It looks like there's not a consistent logic between FE/BE for this field?
