### ISSUE TITLE
[Chaining V2] Display Transaction info at the test run page

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1522]
We would want users to be able to identify if a test run was part of a transaction execution by displaying the transaction run information at the test run level.

Acceptance criteria:
AC1:
As a user looking at a test turn
And the test run was part of a transaction run
I should be able to identify that the run was part of a transaction

AC2:
As a user looking at a test turn
And the test run was part of a transaction run
I should be able to see somewhere on the screen the following information:
1. Transaction name
2. Transaction link

**Comment by xoscar** [comment]
@olha23 this ticket requires some design work, do you mind taking a look? Thanks!

**Comment by olha23** [comment]
sure

**Comment by olha23** [comment]
mockups here https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1550%3A27944&t=T0hediMr9qd18ngV-1
