### ISSUE TITLE
[Chaining V2] Show Outputs for each of the execution steps

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1523]
We need to have a simple way to see the outputs from each of the tests directly from the transaction run page.

Acceptance criteria
AC1:
As a user looking at a transaction run
And some of the tests have outputs
I should be able to see the outputs from each of the tests

AC2:
As a user looking at a transaction run
And some of the tests have outputs
I should be able to see the final state for the variables at the bottom

**Comment by xoscar** [comment]
@olha23 this also has some design work, do you mind taking a look? Thanks!

**Comment by olha23** [comment]
@xoscar regarding variables - we already show variables at the bottom on the transaction page, yes? so we need to add ability to show outputs?

**Comment by xoscar** [comment]
@olha23 exactly, more specifically at each of the tests steps

**Comment by olha23** [comment]
@xoscar to be honest, i am not sure that show the outputs on the transaction page it’s a good idea. First of all we have a direct link for all tests included in transaction and user can easily jump there, second - we just will duplicate the same information during the different pages, third  - outputs take a lot of space. 

as an option i propose show which test include output and how many and if user what to check detail information he will jump on the specific test page. Like this: 

![Image](https://user-images.githubusercontent.com/5725840/214852409-e7a07767-cf2c-4fb2-8607-6cc3b37055d3.png)

**Comment by xoscar** [comment]
@kdhamric @jorgeepc @mathnogueira @danielbdias  thoughts?

**Comment by xoscar** [comment]
Moving this to the freezer int he mean time

**Comment by kdhamric** [comment]
@olha23 @xoscar I can't imagine not being able to see the outputs from each test when viewing a transaction... you need to see the flow (the order of the tests) and how variables have changed (ie what the stat of the variables is after / before each test.

Could we have a line that says:
7 variables    v
That when you hit the 'open/expand' (the 'v' in the line above) it opens it up and shows each variable and its value?

**Comment by olha23** [comment]
@xoscar check the mockups here please https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1588%3A29425&t=7tR20JrxErFMFly2-1

**Comment by jorgeepc** [comment]
Hey @olha23 we need to consider JSON values (or large values in general) in the outputs section. Maybe we can reuse the same component we have at the bottom of the page for variables. Please let me know what you think.

<img width="1624" alt="Screenshot 2023-02-01 at 10 35 16" src="https://user-images.githubusercontent.com/3879892/216088926-58969a11-5dff-4c04-970a-83d0363c074d.png">

**Comment by olha23** [comment]
@jorgeepc yea i like your idea!
