### ISSUE TITLE
[Chaining V2] Add Transaction summary results in the run page

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1542]
The transaction run page does not show a summary of the transaction results for each run in the run page - we need to add this:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/1385894/206346008-58ab39ff-cb62-4a8f-bacd-a9584b1fd2fa.png">

**Comment by olha23** [comment]
mockups here https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=805%3A17510&t=m7ZdwDInX2J5B6dJ-1
