### ISSUE TITLE
Screen changes to trigger tab when defining variable

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1552]
When defining a variable based on an attribute the screen moves to the trigger tab. This alters the screen the user was looking at when beginning the process, so they have to remember what they saw. I tend to think the screen should stay on whichever tab is selected throughout the entire 'add variable' flow.

https://www.loom.com/share/53a6df4d9fbd4bd1a341b1b4748be711

@olha23 Thoughts?

**Comment by jorgeepc** [comment]
Probably should be fixed by #1573

**Comment by olha23** [comment]
work on this👍

**Comment by xoscar** [comment]
Closing as duplicated of https://github.com/kubeshop/tracetest/issues/1573
