### ISSUE TITLE
Improve run page UI

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1554]
Need to move Run button up and replace the 3dots icon to trash icon. The same for test and transaction page.
Check the figma link please> https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.7-Release-Tracetest?node-id=805%3A17152&t=RTzLABF6KHOdE0qx-1

**Comment by sanjayk0508** [comment]
couldn't access the Figma draft
