### ISSUE TITLE
Single page app has to be refreshed to show finished test

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1563]
A number of time when testing in beta I have to refresh the page to see that the test has actually finished. Maybe 1 out of 4 times - not real difficult to reproduce. Here is an example of the screen before refreshing:

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/1385894/203437001-129ec7c8-77f2-4daf-b9b4-e435d548d874.png">

**Comment by xoscar** [comment]
@mathnogueira @danielbdias do you mind taking a look a the websocket configuration? we might be having some issues causing this bug

**Comment by xoscar** [comment]
CCing @schoren too 😄

**Comment by danielbdias** [comment]
Team, this happened because our TracePoller stopped before receiving all trace spans. I've added another stopping condition on #2059 to avoid this situation.
