### ISSUE TITLE
Response not showing after test successfully ran

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1564]
Look at the Trigger tab... the response is not showing. It was (I believe... almost positive) initially when I ran the test. I can see the trace and have applied assertions and set a variable.

https://beta.tracetest.io/test/T8Vw8adVg/run/3/trigger

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/1385894/203453555-a2cc028e-301c-4837-923d-aeb3305d60d7.png">

**Comment by kdhamric** [comment]
Update: we were having issues overall running tests in beta at the time. I think this is a symptom of server issues, not a root issue.

**Comment by jorgeepc** [comment]
This was fixed by #1571
