### ISSUE TITLE
[Chaining V2] Indicate when there is a variable associated with a span or with an attribute

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1565]
As a user, I selected an attribute on a span and created an output from it. When I later view the span, there is nothing to indicate that the attribute is involved as an output. If I do not remember or check, I might try to create an output again against the same piece of data.

After creating an output:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/1385894/203453962-8b45c071-9803-4b4d-9e29-441b36eec3ef.png">

I see no indication when viewing the span or the attribute:
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1385894/203454047-c0b2cec2-d801-4776-b550-e88b0b69d87b.png">

@olha23 should mock how this should look

**Comment by olha23** [comment]
mockups https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1159%3A20966&t=KL8Mj1NsSqKukCP1-1
