### ISSUE TITLE
[Chaining V2] Redesign Test Outputs modal and location

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1573]
Currently, the defining a test output takes you to the Trigger page and the outputs are shown in a tab. There are a couple issues with this:
- when defining an output, you typically are working with attributes on either the Trace or Test page, and you may need to see the data contained and shown in the attribute when defining it. As an example, if you wanted to extract a value from the json in an attribute, viewing the json while creating the output is helpful.
- It would be helpful to have an indication that a particular attribute in a span is involved in setting an output. As user could be looking at an attribute and think they need to create a variable based on it, when in actuality they have already created one. This is covered in #1565

**Comment by olha23** [comment]
mockups - https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1155%3A24225&t=KL8Mj1NsSqKukCP1-1
