### ISSUE TITLE
[docs] Write a dedicated config file reference page for `tracetest.config.yaml`

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#1581]
The docs need a dedicated page with a full reference for all possible configuration possibilities for the `tracetest.config.yaml`.

**Comment by mathnogueira** [comment]
@adnanrahic, I'm working on this. Initially, my plan was to set everything on the same page, however, that will become huge due to the configuration for data stores. I'm thinking about splitting this into multiple pages. What do you think about creating a section called `Configuration`?

**Comment by adnanrahic** [comment]
Nice! For sure. Adding a section called `Configuration` will be covered with this PR: #1593

**Comment by kdhamric** [comment]
@adnanrahic Do we still need this issue?

**Comment by adnanrahic** [comment]
We can close this because we now have:

- https://docs.tracetest.io/configuration/server
- https://docs.tracetest.io/configuration/provisioning
