### ISSUE TITLE
Show links to tests from transaction run page

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1597]
As a user, when I run a transaction I may want to open one of the tests to see why the test is not running properly. Currently, we do not show a link to each of the tests involved in a transaction.

In the case below, I ran the transaction without knowing if the selected environment was setup properly. The transaction pagge shows what the environment variables are, so I wanted to check the test it was 'stuck on' to see what variables it depends on. I should be able to open any of the tests involved in a transaction from this page. As it was, I opened a new window, searched for it by name, then opened it. @olha23 
![image](https://user-images.githubusercontent.com/1385894/204341035-2bcf0034-2478-4299-9850-6acddb57bb90.png)

**Comment by jorgeepc** [comment]
@kdhamric  We have a link to the testRun there. We don't display it until we get a `runId` from the API. It seems that your testRun was not ready yet. 🤔 

<img width="1624" alt="Screenshot 2022-11-28 at 12 33 29" src="https://user-images.githubusercontent.com/3879892/204343670-334e0c7f-392e-487a-b7b6-edf8f68917b2.png">

**Comment by kdhamric** [comment]
Yes, saw that.

I was wanting to open the test (really, the test definition) as the test was still running. It paused on the test (we have an issue with our websockets - I think a refresh would have 'fixed' it). I assumed I did not have the correct variable names defined in the environment, so I wanted to go view that test... right then.

As second 'need' for this would be when I am defining a transaction - I want to be able to 'pop open' in a new window a test to check it. An example of that need would be shown in the screenshot below - if I have 2 tests named the same, I may want to 'pop open' the test (right click and open) to see if it is. 
![image](https://user-images.githubusercontent.com/1385894/204347199-6b430f6b-7661-4ce6-9b0d-d15031774263.png)

A third time would be when I have opened a transaction, but not run the tests yet. I may want to 'open' each of the tests to see what variables it needs or exports.

![image](https://user-images.githubusercontent.com/1385894/204347824-c7b2f0f2-ea2e-4541-be06-d0b196d3399f.png)

We have a 'delete' trash can icon next to each test in the 'edit transaction' list of tests. One possible solution would be some type of 'open test' or 'open test in new window' icon... but your / @olha23 choice.

**Comment by xoscar** [comment]
I added a couple of changes to support links for tests in a transaction and redirect the user to the test details page if the run isn't created yet. 

@kdhamric assigning this back to you to validate if you think this is enough or If you'll like to add something else.

**Comment by kdhamric** [comment]
Looks good Oscar and accomplishes the goal. Closing.
