### ISSUE TITLE
[Chaining V2] Deleting a transaction does not work in beta

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1603]
I cannot delete a transaction in the beta environment. Network tab shows a 500 error with the delete call. The response from the server shows:
"pq: update or delete on table \"transaction_runs\" violates foreign key constraint \"transaction_run_steps_transaction_runs_fk\" on table \"transaction_run_steps\""

https://www.loom.com/share/c5bba4e5e289472f9a7f26355b2c37a5

![image](https://user-images.githubusercontent.com/1385894/204375605-47802352-ea06-40de-bf15-79d2297f409a.png)

![image](https://user-images.githubusercontent.com/1385894/204375666-d44e0dfc-8154-4136-8d0f-67e150ada9d6.png)

**Comment by xoscar** [comment]
Validate deletion sequence for transactions (foreign keys constraints)

**Comment by jorgeepc** [comment]
@kdhamric please re-test this

**Comment by xoscar** [comment]
@kdhamric to retest this 😂

**Comment by xoscar** [comment]
I've been working a lot of transactions lately and I haven't seen this coming up again, so I'm closing this for now
