### ISSUE TITLE
Access to polling settings underneath configuration menu

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1626]
We need to allow easier access to change the global default polling config for the Tracetest server. We want the user to be able to go to 'Server settings' from the home page of Tracetest (see #1625) and access this capability.

Currently, the setting have to be set in the server config file:

pollingConfig:
    timeout: 10m
    retryDelay: 5s

These two values will likely be the ones we need to allow to be changed. The server should respect these values for any future runs.

We are discussing the future state of polling configuration in #1119. We should get consensus on that before beginning work on this issue.

**Comment by xoscar** [comment]
@kdhamric let's add acceptance criteria please 😬

**Comment by xoscar** [comment]
This will be fixed with [[config] Add polling to settings page#1998](https://github.com/kubeshop/tracetest/issues/1998) changes
