### ISSUE TITLE
[In-App Config] No-Tracing Mode

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1628]
When the app is not ready to support data stores, traces, spans, etc. It should be in a specific mode called no-tracing, where it should function just with the immediate request/response and tracetest triggering spans.

Acceptance Criteria:
AC1:
As a user that just installed Tracetest
And I have decided to not provide the data store info at the beginning
I should be able to check if the app is in no-tracing mode

AC2:
As a user that just installed Tracetest
And I have decided to not provide the data store info at the beginning
I should be able to create tests

AC3:
As a user that just created a test in no-tracking mode
I should be redirected to the run page
And see the immediate result of the service

AC4:
As a user looking at a no-tracking mode test
I should be able to move to the trace and test modes
And the trace should display a single trace trigger span

AC5:
As a user looking at a no-tracing mode test
I should be able to create test specs on the trace trigger span

**Comment by xoscar** [comment]
@olha23 I think we need to add some designs on a global way to display the no tracking mode for users, it could be a warning badge in the nav menu that opens something or anything like that.

For the backend, the tasks here are:
1. Create the fake trace and trigger span
2. Do not wait for the full trace

CC: @mathnogueira @kdhamric

**Comment by xoscar** [comment]
bump @mathnogueira
