### ISSUE TITLE
[In App Config] Tech Design

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1638]
As part of the initial planning and grooming of the [config UI epic](https://github.com/kubeshop/tracetest/issues/1612), we need to start working on tech definitions and architecture design that will be the base specs for the implementation tickets.

Acceptance Criteria:
1. It should outline the configuration data flow, from presenting it to the user to the save & reload process.
2. It needs to define closing the possible edge cases when updating the config (when should it be available versus not).
3. Come up with the open API specs so the FE can start working based on them.

**Comment by xoscar** [comment]
Configuration Dataflow and Save & Reload Process.

Currently, the app supports a single way for configuration by providing a configuration YAML file before the server installation, and to handle file updates a full server restart needs to happen.
This causes downtime where users cannot use the application, tests, and transactions cannot be executed and the ones that are in progress become stale.

By opening the door to a post-install setup and updates, there are a few things that need to be considered:
1. What happens to in-progress tests/transactions?
2. Should the server broadcast to clients about the server status (no-tracing vs ready) in case a config change happens?
3. Should we also support live updates for the config yaml file without requiring a reload?

Data Flow - Proposed solution:

```mermaid
sequenceDiagram
    User->>+App: Clicks Finish Setup CTA
    App-->>-User: Displays setup wizzard
    User->>+App: Selects data store
    App-->>-User: Provides config inputps for data store
    User->>+App: Fills in config data store details
    App-->>-User: Valiates config data
    User->>+App: Clicks test connection
    App->>+Backend: Sends test connection request with config
    Backend->>+DataStore: Triggers connection request
    DataStore-->>-Backend: Returns data (or times out)
    Backend-->>-App: Returns test connection result
    App-->>-User: Displays test connection result
    User->>+App: Clicks Save
    App->>+Backend: Sends configuration update request
    Backend->>+FileSystem: Updates configuration file
    FileSystem-->>-Backend: OK
    Backend-->>-App: OK
    App-->>-User: OK

    App->>+Backend: Listens to config changes
    Backend-->>-App: OK

    Backend->>+FileSystem: Listens for Config file updates
    FileSystem->>-Backend: New Config file update
    Backend->>+Backend: Validates and applies in memory config
    Backend-->>App: Broadcasts config update
    App-->>User: Updates UI with results in real time
```

**Comment by xoscar** [comment]
While checking the configuration I saw that we can have an exporter option plus multiple data stores.
Based on this we will need to support a way for users to add multiple data store values plus a possible OTel collector exporter.

Users should have a way to add multiple data stores but have one selected at a time.
Aside from the data store, we need to provide users with a way to add the collector configuration.

**Comment by xoscar** [comment]
Setup Wizzard Flow Chart:

```mermaid
graph TD
    A[User] -->|Starts Setup| B[Wizard]
    B --> C[Display instructions]
    C --> |Click Next| D[Display instructions]
    D --> F{Select Data Store}
    F --> G[Jaeger]
    F --> Q[OtelCollector]
    Q --> R[Show Config Tutorial]
    F --> H[Tempo]
    F --> I[SignalFX]
    F --> J[OpenSearch]
    H --> K[Fill Config Details]
    I --> K
    J --> K
    G --> K
    R --> K
    K --> L[Test Connection]
    L --> M{Exporter?}
    M --> |No| N[Save Changes]
    M --> |Yes| O[Fill Exported Details]
    O --> P[Test Connection]
    P --> N
```

**Comment by xoscar** [comment]
In my opinion we have, because if the setup requires an exporter then Tracetest wont work with just the data store.

**Comment by xoscar** [comment]
OpenAPI definition proposal https://github.com/kubeshop/tracetest/pull/1641

**Comment by schoren** [comment]
I left a comment in the PR, but I think it's more appropriated here.

My only concern is the amount of duplication introduced by having the entire config file defined in OpenAPI Specs./. Can't we figure out a way to send config updates without the need to duplicate everything?

In this case, I think it's particularly impractical because some of our definitions are "external", like the tempo/jaeger gRPC endpoints.

What if we have a single endpoint, like PUT /api/server/config that accepts an entire yaml config file? Then the UI can implement the parts that are neccesary and the backend can "merge" partial updated with existing config.
This approach would leave to a much more flexible endpoint and config format, and decouples the UI from the actual server implementation.

Thoughts?

**Comment by xoscar** [comment]
Next topic:

1. Updated config propagation - not going for this moment - high effort  - low gains (future).
2. Resume tests strategy (not a problem for the short term) - downtimes, restarts the services, we should tell users that a server restart is required and there will be some downtime.

- Work on test connection services spec.

**Comment by xoscar** [comment]
Open API changes have been merged, we need to work on the test connection specification so we have everything covered.
