### ISSUE TITLE
[DRAFT] Trace id as a Trigger Type

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1642]
We should add the ability to define a test that accepts a trace parent id as the trigger. This will allow Tracetests to be created that can be run at any time against a transaction that has already be run in the system under test. Created this issue to discuss and further develop the concept.

Some possible use cases:
- A user has a series of test specs defined for a particular type of transaction. They want to be able to apply those test specs to transactions in production to verify proper operation. 
- A user has another system triggering transactions, and wants to apply tracetests to those transactions. An example would be a load testing system - if the customer can determine the parent trace id for each run via the load testing tool, they could have tracetest run against the trace by scripting a run via the CLI and passing the parent test id.
- A user wants to wants to run a test against a trace from a transaction that was 'bad' and ensure the test specs would identify the problem. If it does not, the user would want to be able to modify the specs so it does properly identify the problem and fail the test. They could then enhance their tests that are part of their CI/CD flow.

Some considerations / concerns / open questions:
- Should a test that has a defined trigger other than 'trace id' be able to be run against a trace id? We would need to ignore any test specs applied against the data contained in the request / response trace, as we will not have those as we did not trigger the test. We need to consider how we would show the results - we would need to label the test result as 'run against a trace' and distinguish it from a normal test run.
- Enabling for OTel collector based installs. Tracetest has to be able to get the trace, which is a requirement for any Tracetest. With any directly support trace data source, Tracetest will be able to grab the trace based on the parent trace id. When a user is utilizing the OTel Collector, however, the trace is sent directly to Tracetest via a second pipeline in the OTel collector. This collection is enabled by Tracetest adding a key/value pair to the trace state (see https://docs.tracetest.io/getting-started/supported-backends#creating-a-new-pipeline-for-your-traces). Due to this, unless the user devises another mean to make sure the trace is sent to Tracetest, using the parent trace id as a trigger will not work for an Otel config based install. There are workarounds, for instance in a dedicated test env a customer could opt to send all traces to Tracetest via the OTel collector config.

**Comment by kdhamric** [comment]
The second possible use case was implemented when getting k6 to work with Tracetest via #1824 which @xoscar worked on.

@olha23 - think about how we would handle the first and the third use case, which are very similar. In bot, we have a test and want to run it against a trace that was not triggered by Tracetest. We need to think how we would cover the first open question where it discusses how to show these runs, ie:
_We need to consider how we would show the results - we would need to label the test result as 'run against a trace' and distinguish it from a normal test run._

**Comment by xoscar** [comment]
@kdhamric how would you like to proceed with this one? should it be good to discuss it next week during planning and start working on it post-chaining v2?

Or should we try to squeeze it as part of the major chaining v2 changes?

**Comment by kdhamric** [comment]
Would like to get @olha23 thoughts on how we might do this in the UI as I have no vision for it. Maybe have a meeting with @olha23 @xoscar @jorgeepc and anybody else that wants to attend and see if we can come up with a vision of how it would integrate in. 

@olha23 - can you set this up?

**Comment by kdhamric** [comment]
Discussed with @olha23 @jorgeepc @xoscar whether we should work on the top and bottom use case (the middle one is implemented). The consensus is that there are workarounds now (download the test definition yaml, change the trigger type to 'trace id' based, and run that test with the trace parent id you wanted to 'test' your test against. Not perfect, but workable until we have more input on these use cases from users. Lets close this as done and revisit if needed.
