### ISSUE TITLE
[Chaining V2] Prompt for values when running a test or transaction with undefined variables

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1643]
When a user runs a test or a transaction, any variables that will be needed but are not defined by the time it is used should be prompted for.

Here are some use cases:
- a user wants a test or transaction they can run on a particular user, order id, etc that is configurable at run time. This would make running an adhoc test in an environment, even production, very easy and convenient. In this case, the user would reference the variable, but not add it to the environment. Each time they run the test or transaction, they would be prompted for the unspecified variables.
- a user wants to define 3 tests as part of a transaction. The first test has an output variable, and this is used by the second test. They define the first test. They then go to define the second test, and reference the variable. When they run the second test initially it will not work because the variable is not defined as they are running outside of a transaction. They could alter the environment to hard code the value, create the full transaction, then remove the environmental variable, but this is a hack and not user friendly.

This capability should be present on both the UI and CLI. On the CLI, we would need options to:
- interactively answer any undefined vars
- specify any variables that will be undefined by passing them as part of the cli vs waiting for a prompt (not sure about this... could just pass an env with the vars defined - we need to discuss this)
- for both UI and CLI, the promoting screen should show the variable name and ask for the value. If there have been previous runs of the test, the value of the variable for the last run should be used if available.

**Comment by xoscar** [comment]
- What happens when a user creates a brand new test with missing variables (create & run scenario)?
- Work on diagrams and use cases/edge cases for this ticket.

**Comment by xoscar** [comment]
The following sequence diagrams describe how the two new services will work to get the missing variables from a test or a transaction.

## Test:

```mermaid
sequenceDiagram
    Frontend->>+Server: GET /${testId}/variables?environmentId=<envId>
    Server->>+Database: Fetch Test
    Database-->>-Server: Return test
    alt is environment Id present
        Server->>+Database: Fetch Environment
        Database-->>-Server: Return Environment
        Server->>Server: Initializes env from database result
    else
        Server->>Server: Initializes empty env
    end
    Server->>Server: Adds test outputs to the env
    Server->>Server: Analyzes test looking for interpolations
    Server->>Server: Generates variables based on interpolations
    Server->>Server: Matches variables with env to find missing entries
    Server-->>-Frontend: Returns env, variables and missing
```

## Transaction:

```mermaid
sequenceDiagram
    Frontend->>+Server: GET /{tId}/variables?environmentId=<envId>
    Server->>+Database: Fetches Transaction
    Database-->>-Server: Returns Transaction
    alt is environment Id present
        Server->>+Database: Fetch Environment
        Database-->>-Server: Return Environment
        Server->>Server: Initializes env from database result
    else
        Server->>Server: Initializes empty env
    end
    loop For Every Test in Transaction
        Server->>+Database: Fetches Test
        Database-->>-Server: Returns Test
        Server->>Server: Adds test outputs to the env
        Server->>Server: Analyzes test looking for interpolations
        Server->>Server: Generates variables based on interpolations
        Server->>Server: Matches variables with env to find missing entries
    end
    Server-->>-Frontend: Returns env, variables and missing
```

The idea is for services to return a response similar as the following:
```json
{
  "environment": {
    "HOST": "localhost",
    "PORT": "3000",
    "POKE_ID": "2"
  },
  "variables": ["STATUS_CODE", "HOST", "PORT", "POKE_ID"],
  "missing": ["STATUS_CODE"]
}
```

Where we can see that the `STATUS_CODE` is the one missing as its not present in the environment map.
From there, clients can decide how to proceed.

**Comment by xoscar** [comment]
Update for the response for transactions to look like this:
```json
{
  "testId": {
    "environment": {
      "HOST": "localhost",
      "PORT": "3000",
      "POKE_ID": "2"
    },
    "variables": ["STATUS_CODE", "HOST", "PORT", "POKE_ID"],
    "missing": ["STATUS_CODE"]
  }
}
```

That way we can go test by test, showing the user which variables are missing, what do you think? with this info we can do smart things like "hey when the transaction gets to this test this is how the env is going to look like, but we are still missing the following entries"
