### ISSUE TITLE
[In-App Config] Setup Wizard - Data Store Step for OpenTelemetry Collector

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1654]
AC1:
As a user looking at the UI setup wizard
And I have selected 'OpenTelemetry Collector' (or 'OTel Collector' if it is too long visually)
The user should be see instructions that help them understand how Tracetest works with the OTel Collector and be able to 'enable' the use of the OpenTelemetry Collector with Tracetest

We want a brief explanation, then point to the documentation

Tracetest can work with any distributed tracing solution that is utilizing the [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/) via a second pipeline. The second pipeline enables your current tracing system to send only Tracetest spans to Tracetest, while all other spans continue to go to the backend of your choice. 

There are 2 steps:
Change your OpenTelemetry Collector configuration (see docs)
Enable Tracetest server to receive the traces (On / Off)

We want to point to the documentation at: https://docs.tracetest.io/getting-started/supported-backends#configuring-your-collector-to-send-traces-to-tracetest

Use the OpenTelemetry icon: https://cncf-branding.netlify.app/projects/opentelemetry/

**Comment by kdhamric** [comment]
@olha23 Can you take a shot at a design for this?

**Comment by olha23** [comment]
@kdhamric please check here https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=976%3A21889&t=IaR0vLTu29utbyz7-1

**Comment by xoscar** [comment]
@mathnogueira I'd encourage you to take a look at the designs, and how we can handle it from the technical side, I thought we needed the collector endpoint or something like that isn't it? if not, then we need to discuss how we want the openAPI spec to look for this scenario.
