### ISSUE TITLE
[In-App Config] Add documentation link to each trace data store screen

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1657]
As a user,
I want to be able to get further information about the trace data store I currently have selected. It may be because:
- I am new to OTel and need more information
- it may be because I do not have any OTel tracing setup yet and need to know how to install it
- I may have the trace data store and be knowledgable, but I just need to see an example so I can better understand specifics about the configuration screen
So we want to provide a link to a specific page in our docs that is dedicated to configuring that particular trace data store.

Suggested implementation / wording:
I would probably have a link that says: "Need more information about setting up Jaeger with Tracetest?"

**Comment by olha23** [comment]
Check the mockups here 👉https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=869%3A22167&t=IaR0vLTu29utbyz7-1

**Comment by xoscar** [comment]
@kdhamric please provide the links to the documentation for each of the data stores. CC: @adnanrahic

**Comment by xoscar** [comment]
Waiting on @adnanrahic to get the doc links
