### ISSUE TITLE
[docs] Use OpenTelemetry Collector as a secondary pipeline for Tracetest

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#1663]
Tracetest can work with any distributed tracing solution that is utilizing the [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/) via a second pipeline. 

The second pipeline enables your current tracing system to send only Tracetest spans to Tracetest, while all other spans continue to go to the backend of your choice.

Enable the OpenTelemetry Collector capability below and alter your OpenTelemetry Collector config file to:

- add a processor to enable tail sampling to get the specific spans that are labeled with the key 'tracetest' in the trace state
- add an exporter to export to the tracetest server which is listening on port 21321
- add a second pipeline to funnel all your span data through the new processor and send it to the next exporter

**Comment by kdhamric** [comment]
@adnanrahic Is this done with this having been created: https://docs.tracetest.io/configuration/connecting-to-data-stores/opentelemetry-collector? Trying to see if we can close this.

**Comment by adnanrahic** [comment]
@kdhamric - yes. Closing this.
