### ISSUE TITLE
[In-App Config] Test Trace Data Store Connection 

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1679]
We need to provide the user with information about the test(s) ran when pressing the 'Test Trace Data Store' button when configuring a trace data store.

Providing more details forAC6 from #1622, ie:

AC6: (from other issue, but all applies)
As a user looking at the UI setup wizard
After filling in the details to configure the exporter section
And I choose the test connection option
I should be able to see the result (error or success)
And details about the results

Specific to these requirements, these are expanded acceptance criteria:

AC1: 
As a user, 
I should be able to tell that the 'test connection' button was pressed
And that we are awaiting results

AC2: 
As a user, 
I should be able to tell the exact test(s) that ran as part of the connection testing (1-4 total tests)
And have details for each individual test
Including information about 1) what was tested with the each test, 2) the result / error message from the test and 3) the status of it (pass / failed)
As well as the overall test result (passed / failed)

**Comment by olha23** [comment]
mockups here https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1103%3A21127&t=OQa7f7SEOtqIGzz0-1
