### ISSUE TITLE
kill the empty tooltips

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1715]
We need to kill the empty tooltips like these:

![Image](https://user-images.githubusercontent.com/5725840/208687692-f35268fc-dc4c-40c1-91c5-5c4852efd092.png)
![Image](https://user-images.githubusercontent.com/5725840/208687693-91abb459-3c33-4ef5-b720-cab9ef0a782b.png)

**Comment by xoscar** [comment]
@olha23 do you mind adding more info to this ticket? sometimes I see the empty tooltip but just for a fraction of time, maybe you have seen a scenario where it is displayed for longer periods. Thanks!

**Comment by olensmar** [comment]
@xoscar not sure how I can help on this!?
