### ISSUE TITLE
Provide access via UI to determine what version the Tracetest server is running

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1763]
As a user,
I want to be able to tell what version of Tracetest I am utilizing
When I am accessing Tracetest via the browser

Need @olha23 to do design first

**Comment by olha23** [comment]
@kdhamric i added mockup with app version and also added modal with latest update just for any case  
https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1240%3A25409&t=CCbRP4RJtS7ijdIy-1
