### ISSUE TITLE
Improve diagnostics returned to a user when executing a test trigger

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1788]
As a User
Running a test
When a test fails
I need helpful information so I know what prevented the successful run

Flow would look like this:
User runs the test
Tracetest triggers the event
If success:
every thing works as usual
if fails:
Run diagnosis steps to try to figure out why the step failed (DNS lookup for example). For other trigger methods, we can use similar approaches (try pinging the  gRPC endpoint or checking the state of the queue -- when we start supporting queues)

We will need a way to clearly show the user the diagnostic information providing details of:
- what we tried in testing the trigger (ie show each step)
- what the response to each step were, indicating 'successful' steps vs failed steps

**Comment by olha23** [comment]
@kdhamric @mathnogueira can you guys check this mockups please and provide your feedback:
https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1313%3A22046&t=Ab3J7BbrFTxC11ex-1

**Comment by danielbdias** [comment]
hi folks, about the status on the corner of the screen, one suggestion is to have a simplified workflow status like some CIs do. Here is an example on how Gitlab CI deals with different steps:

<img width="104" alt="image" src="https://user-images.githubusercontent.com/12397879/211586498-8796ffd2-c25d-4eb1-a951-5b2bd1e5616b.png">

It does make sense?

**Comment by xoscar** [comment]
Will be done alongside [Implement 'help on failed test' response#2040](https://github.com/kubeshop/tracetest/issues/2040)

**Comment by xoscar** [comment]
Closing as duplicated
