### ISSUE TITLE
Support Amazon x-ray

### ISSUE THREAD

**Issue by povilasv** [kubeshop/tracetest#179]
1. Make an app that sends data to x-ray
2. Enable 1/10 client sampling
3. Test if tracetest  forces client to send the trace
4. Implement get trace by id for Amazon x-ray
5. Convert amazon trace model to otel.

Get trace by id API -> https://docs.aws.amazon.com/xray/latest/devguide/xray-api-gettingdata.html

**Comment by kdhamric** [comment]
@mathnogueira Are you going to be working off this issue once you start on X-Ray? I want to tag @mik3h0 on which ever issue you do the work on. His company uses Amazon x-ray and he may be able to assist in trying it once we have it integrated.
