### ISSUE TITLE
Typescript errors when trying to run docker build web

### ISSUE THREAD

**Issue by michaelhyatt** [kubeshop/tracetest#1791]
**Describe the bug**
I tried to run my own build using `docker build --no-cache -t kubeshop/tracetest:latest` but it failed to build `web` component throwing TypeScript compilation errors, such as:

```
 > [build-js 7/7] RUN npm run build:
#0 3.298 
#0 3.298 > web@0.1.0 build
#0 3.298 > craco build
#0 3.298 
#0 15.54 Creating an optimized production build...
#0 795.6 Failed to compile.
#0 795.6 
#0 795.6 TS2322: Type 'IKeyValue[] | Pick<never, string | number | symbol>[]' is not assignable to type '{ [x: string]: any[] | undefined; [x: number]: any[] | undefined; }[] | undefined'.
#0 795.6   Type 'IKeyValue[]' is not assignable to type '{ [x: string]: any[] | undefined; [x: number]: any[] | undefined; }[]'.
#0 795.6     Type 'IKeyValue' is not assignable to type '{ [x: string]: any[] | undefined; [x: number]: any[] | undefined; }'.
#0 795.6       Index signature is missing in type 'IKeyValue'.
#0 795.6     24 |   const onRefreshData = useCallback(async () => {
#0 795.6     25 |     const {url = '', body = '', method = HTTP_METHOD.GET, headers = DEFAULT_HEADERS} = draftTest as IHttpValues;
#0 795.6   > 26 |     form.setFieldsValue({url, body, method: method as HTTP_METHOD, headers});
#0 795.6        |                                                                    ^^^^^^^
#0 795.6     27 |
#0 795.6     28 |     try {
#0 795.6     29 |       form.validateFields();
#0 795.6 
#0 795.6 
```

**To Reproduce**
1. The same happens with the main build, but can also be reproduced with the build running the `Dockerfile` in the web directory. Go to the web directory of the project
2. Run `docker build --no-cache .` in the web directory or `docker build -t kubeshop/tracetest:latest --no-cache .` in the root directory.
 
**Expected behavior**
A clean build of the docker image.

**Comment by xoscar** [comment]
Hello @michaelhyatt thanks for opening the issue.

The docker file from the `/web` directory was never meant to be used, I believe it was a leftover from a previous version, sorry for the confusion.

I will remove it as part of a fix for this issue so it doesn't cause any problems moving forward.

If you want to build and run the tracetest docker version you can use the root folder Dockerfile or the docker-compose file directly. 

Thanks!

**Comment by jorgeepc** [comment]
@xoscar  I'm not sure if the `web/Dockerfile` is causing the issue in this case. I tested locally and is working fine. Also @michaelhyatt mentions that the issue happens with the root Dockerfile too. However, I can't see typescript errors using main. Are you using a different branch or did you modify the web code @michaelhyatt ?

**Comment by michaelhyatt** [comment]
I have made a few changes, but not to the file flagged, strange. I was able to run a clean build on a newly checked-out main branch. Feel free to downgrade the urgency on it.
