### ISSUE TITLE
When changing data store configuration we should warn the current config will be removed

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1799]
As a user,
When I switch from one defined data store to another
I should be warned that my other definition will be removed / lost
So that I am not sad!

AC1:
If a data store is already defined, when saving a new type of data store, 
We should show a message that says:
```
Are you sure you want to save this data store configuration?

Saving will delete your previous configuration of the Jaeger data store (where Jaeger is the name of the currently configured data store)
```

The message should stay as it currently is if:
- you have no data store configured
- if you are just altering the current config (ie staying with the same data store type)

https://www.loom.com/share/7f6dd6d74f8345a3a6319a60aedfda6a

Tagging @olha23 to make sure she does not want to alter this.

**Comment by olha23** [comment]
yea i think we just need to add the text that we delete previous configuration
