### ISSUE TITLE
Project Prioritization Matrix

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#181]
-  decide which features should be included in the next version of a product
- prioritize them

**Comment by kdhamric** [comment]
Performed a prioritization process on Friday, April 29th.  Documented https://docs.google.com/spreadsheets/d/1K6tqm5Aig3TLBk31w8OfH_kI_zcK71XDl3QgbQQMbzw/edit?usp=sharing
![image](https://user-images.githubusercontent.com/1385894/166500338-2146a603-8dee-44d4-a615-da6685605907.png)

Used Miro as part of this:
https://miro.com/app/board/uXjVO4uWeiQ=/?share_link_id=139925425661
![image](https://user-images.githubusercontent.com/1385894/166500198-98231540-bda4-48d7-bf7d-9f2a02138742.png)
