### ISSUE TITLE
GetTraceByID fails to get a trace when using Elastic APM with OTel example

### ISSUE THREAD

**Issue by michaelhyatt** [kubeshop/tracetest#1834]
**Describe the bug**
While `Trigger` tab is working, the `Trace` and `Test` tabs are showing grayed-out outlines hanging. The tracetest log shows the following error:
```
2023/01/13 01:58:48 [TracePoller] Test JZEXnsh4g Run 1: recieved job
2023/01/13 01:58:48 [PollerExecutor] Test JZEXnsh4g Run 1: ExecuteRequest
2023/01/13 01:58:48 [PollerExecutor] Test JZEXnsh4g Run 1: GetTraceByID (traceID 65e1711e00017db46eba2f0d0bd0a148) error: trace not found
2023/01/13 01:58:48 [TracePoller] Test JZEXnsh4g Run 1: ExecuteRequest Error: trace not found
requeuing result 1 for 0 time
```

Kibana shows the trace exists:
<img width="2553" alt="image" src="https://user-images.githubusercontent.com/15670925/212220529-39d4a7b2-7da7-4d1b-989c-a501b28a74b6.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. cd examples/tracetest-elasticapm-with-otel
2. Follow the example README.md to start the stack.
3. Run a simple test from README.md and observe the `Trace` and `Test` tabs being unresponsive.
4. `docker logs tracetest-elasticapm-with-otel-tracetest-1` to show the tracetest error.

**Comment by adnanrahic** [comment]
Hi @michaelhyatt ! Thanks for opening this issue. We'll have a look at this and make sure to get back to you ASAP.
