### ISSUE TITLE
Allow users to find edit option to rename tests through the WebUI

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#1848]
**Describe the enhancement you'd like to see**

When I'm using the Web UI, if I create a test with the wrong name, I can't rename it.

**Comment by olha23** [comment]
you can rename the test 
<img width="721" alt="Screenshot 2023-01-18 at 2 19 27 PM" src="https://user-images.githubusercontent.com/5725840/213262542-b329e830-97db-4e1e-84b7-bfa70ed5ee21.png">

**Comment by danielbdias** [comment]
I'll try to do that soon and show it to you, @jorgeepc and @xoscar !
