### ISSUE TITLE
Enable users to put a description into a test spec, allowing it to document it

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#1849]
**Describe the enhancement you'd like to see**

Sometimes a spec assertion could be difficult to understand at first glance. We could add a description field on a spec to allow the user to explain what is that assertion.

For instance, I have these specs:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/12397879/213266385-dcbaec4f-45af-47b8-9685-027643e701d7.png">

And I wanted to do those explanations:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/12397879/213266953-4c358105-870c-45d4-95ed-4af86830b0bb.png">

**Comment by danielbdias** [comment]
On the CLI, we could have a result like this:
```sh
✔ Add product to the cart (http://tracetest-otel-demo-v2.tracetest.io/test/RPQ-oko4g/run/3/test)
    ✔ Validate that the API was called with the desired product ID
    ✔ Validate that the item was persisted correctly
```

**Comment by jorgeepc** [comment]
Hey @danielbdias I think the API already supports a `name` field for a `test spec`. We just need to include it in the FE.

**Comment by kdhamric** [comment]
It would definitely be a nice enhancement!

**Comment by danielbdias** [comment]
Cool! I saw that it was added a few days ago! I can tackle it after finishing our docs and Keptn presentation on Monday! Or can tackle it together, splitting it into two tasks one for the Web UI and another for the CLI.

**Comment by jorgeepc** [comment]
Let's split this task for now. I can start adding the FE support. I think I already have a draft for that. @danielbdias
