### ISSUE TITLE
Get All Results when searching documentation says no result found

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1855]
When searching docs, if you click 'See all X results' you get a page with 'No results were found'

![image](https://user-images.githubusercontent.com/1385894/213517575-efbeb701-3ca0-4274-b015-e56fcaa568a7.png)

![image](https://user-images.githubusercontent.com/1385894/213517625-e51b9a65-0907-4926-ac80-283c51614224.png)

**Comment by adnanrahic** [comment]
Seems like a bug in Docusaurus. Fixed by removing the `See all Results` button.
