### ISSUE TITLE
Change Trace Id based trigger to always ask for a variable name

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1857]
As a User,
When selecting a test with a TraceID based trigger,
I should be asked for a variable name, not a trace id number

Currently, we are asking for a trace id, and provide the user with the option to enter a variable name by entering ${env:mytraceid}

We want to change this so we always expect a variable name to be used when initially defining the traceID based trigger.

The third form in the wizard should use this text:
Title: Enter the variable name to use for the Trace Id

Subheading: Variable name:
text input: Default the value to 'traceId'
Help text: Please enter a variable name for the trace id or accept the default 'traceId' name

When the user clicks create, we should change the variable name to ${env:VARIABLENAMEENTERED} and that value should show when viewing the 'Edit Test' form. We will 'build' the expression properly and show it - they can alter it from there (ie see below)

![image](https://user-images.githubusercontent.com/1385894/213574389-3369f483-d3c3-42d3-b61f-afcc5ff76b61.png)

@olha23 let me know if you have thoughts....

**Comment by olha23** [comment]
yea make sense, i will add the mockups

**Comment by olha23** [comment]
@kdhamric do we need to have ability to add couple variables name? see mockups - https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1495%3A25017&t=EgMwXPc0AZCYxZYy-1
