### ISSUE TITLE
Create test definition scenarios for Tracetest / Keptn integration

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#1881]
To show our community the type of tests that we can do with Tracetest and Keptn, we should create different testing scenarios.

Examples of scenarios:
- Test time to consume messages from a queue
- Validate cache hits on an API
- Validate calls to external resources

**Comment by kdhamric** [comment]
Any effort we can make to leverage the OTel community demo for this would be good. It is uused by others in the OTel community, so at least some people will see it and know the flow beforehand (not all).
