### ISSUE TITLE
enable CLI to receive server address as an option

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1893]
**Is your feature request related to a problem? Please describe.**
When you install tracetest for running in a CI environment, we have to apply the data store configuration to the server. It would be really useful if I could set the server address on the `tracetest` command instead of having to go through `tracetest configure`.

**Describe the solution you'd like**
```
tracetest -e <endpoint> test run ...
```

**Comment by jorgeepc** [comment]
Is this done guys? I see we merged #1913 cc: @schoren @mathnogueira

**Comment by schoren** [comment]
Yes, that's the PR that fixes this. Sorry!
