### ISSUE TITLE
Variables in the body of a trigger are not detected as undefined variables when running the test

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#1895]
**Describe the bug**
If I use environment variables in the body of a test trigger, and try to run the test(without any environment selected) the mentioned variables are not considered as undefined.

**To Reproduce**
1. Go to our beta env, verify that no environment is selected.
2. Click on create a test.
3. Select the Pokeshop Add demo option.
4. Use a `${env:var}` in the request body field.
5. Save/Run and you will notice that the app is not asking you for the undefined variable.

**Expected behavior**
The app should detect that we have a undefined variable in the request body field.

**Screenshots**
![Screenshot 2023-01-26 at 11 46 57](https://user-images.githubusercontent.com/3879892/214896945-e3a538f0-bf3b-44b9-ba67-4a96742ed38b.png)
![Screenshot 2023-01-26 at 11 47 27](https://user-images.githubusercontent.com/3879892/214896950-cbd27d34-9649-480b-a0e8-75daed74eb09.png)

**Comment by mathnogueira** [comment]
I'm investigating this bug. It's happening because the expression engine expects strings to be wrapped in quotes. This is problematic with JSON. I'll have to find a way of escaping the JSON without breaking it.
