### ISSUE TITLE
[bug] distributed trace is not loaded correctly but shows up on hard page reload

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#1904]
**Describe the bug**
When I run a test it does not load any traces… but when I hard reload the page, the traces load and my assertions pass. However the prior empty state is saved in the test list. Very strange.

https://www.loom.com/share/bb1d23bbdb734274b04d6439739f96e0

**To Reproduce**
1. Go to a test run
2. Click on run test
3. Wait for page to refresh and display distributed trace
4. Distributed trace is not loaded
5. On reloading the page manually it shows up

**Expected behavior**
Distributed trace should load initially.

**Comment by adnanrahic** [comment]
@xoscar FYI, I just ran this test again with a few different versions that work as expected without this bug:

- `v0.9.3`
- `v0.9.2`
- `v0.9.1`
- `v0.9.0`


This issue happens in versions:

- `v0.9.4`
- `v0.9.5` as in my initial test


Seems it started with `v0.9.4`.

**Comment by xoscar** [comment]
@adnanrahic what setup are you using here? is this a different instrumented app than the pokeshop/otel demo? what data store and config are you using? 🤔

**Comment by mathnogueira** [comment]
@adnanrahic what was the application you were using to reproduce it and what was the data store?

**Comment by jorgeepc** [comment]
@mathnogueira in the video I see a `books service`, maybe Adnan is using this example https://github.com/kubeshop/tracetest/tree/main/examples/quick-start-nodejs-manual-instrumentation

**Comment by adnanrahic** [comment]
@jorgeepc is right. That's the one I used.

/cc @mathnogueira @xoscar

**Comment by adnanrahic** [comment]
@jorgeepc is right. That's the one I used.

/cc @mathnogueira @xoscar

**Comment by adnanrahic** [comment]
@danielbdias - Will your PR https://github.com/kubeshop/tracetest/pull/2011 close this issue?

**Comment by danielbdias** [comment]
Team, this happened because our TracePoller stopped before receiving all trace spans. I've added another stopping condition on https://github.com/kubeshop/tracetest/pull/2059 to avoid this situation.
