### ISSUE TITLE
[VIPER] Allow config from different sources

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1911]
Today, the only way we support ingesting the server settings is through having a `config.yaml` dropped in the same DIR as the rest of the binary assets, which causes some issues when trying to deploy Tracetest using tools like AWS ECS that do not provide a simple way of uploading data to volumes on startup.

Here's an [open issue](https://github.com/aws/containers-roadmap/issues/56) with possible workarounds, but we should have an easier way to achieve this for our Tracetest image.

Acceptance criteria:
AC1:
As a user wanting to deploy the Tracetest image
I should be able to configure the basic settings using environment variables
And have default values for settings that are not required during the startup

Required:
DB connection string

Non-required:
Analytics
Poller config
Data store

**Comment by schoren** [comment]
Will be fixed by https://github.com/kubeshop/tracetest/issues/1937
