### ISSUE TITLE
Tracetest AWS ECR docker Image support

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1912]
As we are continuously catching more attention from teams that are using AWS as a primary cloud provider and using alternative setups to Kubernetes like Serverless, we need to support an official tracetest ECR docker image outside of just the docker hub one.

Acceptance Criteria
AC1:
As a developer tagging the repo with a new version
The docker image build should be also uploaded to AWS ECR.

AC2:
As a user installing tracetest in my AWS setup (not k8)
I should be able to use an AWS ECR-based image for the installation

**Comment by danielbdias** [comment]
Hum... maybe we could create a `kind of` mirror from Docker Hub to ECR? Looking at posts like [this](https://stackoverflow.com/questions/56037131/pulling-public-images-from-dockerhub-in-ecs-fargate) it seems more a configuration that we can recommend for our users.
