### ISSUE TITLE
Improve CLI documentation

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#1935]
We need to:

- [x] cover all commands (#1582)
  * configure
  * datastore
    * apply
    * export
    * list
  * environment
    * apply
  * test
    * export
    * list 
    * run
- [x] show examples for all definition file types
  * test
  * transaction
  * environment
  * datastore

**Comment by kdhamric** [comment]
@mathnogueira Do we still need this? Close it if not.
