### ISSUE TITLE
[DataStores] Research Connectivity issues with Grafana Cloud Tempo

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#1938]
While running a test to validate tempo connection
We found out that our settings for tempo don't support grafana cloud tempo yet

We need to investigate and fix the integration.

**Comment by xoscar** [comment]
Seems that the Tempo cloud version doesn't support the GRPC client we use to connect from Tracetest, the options now are:
1. Wait for a potential update in the future to support GRPC
2. Add a different connection mechanism for Tempo Cloud (only) to use HTTP instead


CC: @schoren @mathnogueira @kdhamric @jorgeepc

**Comment by kdhamric** [comment]
I think we should do this in the next few weeks. Adding it to our v0.10 big boulder board.

**Comment by xoscar** [comment]
The team agreed to add an option to the Tempo connector to support both GRPC and HTTP
