### ISSUE TITLE
[docs] Document Tracetest integration with Datadog 

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#1969]
We need to improve the documentation presented on https://github.com/kubeshop/tracetest/pull/1968 , to show your users how to use Tracetest with Datadog

**Comment by danielbdias** [comment]
@adnanrahic can you help me with this later?

**Comment by adnanrahic** [comment]
Definitely! Just leaving a recap here of the pages we need for Datadog based on what we did for Lightstep.

Config page docs: https://docs.tracetest.io/configuration/connecting-to-data-stores/lightstep
Recipe: https://docs.tracetest.io/examples-tutorials/recipes/running-tracetest-with-lightstep/

Examples with otel:

- https://github.com/kubeshop/tracetest/tree/main/examples/tracetest-lightstep
- https://github.com/kubeshop/tracetest/tree/main/examples/tracetest-lightstep-otel-demo
