### ISSUE TITLE
Require a url when creating a HTTP based request

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1979]
As a user,
When I am creating a HTTP based test
I should not be allowed to leave the url field blank.

Currently the system allows you to create http tests and not enter a url. We should make this a required field and not allow the test to be created from the wizard or saved / run unless it has a value.

There is a secondary issue related to this, and we may need to create another issue and resolve it. Tests run without a URL continue to show as 'running' and there is no way to stop them. Because you cannot stop them, you cannot correct the url and rerun the test. We might want to fix that issue first as I do not know how to reproduce the 'will not stop running' issue other than enter a test with no URL.

![image](https://user-images.githubusercontent.com/1385894/218339131-51ff5a80-a913-40af-8585-a95a045de864.png)

**Comment by jorgeepc** [comment]
This should be fixed by #2027 Could you validate it @kdhamric ?

**Comment by xoscar** [comment]
@kdhamric do you mind taking a look a this?

**Comment by kdhamric** [comment]
Verified - closing
