### ISSUE TITLE
Creating a test then switching trigger type requires name to be adjusted

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1980]
If you start to create a test under on trigger type, then hit back and select a different trigger type, you have to alter the name of the test to get the 'Next' button to reenable.

https://www.loom.com/share/2edcd091807a473e95ad3e5344a42478

**Comment by Meyazhagan** [comment]
@kdhamric @danielbdias Can I work on this issue?

**Comment by ShuhaoZQGG** [comment]
Hi, I notice this issue is still open - cool if I jump in and give it a shot?
