### ISSUE TITLE
Environments page improvement

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#1986]
Link for design - https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=1686%3A28255&t=NTCvZlJORKNhyutP-1

**Comment by xoscar** [comment]
@olha23 I think this is done right? as it has the link fo the designs?

**Comment by olha23** [comment]
@xoscar yes
