### ISSUE TITLE
[config] create a resource manager

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2016]
We will be implementing several config resources that will have a very similar CRUD interface. We agreed that we can use a `resource manager`, a generalization of the CRUD operations of any resource, so we can:

1. reduce code duplication
2. have flexibility for adding new resources in the future

This issue needs some research before settling on an implementation path.

**Comment by danielbdias** [comment]
Database persistence:
- [Bun](https://bun.uptrace.dev/)
- [GORM](https://gorm.io/)
- [Pop](https://github.com/gobuffalo/pop)

HTTP Operations:
- [Gin](https://github.com/gin-gonic/gin#gin-web-framework)
- [Echo](https://echo.labstack.com/) - [CRUD example](https://echo.labstack.com/cookbook/crud/)
- [Buffalo](https://github.com/gobuffalo/buffalo)

**Comment by danielbdias** [comment]
As far as I see, k8s uses [openapi](https://github.com/kubernetes/api/blob/master/apps/v1/types.go) to define servers operations in a similar way that we do: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/server.go
