### ISSUE TITLE
Improve icon "more" on different pages

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2085]
We need to replace this icon:

![Image](https://user-images.githubusercontent.com/5725840/224824679-3610f855-ac90-48e4-91ff-5ad933a3a17c.png)

and not forget about other place where we use these icons
mockups here: https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2049%3A34432&t=IStfSpX1k87qvr9Z-1

add svg icon:
![icon](https://user-images.githubusercontent.com/5725840/225115661-b1c9165f-b60c-43f8-9a1a-62cfde970589.svg)

**Comment by tarangverma** [comment]
can i work in this issue ?

**Comment by xoscar** [comment]
Hello @tarangverma thanks for reaching out, yes I think this would be a great issue for you to take a look!
