### ISSUE TITLE
runtime error: slice bounds out of range [:22] with capacity 20

### ISSUE THREAD

**Issue by correa-juan** [kubeshop/tracetest#2117]
**Describe the bug**
installation fails 

**To Reproduce**
1. exec tracetest server install
2. select kubernetes
3. select instalation with demo 

**Expected behavior**
Install tracetest in kubernetes with a demo 

**Screenshots**
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/127070539/223327186-064e4fc5-be11-4490-bd71-625210e15c29.png">

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/127070539/223327620-c0d3c6c8-95d5-4139-bc8d-5d61b9c60b77.png">

**Additional context**
tracetest version: v0.10.0

**Comment by adnanrahic** [comment]
Hi @correa-juan ! Thanks for opening this issue. I've asked the engineers, but it's still a bit early in their timezones. They'll jump into this thread when they wake up.

**Comment by schoren** [comment]
Hi @correa-juan, I'm the engineer investigating this bug. It looks like you hit a bug in the CLI UI library we use internally for the installer tool. The bug hits when you have 3 or more contexts configured in your kuberenetes config file. Updating the library seems to fix it, but I'm not 100% sure. So, 2 questions:

1. Can you confirm your Kubernetes config file has 3 or more contexts? A simple yes/no is enough for confirmation.
2. Would you be willing to try running a dev build just to confirm the issue?

Thanks

**Comment by Juandavi1** [comment]
Hi 👋 
Thanks for answering 

1. Yes 
2. Yes

**Comment by schoren** [comment]
@correa-juan (or is it @Juandavi1?) I've merged the fix. Can you please download the nightly CLI? https://github.com/kubeshop/tracetest/releases/tag/nightly

Here's a script to do it, just make sure you update the download url with the correct platform.

```sh
mkdir /tmp/test
cd /tmp/test

curl -sLO https://github.com/kubeshop/tracetest/releases/download/nightly/tracetest_latest_darwin_arm64.tar.gz ## Update this URL with the correct version 
tar xf tracetest_latest*.tar.gz 

# this launches the installer using the downladed version. Note the `./` at the begining
./tracetest server install
```

As an extra check, make sure that the version displayed at the begginig of the installer matches the latest release, like in this screenshot:

![Screenshot 2023-03-07 at 12 54 19](https://user-images.githubusercontent.com/314548/223475934-8d6fe9e3-2098-46fc-ac50-dd50a016ae5f.png)

Please, let me know if any step is unclear, or you need any help. 

Thank you!

**Comment by correa-juan** [comment]
Hi ! 
I tried it ! 

<img width="808" alt="image" src="https://user-images.githubusercontent.com/127070539/223590562-5d92ebd1-86c9-410d-8164-c699192e8799.png">

but fails when the installation process try to update the config map 

<img width="1583" alt="image" src="https://user-images.githubusercontent.com/127070539/223590756-7750eda8-912f-4d91-802f-46f38e117d6f.png">

The installation was with kubernetes and the demo app. 

thanks !!

**Comment by Juandavi1** [comment]
Same here 🥲

**Comment by schoren** [comment]
@Juandavi1 @correa-juan sorry to see you're still having issues :(. This new thing might be related to a few changes we've been doing in order to release v0.11.0, which we did yesterday. Would you mind upgrading to that version? It's fully released so you can use the regular channels (brew, apt, rpm, etc).

Thanks!

**Comment by Juandavi1** [comment]
it works ! thanks

**Comment by schoren** [comment]
@correa-juan I'll wait for your confirmation to close the issue. If you still have any problems, please let us know

**Comment by kdhamric** [comment]
Three weeks since the last comment - closing the issue.
