### ISSUE TITLE
[installer] Add provision file for K8s installer with demo

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#2119]
**Describe the enhancement you'd like to see**
The k8s installer that includes otelcol and the pokeshop demo should have a Tracetest provision file to make sure the otelcol is hooked up as a data store from the start.

**Comment by kdhamric** [comment]
@adnanrahic Looking at all our issues... do we still need this?

**Comment by adnanrahic** [comment]
This is fixed. Closing.
