### ISSUE TITLE
CLI distribution on Chocolatey is broken

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2142]
**Describe the bug**

Every time that we are releasing a new version of Tracetest, the chocolatey step on our pipeline fails. 
Pipeline example (v0.10.1 release): https://github.com/kubeshop/tracetest/actions/runs/4387280032
Action: https://github.com/kubeshop/tracetest/actions/runs/4387280032/jobs/7682805551

It seems a problem with an ApiKey but we need to check, otherwise, Windows users with chocolatey will not receive CLI versions correctly.

**Comment by danielbdias** [comment]
As described on https://github.com/kubeshop/tracetest/issues/2152, https://github.com/kubeshop/tracetest/issues/2152#issuecomment-1469208840, Tracetest is not featured anymore on [Chocolatey community packages](https://community.chocolatey.org/packages?q=tracetest) and on every version release the Chocolatey step is broken.

We need to review this step to make it work and add documentation about it on https://docs.tracetest.io/getting-started/detailed-installation.

**Comment by jorgeepc** [comment]
Is this done @mathnogueira ?
