### ISSUE TITLE
Review installation documentation on docs.tracetest.io

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2152]
Review https://docs.tracetest.io/getting-started/detailed-installation and update documentation.

Missing points:
- Windows manual installation don't explain in terms of steps to do a manual installation
- Windows chocolatey installation is not explained
- Step 3 don't behave as documented (we don't choose `docker-compose` file anymore)
- Step 4 to 7 are different.

**Comment by adnanrahic** [comment]
We have an issue from before. I never got around to actually doing it. 😢
https://github.com/kubeshop/tracetest/issues/1946

**Comment by danielbdias** [comment]
Tackling in on #2164 and keeping the Windows installation for another ticket because we need to review our Chocolatey setup. Right now, Tracetest is not featured anymore on [Chocolatey community packages](https://community.chocolatey.org/packages?q=tracetest).
