### ISSUE TITLE
Add test snippets user can use

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2174]
We need  to add key assertions that provide value out-of-the-box.
Possible scenario:
Multiple of the examples Postman has would apply:
Response status code is 200
Response body contains string
Response body JSON value check
Response time is less than 200ms
but there are additional ones we could show:
all database spans return in less than 100ms
all http spans return status code of 200
all gRPC spans return status code of 0

**Comment by xoscar** [comment]
This is still future work, right? if there is anything we can do to speed this up let us know 😄

**Comment by olha23** [comment]
@xoscar @jorgeepc need you feedback on this https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2163%3A33256&t=P9kNAyXKV3bbliy7-1

**Comment by kdhamric** [comment]
Copying @xoscar questions from Figma here so we can discuss them:

Should the examples match the spans that exist in the trace? In the first iteration, lets just keep it simple and have a defined list and have all of them show.
Should we breakdown the examples by types? db/http/faas, etc? I don't think we need to
Should we have a list of examples by type documented somewhere? Perhaps, but I don't think we need to include that in this scope.

**Comment by xoscar** [comment]
@kdhamric
