### ISSUE TITLE
[docs] Write "Configuring tracetest with the CLI" (resources) page

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2180]
By adding the new resources commands we are enabling users to have control over the Tracetest server using resources, we need to a documentation to explain how a user can achieve this using the CLI.

**Comment by xoscar** [comment]
@adnanrahic & @kdhamric are you working on this? or do we even need it?

**Comment by kdhamric** [comment]
These pages cover this:
https://docs.tracetest.io/configuration/server
https://docs.tracetest.io/configuration/provisioning

Closing.
