### ISSUE TITLE
[docs] Write " Configuring tracetest with the env variables" Page

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2181]
As part of the changes for the config epic, we introduced a way for users to provision and configure Tracetest using environment variables.

Therefore, we need to add documentation that users can follow to take advantage of this new way of interacting with Tracetest.

Available env vars with example values:

```sh
TRACETEST_POSTGRES_DBNAME=tracetest
TRACETEST_POSTGRES_HOST=postgres
TRACETEST_POSTGRES_USER=postgres
TRACETEST_POSTGRES_PASSWORD=postgres
TRACETEST_POSTGRES_PORT-=5432
TRACETEST_POSTGRES_PARAMS="sslmode=disable"
TRACETEST_SERVER_HTTPPORT=11633
TRACETEST_SERVER_PATHPREFIX="/"

# this is a list of space-separated strings, so here a, b, and c are each an enabled experimental feature
TRACETEST_EXPERIMENTALFEATURES="a b c"

# these 2 are mainly used for internal testing
TRACETEST_INTERNALTELEMETRY_ENABLED=true
TRACETEST_INTERNALTELEMETRY_OTELCOLLECTORENDPOINT=otel-collector.tracetest
```

**Comment by adnanrahic** [comment]
@xoscar this page covers 80% of what is mentioned in this issue.
https://docs.tracetest.io/configuration/provisioning

WDYT, should we expand on it with a hands-on example? I think that would be good.

**Comment by kdhamric** [comment]
Added the server configuration variables in https://github.com/kubeshop/tracetest/pull/2338

I did not add:
TRACETEST_EXPERIMENTALFEATURES
TRACETEST_INTERNALTELEMETRY_ENABLED
TRACETEST_INTERNALTELEMETRY_OTELCOLLECTORENDPOINT

as I do not think end users need those.

**Comment by xoscar** [comment]
Can we close this?
