### ISSUE TITLE
[Error Handling] Backend - Event Log System

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2254]
## NOTE: This ticket is partially blocked until the following tasks are completed:
- [x]  https://github.com/kubeshop/tracetest/issues/2246
- [x] https://github.com/kubeshop/tracetest/issues/2247

This ticket is part of the epic https://github.com/kubeshop/tracetest/issues/2040 to improve the UX/UI when running a test

### Acceptance Criteria:

**AC1**
As a client triggering a new test run
I should be able to subscribe for live events from the server side using a WebSocket
And get live information about what is happening with the run

**AC2**
As a client that triggered a run
And I need to display the full list of events up until that point
I should be able to fetch the list from an endpoint to get the event history

**AC3**
As a developer working on adding event logs to the test run process
I should be able to use a wrapper subscription which will be listening to events happening at the test run level
And push those events to both the WebSocket and store them in the database

**AC4**
As a developer working on adding event logs to the test run process
I should be able to add extra information depending on the event (polling, data store connection)

**AC5**
As a developer working on adding event logs to the test run process
The event system should be extendable to add new event types depending on the requirements and updates

To find more information about the technical design for this task check out the [following comment](https://github.com/kubeshop/tracetest/issues/2040#issuecomment-1482987408)

**Comment by danielbdias** [comment]
Team, I will brainstorm here some backend tasks that we can do and later open one issue for each one:

- [ ] Build/re-use Websocket subscriber for Test events
    - I'm unsure if we can reuse our current structure just for that or consider a segregated structure for this type of notification.
- [ ] Implement Event database persistence migrations
    - At first glance, we can implement it by having the [entire event structure](https://github.com/kubeshop/tracetest/issues/2040#issuecomment-1482987408) in one table `events`, that will have each event attribute (type, stage, description, created_at, test_id, run_id), plus one JSON attribute for each auxiliary structure (dataStoreConnection, polling, outputs)
- [ ] Implement `GetTestRunEvents` endpoint logic, introduced on #2255, that will read the `events` table
- Implement an Event publisher module that will do the following operations: 
    - [ ] Persist the event on the `events` table 
    - [ ] Send the event JSON to subscribed clients
    - This module could be created as a module on `./server` directly or on `./server/executor`

**Comment by mathnogueira** [comment]
> Build/re-use Websocket subscriber for Test events

I don't think this is the right approach TBH. One of the requirements for the epic is that Tracetest generates telemetry based on those events. This means that every time an event is created, it should have a span with that information too. The implication for that is that we get a new `context.Context` and have to use it in order to link the spans to their correct parents.

I don't think it's possible to have the subscriber manage those contexts in an easy way. I rather have a facade instead. This is how I imagine it (simplified version)

```go
// facade.go
// ...
func (f facade) Emit(ctx context.Context, event Event) (context.Context, error) {
  span, ctx := f.tracer.Start(ctx, event.Name)
  // populate span with event data
  f.db.InsertEvent(ctx, event)
  f.subscriber.Publish(ctx, event)
}
```

**Comment by mathnogueira** [comment]
Should we add events to the otlp ingest endpoint? It's possible to get the testID and runID based on the traceID

**Comment by danielbdias** [comment]
At first glance, we could add it to have visibility in debugging, to understand what happened during a test run.
