### ISSUE TITLE
[CLI Improvements] Normalise verbs outputs

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2299]
CLI outputs are currently not similar between different verbs. We need to make sure all resources in the CLI follow the detailed definition in the [epic](https://github.com/kubeshop/tracetest/issues/2182).

Commands to update:
- list
- get
-  delete
- apply

**Comment by xoscar** [comment]
Let's have a global way of printing outputs to the terminal before we start going one by one fixing the resources/verbs.

I believe we should support
- JSON
- YAML
- Pretty (table version)

Right?
