### ISSUE TITLE
[CLI Improvements] ensure all commands provide feedback on success

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2300]
Not all commands generate output, and it is not always obvious what the result of an operation was. We need to review all commands and make sure that they all generate a success message when things worked correctly.

**Comment by xoscar** [comment]
Let's be more specific on this, we can call out what resources and verbs need this.
Also, I think this ticket might depend on having these done, isn't it?

https://github.com/kubeshop/tracetest/issues/2297 
https://github.com/kubeshop/tracetest/issues/2299

**Comment by kdhamric** [comment]
@schoren @xoscar Wanted to check the state of this issue. Is this work we still need? If so, will we do it after we finish 'Test' resources? If we are not doing it in the next 2-3 weeks I would like to pull it off the board until we near time to work on it.

**Comment by xoscar** [comment]
I think this is important, but can be pulled into the project when its needed

**Comment by schoren** [comment]
IMO, this issue has been fixed by all the work of using the new resourcemanager client and normalizing the verbs. 
@xoscar @kdhamric what do you think? can we close it?
