### ISSUE TITLE
[CLI Improvements] Add `run` verb

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2302]
the `test run` command will be deprecated in favor of the new `[verb] [resource]` format. This format supports the general CRUD operations, but running a test doesn't fall on that category.

We need to add the `run` verb, which should only support the following resources:
- test
- transactions

The new `run [resource]` command will invert the waiting flat. The current implementations default behaviour is to **not** wait for the test to run, and it offers the `--wait-for-result` flag if the user wants to wait to see the actual results. The new implementation will inverse that logic, so the default behavior will be to wait for the results, and allow users to skip the wait with a `--skip-results-wait | -W`.

**Comment by schoren** [comment]
I added the `all` resource support here to allow users to run a mix of tests and transactions in a single command. I can see myself using it, but not sure if this is the right path.

@kdhamric @olha23 Would love your feedback here

**Comment by schoren** [comment]
as by talks with @kdhamric we won't support the `all` resources for the run resource. Update the issue description accordingly

**Comment by olha23** [comment]
@schoren do we need to include the deprecation message now in CLI for user who use  test run command? 
i mean something like this:
`⚠️  Warning: The "tracetest run test" command will be deprecated soon. Please use the new CRUD-style format: "tracetest run [verb] [resource]". 
`

**Comment by schoren** [comment]
@olha23 there's a separated issue to deprecate commands: https://github.com/kubeshop/tracetest/issues/2301. Is that what you mean? We should add the message in that issue.
