### ISSUE TITLE
Need input validation on url field of http request trigger

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2374]
AC1: As a user adding or editing a test
I should not be allowed to enter a url that is not valid
i.e. it should have the protocol and a validly structured url
or we should give an input verification error.

AC2:
We should show an example of the url in the URL field in the grey text.
ie change: 
Enter request url 
to 
Enter request url, such as http://yourhost/path

AC3:
In the red 'help text' on validation failure, show 'Please enter a request url, such as http://yourhost/path'

**Comment by xoscar** [comment]
Issue was fixed for urls like:

```
www.google.com
amazon.com.mx
github.com
demo-pokemon-api.demo.svc.cluster.local/pokemon/import
```

But for others when specifying the port like:

```
demo-api:8081/pokemon
```

it doesn't work as the golang library takes `demo-api` as the Scheme...
![Image](https://user-images.githubusercontent.com/11051031/233164316-6eccc79c-9478-4e9d-8ab0-58965af20a3c.png)
