### ISSUE TITLE
Update Snippets Menu

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2376]
Update the snippets menu for empty state and dropdown menu behavior

Acceptance Criteria:

**AC1**
As a user looking at a test run with no test specs
As part of the empty state section
I should see the list of predefined snippets

**AC2**
As a user looking at a test run with no test specs
The snippets dropdown should NOT be open by default

**AC3**
As a user opening the snippets dropdown
I should not see the add empty test spec option

**Comment by xoscar** [comment]
@kdhamric could you chime in here? right now the behavior for automatically opening the snippets is to keep it open until the test run has at least one test spec. So every time the user returns to the test mode they will see the snippets.

The second thing is the empty spect at the bottom, I think we can remove it.

Last is the messaging and info for the test specs empty state, I think we could have the snippets there too, that way we can avoid opening the dropdown menu every time.

What do you think? @olha23 @jorgeepc

**Comment by olha23** [comment]
the behavior for automatically opening the snippets looks also bad in this case also: 
<img width="1408" alt="Screenshot 2023-04-17 at 2 24 04 PM" src="https://user-images.githubusercontent.com/5725840/232483473-6424091f-f02d-45ca-8e57-f3e14a484dc0.png">

**Comment by olha23** [comment]
Anyway this automatically open snippet realisation from my perspective look like more a bug not a feature 🫠

**Comment by olha23** [comment]
@xoscar @kdhamric @jorgeepc my updated suggestion about snippet here - https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2163%3A33256&t=qPzPudVDw86hRI4c-1
please check
