### ISSUE TITLE
[Network Improvements] Ease networking knowledge needed to use Tracetest

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2383]
Currently, some users struggle to use Tracetest due to networking issues. We want to ease this pain.

AC1: 
As a new user to OTel, 
I want to be able to use a minimal configuration in my app instrumentation 
and have the trace data easily appear in Tracetest when not utilizing a direct trace data store.

AC2: 
As a developer, when coding locally on my desktop, I want Tracetest to just work where possible, 
and guide me in the areas where some education is needed.

Proposed Solution:

1) Move to using the default gRPC port Tracetest listens for incoming spans via gRPC to 4317 to match the default (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md). This will allow a minimal configuration. 

2) Allow http as a method to send incoming spans, and listen for this on 4318 (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp)

3) On the Docker setup, expose 4317 and 4318 and route them to either Tracetest or the OTel Collector.

**Comment by mathnogueira** [comment]
We would have to allow users to override the port that Tracetest listens to because it might conflict with an Otel collector running locally. This would prevent users from starting Tracetest.

This config should probably live in the config file and we also should allow users to define env variables to set them (I suspect most people would use env variables for that)

**Comment by kdhamric** [comment]
Will we leverage the 'config resource' for this?

**Comment by xoscar** [comment]
DRAFT: Tasks required to complete this story:

1. Update the otlp server to listen to HTTP incoming requests
2. Update the configuration resource manager to accept values for OTLP ports
3. Add test run events for received data incoming from the collector endpoints
4. Edit examples and recipes to use the new config


@mathnogueira what do you think?

**Comment by kdhamric** [comment]
We may want to consider #1292 as part of this work.

**Comment by xoscar** [comment]
@kdhamric that ticket doesn't have much info, could you add something so we can check if it would match to be done as part of this?

**Comment by xoscar** [comment]
Currently considering this:


As we are making the OTLP endpoints to be more prominent by the [network ease changes](https://github.com/kubeshop/tracetest/issues/2383).
Should we also support a specific DataStore type to point directly to Tracetest? currently, we have OpenTelemetry and the examples are using the otel collector. But we really don't need to collector so we can have another "send open telemetry data directly to Tracetest" data store

**Comment by xoscar** [comment]
If we decide to work on the above ☝ that should be part of a separate ticket
