### ISSUE TITLE
Add helper code on ResourceManager-based repositories to handle list pagination and avoid query injection

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2388]
On our repo list methods, we have the same pagination code made, like [here](https://github.com/kubeshop/tracetest/blob/main/server/config/demoresource/demo_resource.go#L238):

```golang
listQuery := baseSelect

if sortDirection == "" {
	sortDirection = "ASC"
}

if query != "" {
	listQuery = fmt.Sprintf("%s WHERE %s", listQuery, query)
}

if sortBy != "" {
	listQuery = fmt.Sprintf("%s ORDER BY %s %s", listQuery, sortBy, sortDirection)
}

if take > 0 {
	listQuery = fmt.Sprintf("%s LIMIT %d", listQuery, take)
}

if skip > 0 {
	listQuery = fmt.Sprintf("%s OFFSET %d", listQuery, skip)
}
```

We should:

1. Move this code to an auxiliary method and allow other resources to use them.
2. Standardize how we work with the `query` parameter and insert them safely on the query string.

**Comment by kdhamric** [comment]
@danielbdias Do we still need this issue? Please close if not. If we do need it, if we are not going to work on it in the next couple weeks lets take it off the project board unless there is a good reason for it to be here.
