### ISSUE TITLE
Enable/disable SSL certificate verification in Test trigger

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#2439]
**Describe the enhancement you'd like to see**
We should include an option at the `Test Trigger` level to enable/disable the SSL certificate verification. This would allow users to interact with URLs(endpoints) that are using self signed certificates.

**Additional context**
Here is an screenshot of how postman handles this configuration:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3879892/234617808-e20cb229-d431-4b8b-999f-a324b65108b3.png">

**Comment by olha23** [comment]
@jorgeepc can you please check the mockups https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2580%3A34402&t=VKha1tRkWcuaxPKl-1
