### ISSUE TITLE
Test specs screen "blink" when pressing "Run Test" button

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2448]
When clicking on "Run Test" while seeing the "Test spec" screen, we have the test screen set as empty during the execution of the test.

![Kapture 2023-04-26 at 19 42 15](https://user-images.githubusercontent.com/12397879/234718501-78d3209e-8960-41ff-ae60-e50f2235ec62.gif)

**Comment by kdhamric** [comment]
I believe this is improved now that we do not open the test snippets automatically any more. Closing the issue - it is becomes a problem in the future we can readdress.
