### ISSUE TITLE
Highlight selected span

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#2495]
**Describe the enhancement you'd like to see**
In our current graph view, we highlight the selected span by using a blue line around the span. However, it is not easy no identify it specially when you are in the "Test Spec" detail mode. We want to improve this design to have a clear understanding of which span is selected.

**Additional context**
<img width="1486" alt="Screenshot 2023-05-05 at 13 06 46" src="https://user-images.githubusercontent.com/3879892/236548983-f0b028e8-a5e5-41d6-a03d-74f4afe5f397.png">

**Comment by olha23** [comment]
@jorgeepc i propose use more wider stroke and drop shadow like this:
<img width="696" alt="Screenshot 2023-05-08 at 12 53 33 PM" src="https://user-images.githubusercontent.com/5725840/236806245-d5f22887-3afb-48ee-af62-98e06c4530ee.png">
check the mockups here: https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2588%3A34470&t=WbaRDtQAN8PdWHLL-1
