### ISSUE TITLE
Configure Data Store improvements

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2509]
Now on the OpenTelemetry, New Relic, Lightstep, Datadog  and Honeycomb tabs there are not settings you are adjusting, so it is not necessarily clear you need to save to enable / select it.

Need to add a slider "Enable OpenTelemetry as selected trace data source" on the Configure Data Store setting page.
It's to make it clear to the user that they need to enable and save the data store selection. By default, the slider could be set to "off" and the user would need to slide it to "on" and click the "Save" button to enable and save the OpenTelemetry Collector as their selected data source.

Check the mockups here: https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2609%3A34492&t=KJ9TFs1UtEEDxYyn-1 

need to make this for OpenTelemetry, New Relic, Lightstep, Datadog  and Honeycomb tabs

**Comment by jorgeepc** [comment]
@olha23 I added a comment in figma, please take a look

**Comment by olha23** [comment]
updated

**Comment by kdhamric** [comment]
Yes - lets match the figma design. If one of the 'otel collector based' methods is choosen (Lightstep, New Relic, Datadog, Honeywell, OpenTelemetry) then the toggle should be set to 'On' when you click on that configuration. 

To enable the configuration, you have to slide the toggle to 'on' and click the save button.

**Comment by kdhamric** [comment]
@xoscar I would say the bottom one
