### ISSUE TITLE
[docs] Update list of Data Stores to be complete

### ISSUE THREAD

**Issue by mjingle** [kubeshop/tracetest#2511]
**Describe the bug**
In the Tracetest docs, Honeycomb is missing from the list in https://docs.tracetest.io/configuration/overview#supported-trace-data-stores.

**To Reproduce**
1. Go to https://docs.tracetest.io/configuration/overview#supported-trace-data-stores
2. Expand the left nav menu to view the options under "Connecting to Data Stores"
3. Notice that Honeycomb is listed at the bottom of the available options but not listed in https://docs.tracetest.io/configuration/overview#supported-trace-data-stores

**Expected behavior**
https://docs.tracetest.io/configuration/overview#supported-trace-data-stores should have Honeycomb listed as a hyperlinked bullet point to https://docs.tracetest.io/configuration/connecting-to-data-stores/honeycomb

**Screenshots**
 N/A

**Additional context**

**Comment by adnanrahic** [comment]
Ah! Yes. Let me update that.
