### ISSUE TITLE
Creating test spec from response data page

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2525]
Need to add ability to create test spec from response data page. 
Check the mockups here: https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?node-id=2572%3A34372&t=j4B4pQBCokqAasxK-1

**Comment by akshaya-hub** [comment]
@olha23 i would like to work on this issue

**Comment by olha23** [comment]
@akshaya-hub Hello, sure! I approved your figma access, let me know if you have any questions

**Comment by akshaya-hub** [comment]
@olha23 Sure

**Comment by kdhamric** [comment]
@olha23 We need to add buttons next to status code and duration on the response screen

**Comment by olha23** [comment]
added
