### ISSUE TITLE
Clearly state the otel config file is a sample that you need to update in your otel col config — in-app edits

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#2531]
**Describe the enhancement you'd like to see**
In the in-app settings for OpenTelemetry-based data store integrations:
- Clearly state the otel config file is a sample that you need to update in your otel col config
- Mention ingest endpoint and explain what it is
- Think of a new way to apply the settings without needing to save the setting

In the docs:
- Write docs pages about otel collector and ingest endpoint for all OpenTelemetry-based data store integrations

**Additional context**
N/A

**Comment by adnanrahic** [comment]
Hi @olha23 ! Do you have a moment to work on some designs for this?
I'm happy to help with wording and how to get the point across.

Here are some samples we can work with and improve:

**Mention ingest endpoint and explain what it is**
"Tracetest exposes trace ingestion endpoints on ports `4317` for gRPC and `4318` for HTTP. By toggling the Tracetest ingestion endpoint to 'On', you'll enable ingesting traces into Tracetest. To send traces to Tracetest make sure to use the Tracetest Server's hostname and port. eg. if you are using Docker it would be `tracetest:4317` if you are sending traces over gRPC."

**Clearly state the otel config file is a sample that you need to update in your otel col config**
"The OpenTelemetry Collector configuration below is a sample. Your config file layout should look the same. Make sure to use your own API keys or tokens as explained. Copy the config sample below, paste it into your own OpenTelemetry Collector config and apply it."

**Comment by olha23** [comment]
@adnanrahic do we need to have also text field here with Tracetest Server hostname and port? or just toggle?

**Comment by adnanrahic** [comment]
If there is a way to expose the hostname of the Tracetest server, then we can also add it. Not sure if it is possible.

Otherwise, just toggle is fine IMHO.

**Comment by olha23** [comment]
@adnanrahic can you check this and say what do you think? https://www.figma.com/file/LBN4SKVPq3ykegrPKbHT2Y/0.8-0.9-Release-Tracetest?type=design&node-id=2658%3A34615&t=sdZbxla4fGRfCkUB-1

**Comment by adnanrahic** [comment]
I think it looks very nice. We can iterate further on the wording. It can be improved. Let's wait for more feedback from the team.

**Comment by xoscar** [comment]
@olha23 my opinion

- I like the idea of having more information about the otlp endpoints and the change to the save and set text
- The otlp endpoints are always enabled, we do not have a switch for that in the application, I think it should stay that way, so that switch doesn't make too much sense.

**Comment by kdhamric** [comment]
I am torn on the 'Enable' switch. I am afraid this screen is confusing without a value / altering something (ie 'Saving' usually means you altered something, and this screen just seems to present material). We could:
- disable the 'Save and set as Datastore' button unless the 'Enable Tracetest Ingestion Point' is 'enabled'... this would make the only allowed state for a selected datastore as 'enabled'
or
- show an error when clicking 'Save and set as Datastore' if the 'Enable' is not enabled and not allow the action.

Or... we can listen to @xoscar on this one - I am not certain of the best choice and do not feel strongly about it (just afraid it is confusing)

**Comment by adnanrahic** [comment]
I agree some of this does not make sense "technically" as the endpoint is always enabled.

However, I'm thinking about this from the POV of a user. Here's a flow example:

1. In the data store settings, I want to select a data store.
2. I have no pre-existing knowledge about the OTLP endpoint.
3. I have used Jaeger in the provisioning file when starting Tracetest.
4. I want to switch to using OpenTelemetry as the data store in the in-app settings.
5. I select the OpenTelemetry data store page, and see that it works by using a trace ingestion endpoint on port `4317/4318`.
6. I read on the page that I need to enable the data store in order to use the ingestion endpoint in my OpenTelemetry config file. (This step requires us to give the user some feedback that an ENABLE or SAVE action needs to happen)

I think that we're okay with not having a toggle, if we write very clear copy and fix the `Save and Set as Data Store` button to the bottom so that no scrolling is needed.

WDYT?
