### ISSUE TITLE
[CLI] output manifests instead of applying them directly

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#2559]
**Is your feature request related to a problem? Please describe.**
From what I saw, `tracetest server install` does not have the option to output manifests instead of applying them directly, hence I cannot store them in Git and apply them with ArgoCD or Flux. Alternatively, it would be OK to use a Helm chart if there is one. https://docs.tracetest.io/deployment/kubernetes does not mention any alternatives to `tracetest server install`.
From [Discord](https://discord.com/channels/884464549347074049/963470167327772703/1109093969457074236).

**Describe the solution you'd like**
Have a dry run command option. Or something better?

**Describe alternatives you've considered**
Use Helm charts from GitHub, here: https://github.com/kubeshop/helm-charts/tree/develop/charts/tracetest
```
helm repo add kubeshop https://kubeshop.github.io/helm-charts
helm repo update
helm install tracetest kubeshop/tracetest
```

**Additional context**
[Question opened by Viktor Farcic in Discord, here](https://discord.com/channels/884464549347074049/963470167327772703/1109093969457074236).

**Comment by adnanrahic** [comment]
I think we have 2 options:

1. Add detailed docs about the Helm charts here: https://docs.tracetest.io/deployment/kubernetes — they should explain how to use Helm to generate manifest files, do dry runs, and deploy the chart to a running cluster.
2. Add a feature in the CLI to generate files into a directory instead of applying them to a cluster right away. — Then add these instructions to https://docs.tracetest.io/deployment/kubernetes

What do you think?

**Comment by danielbdias** [comment]
I believe that we can follow the first option. 

When a user wants to use the helm chart directly, it is because they have a specific need on their infra (like for instance, configuring [Flux](https://fluxcd.io/) to read helm charts and auto-update a deployment), and it usually is difficult to map on our CLI. 

Does it make sense? What do you think, @mathnogueira and @schoren?

**Comment by adnanrahic** [comment]
I think we should also re-write this page https://docs.tracetest.io/getting-started/detailed-installation to include both using the CLI and the Helm charts. This page can be shorter and more concise than the full explanation on this page https://docs.tracetest.io/deployment/kubernetes.

WDYT @danielbdias ?

**Comment by adnanrahic** [comment]
Updates on https://docs.tracetest.io/getting-started/detailed-installation are pending https://github.com/kubeshop/tracetest/pull/2567

**Comment by adnanrahic** [comment]
To summarize, we've updated two pages with more detailed instructions and added Helm instructions.

- https://docs.tracetest.io/getting-started/detailed-installation
- https://docs.tracetest.io/deployment/kubernetes
