### ISSUE TITLE
attr with dashes are not allowed

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2564]
I have an assertion with an attribute with dashes:
![image](https://github.com/kubeshop/tracetest/assets/4865355/1bd84b18-ea2c-4176-b504-012dac191def)
Is this a bug?
Or is the syntax wrong?

**Comment by adnanrahic** [comment]
Hi @BartNetJS ! 
I believe the expected syntax does not use dashes. As seen in the [docs, here](https://docs.tracetest.io/concepts/expressions#reference-variables), attributes are expected to use underscores.
I'll loop in the engineering team once they wake up to provide a more detailed answer. 😄

**Comment by BartNetJS** [comment]
I hope the dashed will be allowed.
in my case the traces are from [dapr ](https://dapr.io/)and I can't change that ;-)

**Comment by kdhamric** [comment]
It looks like we need to allow them based on what I am reading at https://opentelemetry.io/docs/specs/otel/common/attribute-naming/. Specifically:

> Semantic conventions MUST limit names to printable Basic Latin characters (more precisely to [U+0021 .. U+007E](https://en.wikipedia.org/wiki/Basic_Latin_%28Unicode_block%29#Table_of_characters) subset of Unicode code points). It is recommended to further limit names to the following Unicode code points: Latin alphabet, Numeric, Underscore, Dot (as namespace delimiter).

Based on this, while it sounds like Dapr is not going with the recommendation, it is within the spec. Will ask the devs to chime in.

**Comment by mathnogueira** [comment]
Hey @BartNetJS. Supporting a dash, in that case, is not simple, but I'll try to make it possible. I'll keep you updated on the progress.

**Comment by kdhamric** [comment]
@BartNetJS Just for some background on why it is not simple - when we are parsing, the 'minus sign, ie -, is also an operator. The due meaning makes it harder. @mathnogueira has an idea on how to get it to work properly and will get back to you.

**Comment by mathnogueira** [comment]
Good news is that the simplest solution worked fine. I just opened a PR to include it in our next release.

**Comment by mathnogueira** [comment]
@BartNetJS version 0.11.9 was just released and it allows dashes in attributes now. Thanks for opening this issue!
