### ISSUE TITLE
`tracetest version` always consider that the user has a server before running it

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2592]
When you run the command `tracetest version` and don't have a version installed locally, you receive the following message:

<img width="947" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/c753a737-0e95-4bd8-9247-2123b05b33cd">

We should handle this Server message and show something like `Server: not detected`

**Comment by xoscar** [comment]
Will be fixed as part of https://github.com/kubeshop/tracetest/issues/2298
