### ISSUE TITLE
the page is not working 

### ISSUE THREAD

**Issue by akshaya-hub** [kubeshop/tracetest#2596]
The kubernetes deployment page is not working 
link:  https://docs.tracetest.io/deployment/overview/kubernetes

**Comment by xoscar** [comment]
Hey @akshaya-hub I saw you closed this one too, is there something that changed when looking at the docs? if you have any questions or concerns I'll be happy to help 😄

**Comment by adnanrahic** [comment]
Might be a redirect issue. This PR fixes it: #2597

**Comment by akshaya-hub** [comment]
@xoscar @adnanrahic  yeh it was with the links actually but somehow after redirecting it worked good

**Comment by akshaya-hub** [comment]
@xoscar @adnanrahic i think  the page is still not working
link:https://docs.tracetest.io/deployment/overview/docker
