### ISSUE TITLE
[CLI Improvements] Add Upgrade Documentation Page

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2612]
As we are adding a version check between the server and the CLI, we have to create a documentation page where users can find the upgrading guides.

Page should be https://docs.tracetest.io/configuration/upgrade

**Comment by xoscar** [comment]
@adnanrahic not to put pressure on you but the code feature is going to be released as part of 0.11.10 tomorrow 😬

**Comment by adnanrahic** [comment]
#2640
