### ISSUE TITLE
Cannot add specs in WebUI when  a test failed in the linter

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2634]
**Describe the bug**

I ran a test with the linter enabled, and due to the score, it failed. When I try to go to the test specs page the Add Spec button is disabled.

<img width="1732" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/ec5cbe57-186d-4cf9-9ddd-2c6b00797334">

**Comment by jorgeepc** [comment]
@xoscar is this fixed by https://github.com/kubeshop/tracetest/pull/2697 ?
