### ISSUE TITLE
Tests specs are not shown if a test fails in linter

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#2636]
**Describe the bug**

Given a previous test where I added the following specs:

<img width="1741" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/4358f16d-9219-4177-9269-fe51e835d8c0">

When I enable the linter with a high score and try to rerun it, the linter fails (due the score) and the specs are missing:

<img width="1733" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/cc19ea68-012b-4b3a-939a-b90ca49207e1">

**Comment by jorgeepc** [comment]
@xoscar is this fixed by https://github.com/kubeshop/tracetest/pull/2697 ?

**Comment by danielbdias** [comment]
Indeed! Closing it.
