### ISSUE TITLE
[Analyzer Results] UI improvements

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2647]
6 UI improvements for analyzer
(In mockups changes are indicated by red arrows)

Link to mockups https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/hackathon?type=design&node-id=119%3A12394&t=iBIesn7ggxj0WJEP-1

**Comment by kdhamric** [comment]
Love it. Left one comment about wording.
