### ISSUE TITLE
[Analyzer Results] Smooth Scrolling

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2649]
We need make it easier for users to navigate the Analyzer. When they click on the circle chart at the top, we can automatically open the corresponding 'detail' section below and smoothly scroll to it. This way, users can quickly dive into the details they're interested in without any hassle.

See mockups: https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/hackathon?type=design&node-id=119%3A12763&t=iBIesn7ggxj0WJEP-1

**Comment by kdhamric** [comment]
Looks great @olha23 - thanks!

**Comment by xoscar** [comment]
@olha23 as we have updated the analyzer results to not show the plugins anymore, should we close this one as the functionality doesn't exist now?

**Comment by olha23** [comment]
yes
