### ISSUE TITLE
[Analyzer Results] Showing the high level results

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2650]
Ken had idea to show the score results when looking at the list of tests and the list or test runs.
Here is mockups https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/hackathon?type=design&node-id=119%3A13641&t=iBIesn7ggxj0WJEP-1 

About behaviour: 
-clicking on score specifically should take you to the Trace tab
-clicking on the test pass/fail should take you to the Test tab

**Comment by kdhamric** [comment]
Looks great @olha23
