### ISSUE TITLE
[Analyzer] UX - Error message improvement

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2677]
Please check the video https://www.loom.com/share/b3efe5ef26044db59c78cd4f0f72191b

See example:
### Instead of this text:

```
**Required Attributes by Span Type:**
Attribute "http.target" is missing from span of type "http"
Attribute "net.host.name" is missing from span of type "http"

**Attribute Naming:**
Attribute "name" doesnt follow naming convention
Attribute "tracetest.span.startTime" doesnt follow naming convention
Attribute "tracetest.span.endTime" doesnt follow naming convention
Attribute "parent_id" doesnt follow naming convention

**Enforce HTTPS Protocol:**
Insecure http schema found for attribute: http.scheme. Value: http
```

### i propose use this template:

```
**Missing Attributes for Span Type:**
The span of type "http" is missing the required attributes:
- "http.target"
- "net.host.name"

**Attribute Naming:**
The following attributes do not adhere to the naming convention:
- "name"
- "tracetest.span.startTime"
- "tracetest.span.endTime"
- "parent_id"

**Enforce HTTPS Protocol:**
The attribute "http.scheme" has an insecure value of "http". 
Please ensure that the value is set to "https" for security purposes.

Please review and update the necessary attributes and naming conventions to ensure proper functionality.
```

Overall, the improvements aim to provide clearer explanations and actionable instructions to the user, making the error message more user-friendly and facilitating better understanding and resolution of the encountered issues.

**Comment by olha23** [comment]
@xoscar @jorgeepc @kdhamric need you feedback on this suggestion

**Comment by olha23** [comment]
one more: one more: i don’t understand the error like "Attribute "name" does not follow naming convention" and so on. what is wrong with this 'name"?  and where user need to find this ''naming convention"?

**Comment by olha23** [comment]
and one one more comment: 
we say that something wrong with your Span name or Attribute name but we have no way to fix/edit them...then what is the meaning of these messages? or maybe i don’t understand how this must work

**Comment by kdhamric** [comment]
On: "we say that something wrong with your Span name or Attribute name but we have no way to fix/edit them...then what is the sense of these messages? or maybe i don’t understand how this must work" - we will want to start tying the errors back to the definitions of what is 'correct'. For example, for attribute naming issues, we should have a hyper link that goes to https://opentelemetry.io/docs/specs/otel/common/attribute-naming/#:~:text=Attribute%20names%20that%20start%20with,t%20have%20a%20corresponding%20concept. This way the tool will start showing people the correct method.

Another example, if an attribute was require on a http span and it was missing, we might provide a link to https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#common-attributes

We need to plan these things out via an epic, so for now I would not include the links and just focus on your changes to group like errors (which looks good)
