### ISSUE TITLE
[Analyzer Results] Do all steps of a test rather than failing on an Analyzer Score not being reached

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2682]
Currently, the new analyzer, if enabled, checks to see if the score is below the threshold value and stops the test processing, leaving the test in a state of ANALYZING_ERROR. Rather than doing this, processing the test should continue, progressing through to the FINISHED state.

AC1: When running a test, the processing should not stop
        based on the score for the analyzer being below a certain threshold

AC2: If the Analyzer is enabled, 
         the Trace screen should indicate if the overall score, ie the Trace Analyzer Result, 
         was below the threshold for a successful run. It should clearly indicate what the overall 
         Trace Analyzer Score was, and what the minimal acceptable score was at the time this test run was run,
         and whether this was a passing test score or not. Suggested wording (although a graphic may work better):
         Overall Trace Analyzer Score: 61  Minimum acceptable score: 70. This trace analyzer result is: Failed
         
We will need other followup issues to make the CLI handle failure to meet the score, but this first change is needed so test specs run properly regardless of the passing or failing of the test score.

**Comment by xoscar** [comment]
@olha23 do you mind taking a look at this, we would need to have a place in the `trace` tab to show that the analyzer failed because of the minimum score rule

**Comment by jorgeepc** [comment]
Looks good. One question @kdhamric, we are going to fail the test if the score for the analyzer is below the threshold, right? I mean, we are going to execute the specs but we want to mark the test as failed. Is that correct?

**Comment by kdhamric** [comment]
In the UI, we want to start indicating score information and whether the test met the minimum score. @olha23 has mocks in #2650 that show in the results view the overall score, and the image is in red or green to indicate whether the trace analyzer passed the minimum score.

We do, however, need to mark the entire test run as passed or failed, which is indicated by the green or red circle at the beginning of a test run, based on some logic. Were there any assertions that failed? Is the trace analyzer on, and if so, was the overall score below the minimum? We may have a setting to say 'score the traces, show pass or fail for it, but do not fail the overall test (ie just show scores and whether we passed or not).

Rather than having this logic in the front end and in the CLI, we may want to centralize it and deliver it as part of the test run info. Creating an issue to describe the problem.

**Comment by olha23** [comment]
@kdhamric i created the mockup for this, please check here. I prefer V2 
https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/hackathon?type=design&node-id=138%3A13983&t=XwutnpreNjZV8kzL-1
