### ISSUE TITLE
tracetest server install fails

### ISSUE THREAD

**Issue by dfranklin-at-bg** [kubeshop/tracetest#2723]
**Describe the bug**
On a Linux system, I am trying to install the tracetest server. I have followed the instructions on https://docs.tracetest.io/ci-cd-automation/testkube-pipeline/ but when running "tracetest server install" I get the following:

  ERROR   cannot get kubectl contexts: record on line 2: wrong number of fields

**To Reproduce**
1. Go to https://docs.tracetest.io/ci-cd-automation/testkube-pipeline/
2. Already have kubectl, helm, and an EKS cluster running
3. Select the context in your terminal window by using the kubie tool
4. Follow the instructions from the URL in step 1 for a Linux installation

**Expected behavior**
You can run the tracetest server.

**Screenshots**
[eks/ft2-mthn-sqa2|default] (base) david.franklin@LT42V3BC3:~/training$ tracetest server install

[ graphic removed ]

Version: v0.11.12

Hi! Welcome to the TraceTest server installer. I'll help you set up your TraceTest server by asking you a few questions
and configuring your system with all the requirements, so you can start TraceTesting right away!

To get more info about TraceTest, you can check our docs at https://kubeshop.github.io/tracetest/

If you have any issues, please let us know by creating an issue (https://github.com/kubeshop/tracetest/issues/new/choose)
or reach us on Discord https://discord.gg/6zupCZFQbe

How do you want to run TraceTest?: 
  > Using Kubernetes

-> Let's check if your system has everything we need
✔ kubectl already installed
✔ helm already installed

-> Your system is ready! Now, let's configure TraceTest

Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app? [type to search]: 
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app? [type to search]: 
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app? [type to search]: 
Do you have OpenTelemetry based tracing already set up, or would you like us to install a demo tracing environment and app?: 
  > Just learning tracing! Install Tracetest, OpenTelemetry Collector and the sample app.

  ERROR   cannot get kubectl contexts: record on line 2: wrong number of fields

**Browser (please complete the following information):**
N/A

**Additional context**
Host OS information:
Linux LT42V3BC3 5.4.0-150-generic #167~18.04.1-Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Kubectl version:
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.1-eks-2f008fe", GitCommit:"abfec7d7e55d56346a5259c9379dea9f56ba2926", GitTreeState:"clean", BuildDate:"2023-04-14T20:40:28Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mathnogueira** [comment]
Hey @dfranklin-at-bg, can you share the output of `kubectl config get-contexts --no-headers`?

**Comment by dfranklin-at-bg** [comment]
Here's the output of that command piped to grep to show the cluster I'm using now 
** *     eks/ft2-mthn-sqa2               arn:aws:eks:us-east-1:524470583153:cluster/ft2-mthn-sqa2   arn:aws:eks:us-east-1:524470583153:cluster/ft2-mthn-sqa2**

**Comment by mathnogueira** [comment]
Ok, managed to reproduce the bug locally with your input. I'll work on a fix for that!

**Comment by dfranklin-at-bg** [comment]
Yes perhaps I should have been more clear - there are several contexts available for me to choose from but I use kubie to set the active one in any given terminal session. But it sounds like you may have a line of sight on a solution. :-)

**Comment by mathnogueira** [comment]
Merged #2725, and we are going to release it today. As soon as it gets out, I'll let you know

**Comment by mathnogueira** [comment]
@dfranklin-at-bg version 0.11.13 is live. Try upgrading your CLI and try install Tracetest again
