### ISSUE TITLE
"Contact us" issue

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2744]
We want to increase the number of people that contact us for help.  We watch Posthog sessions, see people have problems, but they do not reach out. The idea is when user try click "test connection" more then 3 times and see error we show something like this message: 
https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=221%3A15409&t=OIZh5Q4C9LqRDejl-1

**Comment by olha23** [comment]
updated mockups https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=324%3A14038&t=HxcAdZTNLFJbNyOD-1

**Comment by xoscar** [comment]
@olha23 I have some questions:
1. Should the plushy be visible all the time or just after the three failures from the test connection action?
2. If visible all the time, should it be opened by default after the three fails?
3. Is this only for the data store configuration page or somewhere as well?

**Comment by olha23** [comment]
@xoscar 
1. i think we can start to show it after the three failures
2. -
3. Let’s start to show it for the data store and will check how it goes
