### ISSUE TITLE
[Automate Tab] Include DeepLink Technique

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2767]
The frontend now supports a deep link to trigger tests automatically, it was part of issue's #2745 work.

Now, we have to showcase that feature as part of the automated tab in the test run.

#### Acceptance Criteria

**AC1**
As a user looking at the automate tab
I should be able to switch from CLI to Deep Link
And see the deep link usage to run my test

**AC2**
As a user looking at the automate tab and the Deep Link technique
I should be able to add `variables` to the execution
variables are a set of `key` - `value` pair similar to the environment entries
And the deep link should update accordingly

**AC3**
As a user looking at the automate tab and the Deep Link technique
I should be able to use the current environment I have selected as part of the run
And the deep link should update accordingly

**AC3**
As a user looking at the automate tab and the Deep Link technique
I should be able to copy the link and paste it into my browser

The deep link structure is the following:

`<protocol>://<host><prefix?>/test/<testId>/version/<version>/run?environmentId=<envId>&variables=<variables>`

Where the variables is an array of URL encoded key values. i.e `[{key: 'HOST', value: 'localhost'}]` encoded `%5B%7Bkey%3A%20%27HOST%27%2C%20value%3A%20%27localhost%27%7D%5D`

Example: https://beta.tracetest.io/test/UVmea5X4g/version/3/run?environmentId=dev&variables=%5B%7B"key"%3A"HOST"%2C"value"%3A"google.com"%7D%5D

**Comment by olha23** [comment]
@xoscar please check the mockups here https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=358%3A14209&t=ciXYmunOH3EMEgOt-1
