### ISSUE TITLE
[Automate Tab] Support Test Definition Name Update

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2768]
Based on @adnanrahic's comment:

```
One suggestion might be cool:

Can we also enable naming the test definition file?
This could be a field in the left tile right above the code block.

My reasoning:

This would let the used give the test definition a specific name before downloading the file.
This would make the right tile use the specific name for the test definition from the left tile.
If this is too complex, I'm not super invested in having it. It's already pretty awesome!
```

Update the CLI command technique to support test definition name changes

#### Acceptance Criteria

**AC1**
As a user looking at the CLI command automate technique
I should be able to update the definition file name that will be used for the command

**Comment by xoscar** [comment]
@kdhamric @olha23 could you take a look at this?

**Comment by kdhamric** [comment]
I think I know what you are suggesting, but not exactly. If you and @adnanrahic think it would be an improvement, do it.

**Comment by olha23** [comment]
@xoscar I’m not sure that i understand what i need to do here. Something like this? https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=250%3A13639&t=ciXYmunOH3EMEgOt-1

**Comment by adnanrahic** [comment]
Added my 2 cents in the Figma design.

**Comment by olha23** [comment]
updated
