### ISSUE TITLE
[Analyzer] Global Configuration - Test Run Failure Gates - CLI

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2778]
As part of the changes to support a specific failure point for test runs, we need to update the backend to support these changes.

#### Acceptance Criteria

**AC1**
As a user configuring the server
I should be able to set the required gates for test runs
Which should be a list of any of the following
- test specs
- analyzer score
- analyzer rule

**AC2**
As a user executing a test
I should be able to attach the failure point to the command as flag
Which overrides the global configuration

**AC3**
As a user that executed a test
I should see the failure point configuration used for the run
And the result of such calculation passed/failed

**AC4**
As a user configuring the CLI
I should be able to configure the test runner resource as any other
including the verbs for:
- list
- get
- apply
- delete

And with the formatters for `pretty`, `json` and `yaml`

```[tasklist]
### Tasks
- [ ] https://github.com/kubeshop/tracetest/issues/2950
- [ ] https://github.com/kubeshop/tracetest/issues/2945
- [ ] https://github.com/kubeshop/tracetest/issues/2946
```

**Comment by xoscar** [comment]
The flag used for the gates in the CLI should be describing the list of checks that fail the test run.

### Suggestion #1

Names:
- `gates`
- `failure-gates`
- `required-gates`
- `required-passing-gates`

CLI Command
```
tracetest run test <name> <gate1>,<gate2>,<gate3>
```

### Suggestion #2

Names:
- `required-gate-analyzer-score`
- `required-gate-analyzer-rules`
- `required-gate-test-specs`

CLI Command
```
tracetest run test --required-gate-analyzer-score --required-gate-analyzer-rules <...etc>
```

```
tracetest run test --falure-gate-analyzer-score --falure-gate-analyzer-rules <...etc>
```

Tagging everyone to start a conversation on how we want to implement this, please share your thoughts @schoren @mathnogueira @danielbdias @jorgeepc @olha23 @adnanrahic @kdhamric

**Comment by schoren** [comment]
how about this?
```
tracetest run test --required-gates analyzer-rules,analyzer-score,test-specs
```

single flag, comma separated values. This gives us flexibility if we need to add/remove gates in the future. It's easier to deprecate values than flags IMO
