### ISSUE TITLE
Improve attribute menu behaviour

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2902]
Please check the video 
https://www.loom.com/share/4f94738f87af4d6b90650c49fcf762be?sid=19fa01b4-2943-408a-8010-e62151d6fdce

**Comment by xoscar** [comment]
Hey @olha23 so it should only be visible for the very first time the user lands on the trace view? and the drawer is opened? or what are the criteria for showing and hiding the message?

**Comment by olha23** [comment]
@xoscar sure, here’s detailed instruction how it must work:

It’s must be like one time visual hint for user (something like you see in applications when highlighted the new functionality)

1. Pulsing circle to catch the user attention:
<img width="570" alt="Screenshot 2023-07-13 at 11 24 35 AM" src="https://github.com/kubeshop/tracetest/assets/5725840/8da23ccf-f3a6-4124-ad7c-a7af2cec691c">
2. The message appears:
<img width="251" alt="Screenshot 2023-07-13 at 11 36 53 AM" src="https://github.com/kubeshop/tracetest/assets/5725840/026f90d0-dbc9-4ec9-9e01-2559ddb1b12a">
(i added title and close icon)
3. When user close this message we don’t show it anymore. The main point here to let user know the attitude menu there
