### ISSUE TITLE
Add support for signoz as source for Tracetest

### ISSUE THREAD

**Issue by Connect2naga** [kubeshop/tracetest#2927]
HI,
Is there any support in tracetest, to read data from Signoz.

Both Tracetest & signoz  will have support open telemetry.  Since data is available in Signoz it will be good to have  signoz as source.

Else same metric data persisted in both Tracetest(for test) & Signoz(visualization), which will be duplicate.

**Comment by danielbdias** [comment]
Hi @Connect2naga , thanks for opening this issue!

It seems interesting, I'm working on it right now on #2935, and I believe that we can enable it soon (probably on the next Tracetest release next week).

**Comment by xoscar** [comment]
Hello @Connect2naga yesterday we released `v0.13.0` which includes support for Signoz as a OTPL DataStore
