### ISSUE TITLE
Create separate transaction flow

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#2937]
WIP. mockups https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=734%3A19203&mode=design&t=aMhGDnZ70ifoj5qn-1

**Comment by jorgeepc** [comment]
is this done @xoscar @olha23 ? Should we close the ticket?

**Comment by olha23** [comment]
@jorgeepc yes
