### ISSUE TITLE
docker-compose file for  tracetest with signoz not working as expected.

### ISSUE THREAD

**Issue by Connect2naga** [kubeshop/tracetest#2952]
HI ,
Created support request for Signz+ tracetest https://github.com/kubeshop/tracetest/pull/2935. Thanks for help with example.

Facing issue with example.  Tracetest Server failed to start with below error (example mention in repo)

 _✘ connect2naga@connect2naga  ~/.../examples/tracetest-signoz   main  docker-compose logs -f tracetest
Attaching to tracetest-signoz_tracetest_1
tracetest_1                      | 2023/07/16 13:45:08 Config file used:  /app/tracetest.yaml
tracetest_1                      | tracetest-server v0.12.2 (main)
tracetest_1                      | Starting
tracetest_1                      | New install? true
tracetest_1                      | sending event "Install" (beacon)
tracetest_1                      | event sent "Install" (beacon)
tracetest_1                      | OTLP server started on :4317 (grpc) and :4318 (http)
tracetest_1                      | tracePoller start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | tracePoller start goroutine
tracetest_1                      | tracePoller start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | tracePoller start goroutine
tracetest_1                      | sending event "Server Started" (beacon)
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | tracePoller start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | PersistentTransactionRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | PersistentTransactionRunner start goroutine
tracetest_1                      | PersistentTransactionRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
tracetest_1                      | event sent "Server Started" (beacon)
tracetest_1                      | PersistentTransactionRunner start goroutine
tracetest_1                      | PersistentTransactionRunner start goroutine
tracetest_1                      | persistentRunner start goroutine
**tracetest_1                      | 2023/07/16 13:45:09 [provisioning] attempting file:  /app/provision.yaml
tracetest_1                      | 2023/07/16 13:45:09 [provisioning] error: invalid resource type from yaml**
tracetest-signoz_tracetest_1 exited with code 1
 connect2naga@connect2naga  ~/.../examples/tracetest-signoz   main _

looks like there is issue with DataSource. Please help here.

Step to reproduce issue  : same steps mention in Readme.md https://github.com/kubeshop/tracetest/blob/main/examples/tracetest-signoz/README.md

Could you please evaluate once and correct me where i am wrong.?

Thanks,

**Comment by kdhamric** [comment]
I do not believe we have released the version containing the signoz data store support yet - I just verified v0.12.2 does not have it. We will be releasing either Monday or Tuesday and it should work. correctly then.

In the meantime, I believe you can get it working by configuring the provisioning file to use the otlp datastore. Find this file:
examples/tracetest-signoz/tracetest/tracetest-provision.yaml

and change the two occurrences of 'Signoz' to 'otlp' and then try the install again. Let us know whether this works or not...

<img width="610" alt="image" src="https://github.com/kubeshop/tracetest/assets/1385894/f3a9889a-355d-4477-908a-ace9f0071c56">

**Comment by Connect2naga** [comment]
ok, but if it is otlp, then it there will be two source for the same data (one is signoz & another tracetest)

**Comment by kdhamric** [comment]
The oltp setting tells Tracetest 'you are going to receive oltp trace data on one of the standard ports (4317 or 4318) from the instrumented system under test. With the OTel Collector sent to send data to both Tracetest and signoz (see https://github.com/kubeshop/tracetest/blob/main/examples/tracetest-signoz/tracetest/collector.config.yaml) we just need to tell Tracetest 'expect to receive the trace data via one of these two ports'. 

Tracetest gets trace data in one of two ways:
- direct: there is an api or data store we can connect to and directly reach out and grab the completed trace
- via oltp: we configure Tracetest to accept incoming OLTP data and use the OTel collector to route this data to both us and the trace data store that you are currently using.

**Comment by Connect2naga** [comment]
HI.
With latest version , able to bring the docker compose up.
but for test execution is giving below error:



```
 connect2naga@connect2naga  ~/.../github.com/kubeshop  tracetest test run -d tracetest/tests/list-tests.yaml
WARN    You haven't configured your CLI, some commands might fail!
WARN    Run 'tracetest configure' to configure your CLI
CLI: v0.12.2
Server: Not Configured
✖️ Error: Version Mismatch
The CLI version and the server version are not compatible. To fix this, you'll need to make sure that both your CLI and server are using compatible versions.
We recommend upgrading both of them to the latest available version. Check out our documentation https://docs.tracetest.io/configuration/upgrade for simple instructions on how to upgrade.
Thank you for using Tracetest! We apologize for any inconvenience caused.
 ✘ connect2naga@connect2naga  ~/.../github.com/kubeshop 
```

**Comment by Connect2naga** [comment]
Thanks , it is working with new release

**Comment by kdhamric** [comment]
Great to hear it worked. Let us know if you need any additional capability. Would love to hear how you are using Tracetest - you can contact me at https://www.linkedin.com/in/ken-hamric-016b1420/.

**Comment by kdhamric** [comment]
Currently you will need to use Signoz with the OTel collector. I put a message in the Signoz slack asking if there is an API or database connection exposed that we could use, but it has not been answered. It might help if you were to add a comment to it saying you are interested in this also: [](https://signoz-community.slack.com/archives/C01HWUTP4HH/p1690213833204599)
