### ISSUE TITLE
Update installer script docs with new options

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#2969]
We added a new option to the installer script so users can request to install a specific version. 
Usage:
```
curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash -s -- [version]
```

Example:

```
curl -L https://raw.githubusercontent.com/kubeshop/tracetest/main/install-cli.sh | bash -s -- v0.12.1
```

Notes:
1. this method skips package managers and directly downloads the build from the release page.
2. because of that, f tracetest was previously installed using a package manager, that version will still exist in the system, so depending on the `$PATH` env var configuration, that version might take precedence over the user selected one.

**Comment by adnanrahic** [comment]
Here is a preliminary idea of how to add it:

![localhost_3000_cli_cli-installation-reference](https://github.com/kubeshop/tracetest/assets/15029531/0946f758-19b8-4e34-9794-82da190825c2)
