### ISSUE TITLE
Available resource names should be returned on CLI when missing

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#2976]
When doing a tracetest list, the CLI informs you that you need to send a resource name but does not tell you what the possible resource names are. 

AC1: On running any command that has the resource name missing (tracetest delete, tracetest list, etc) It needs to say:
[resource] resource name must be provided (analyzer | config | datastore | demo | environment | pollingprofile | test | testrunner | transaction)

AC2: We have a typo - correct the spelling of ocurred to occurred

This is how tracetest list currently works - it gives the user no idea of how to move forward / what the choices are):
```
tracetest list

Version
CLI: v0.13.0
Server: v0.13.0
✔️ Version match

An error ocurred when executing the command

The following errors occurred when validating the flags:
[resource] resource name must be provided
```

**Comment by kdhamric** [comment]
@schoren Any interest in tackling this one across all the verbs?

**Comment by schoren** [comment]
on it!
