### ISSUE TITLE
Add trace id to tracetest test run output

### ISSUE THREAD

**Issue by BartNetJS** [kubeshop/tracetest#2986]
When running test, especially when there are issues, the next step is to explore the traces, logs, etc.
In my case we are using jaeger as next step to explore the full orchestration and failed calls.
In the next step we look at the log files and also filter on the traceid.

It would handy to report that trace id as part of a tracetest test run (in pretty, json,...)

**Comment by kdhamric** [comment]
Great idea Bart. Does this format look good:

✘ Pokeshop - List (http://localhost:11633/test/03Q33Fq4R/run/4/test) - trace id: cb5e80748cc06f8a63f6b96c056defec
	:heavy_check_mark: span[tracetest.span.type="general" name="Tracetest trigger"]
		:heavy_check_mark: #7681cb226e149778
			:heavy_check_mark: attr:tracetest.response.status = 200 (200)
	:heavy_check_mark: span[tracetest.span.type="database" name="count postgres.pokemon" db.system="postgres" db.name="postgres" db.user="postgres" db.operation="count" db.sql.table="pokemon"]
		:heavy_check_mark: #bcb71d6393e58988
			:heavy_check_mark: attr:tracetest.span.duration < 20ms (11ms)
	✘ Required gates
		:heavy_check_mark: test-specs
		✘ analyzer-rules
		:heavy_check_mark: analyzer-score

**Comment by BartNetJS** [comment]
@kdhamric that's fine for me.
Good solution!

**Comment by kdhamric** [comment]
@schoren is going to try to include this in our next release for tests and transactions / test suites.
