### ISSUE TITLE
UI showing invalid run times for a test that was not run in a transaction

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#3063]
**Describe the bug**

When we run a `Transaction` / `TestSuite` on the CLI and it fails on the first steps, the other test steps are created with no runs. 

When seeing the tests on the Web UI, we see an invalid last run time for them ("2024 years ago").

<img width="1769" alt="image" src="https://github.com/kubeshop/tracetest/assets/12397879/5e3293f3-e7e5-4711-b836-3de0c87b898d">

**Comment by jorgeepc** [comment]
fixed by https://github.com/kubeshop/tracetest/pull/3390 closing this ticket
