### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by tigersabre** [kubeshop/tracetest#3222]
**Describe the bug**
After entering "tracetest start" I'm redirected to the web ui, but I get a failure message saying oauth has failed and to try again later.

**To Reproduce**
1. execute "tracetest start" command

**Expected behavior**
Log in to the webui to configure

**Screenshots**

**Browser (please complete the following information):**
Chrome: Version 117.0.5938.92 (Official Build) (arm64)

**Additional context**

**Comment by kdhamric** [comment]
Reproduced this by signing in with a new user using Google Mail. My prior github account worked.
![image](https://github.com/kubeshop/tracetest/assets/1385894/3546a381-9f7c-465a-b0f9-84f2e34faa92)

**Comment by tigersabre** [comment]
Yep, and now that Ive signed in with Google, my GitHub acct with same email
is flagged as a duplicate.

**Comment by jorgeepc** [comment]
Hey @tigersabre we identified the issue and the team is working on a fix. Will keep you posted.

**Comment by kdhamric** [comment]
@tigersabre I am now able to login with both my google and github account. I did have to:
- log out of app.tracetest.io (if you are logged in - you can do this at the top right)
- if you are on the mac, do a 'rm ~/.tracetest/config.yml'. You likely do not have one, but this resets your CLI to having no knowledge of an account with Tracetest.
- clear your cookies for app.tracetest.io
- try a 'tracetest start' again

The team will be looking at this further in the morning - sorry for the issue!
![image](https://github.com/kubeshop/tracetest/assets/1385894/2f68977d-94cb-48b7-80af-2fe96d41e2cd)

**Comment by kdhamric** [comment]
@tigersabre we believe it is corrected now. Can you let us know once you have tried again whether it is successful or not?

**Comment by jorgeepc** [comment]
This issue was fixed. We don't have new reports around this. I'm closing the ticket.
