### ISSUE TITLE
Metadata in GRPC is disappearing 

### ISSUE THREAD

**Issue by Gibonachi** [kubeshop/tracetest#3258]
**Describe the bug**
Added metadata values are not shown on the call details. I'm not sure if metadata is correctly used during the call because I cannot successfully use the gRPC endpoint. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to gRCP test
2. Add metadata to a call 
3. Click Save & Run
4. Go back to the test list
5. Enter into previously used version of the test

**Expected behavior**
Metadata values should be present, I see only empty fields.

**Screenshots**
![obraz](https://github.com/kubeshop/tracetest/assets/39117601/7b4f307f-4ec2-46ec-8ba5-a8fe4adcc2c5)

**Browser (please complete the following information):**
 - Browser: Firefox and Chrome 
 - Version F 118.0.2 and Chro 118.0.5993.71

**Comment by adnanrahic** [comment]
Hey @Gibonachi, thanks for reporting this bug. We will prioritize this and keep you updated.

**Comment by adnanrahic** [comment]
Hey @Gibonachi ! #3259 solved this issue. Thanks a lot for taking the time to open the issue and be a valuable member of our community! 😄

**Comment by mathnogueira** [comment]
Hey @Gibonachi , we have a release scheduled for Monday. The fix will be included in it.

**Comment by Gibonachi** [comment]
In which version is this fix? Will bumping it to v0.14.3 be sufficient?

**Comment by jorgeepc** [comment]
Hey @Gibonachi Yes, the fix is included in `v0.14.3`. Please try it and if you find any issue let us know.
