### ISSUE TITLE
Test run on CLI don't stop if we opted for cancel a test on the WebUI

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#3280]
**Describe the bug**

If an user run a slow test on the CLI and then enter on the WebUI to cancel it, the CLI will became stuck on the test run.

**To Reproduce**
1. Run a test through the CLI with `tracetest run test -f my-test.yaml`
2. Go to the WebUI, choose the test that is running and cancel it
3. The CLI will continue to poll our API and will not stop

**Comment by xoscar** [comment]
We have removed the stop option from the UI after we implemented the skip trace feature, I'm closing this until we start working on the fresh new stoping mechanism
