### ISSUE TITLE
"Pokeshop - Import" makes error when running on Linux

### ISSUE THREAD

**Issue by mrasu** [kubeshop/tracetest#3393]
**Describe the bug**
When following the getting-started at https://docs.tracetest.io/getting-started/open, I encountered an error failing to connect to `host.docker.internal`
I'm using Ubuntu 22.04 but this may happen in all Linux distributions.

**To Reproduce**
1. Run docker-compose at tracetest/examples/tracetest-agent/pokeshop.
2. Create a new test from "Pokeshop - Import" in app.tracetest.io
3. "Run Test"
4. The test won't finish and docker compose outputs following error
```
pokeshop-otel-collector-1  | 2023-11-23T08:47:09.312Z	warn	zapgrpc/zapgrpc.go:191	[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
pokeshop-otel-collector-1  |   "Addr": "host.docker.internal:4317",
pokeshop-otel-collector-1  |   "ServerName": "host.docker.internal:4317",
pokeshop-otel-collector-1  |   "Attributes": null,
pokeshop-otel-collector-1  |   "BalancerAttributes": null,
pokeshop-otel-collector-1  |   "Type": 0,
pokeshop-otel-collector-1  |   "Metadata": null
pokeshop-otel-collector-1  | }. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host"	{"grpc_log": true}
pokeshop-otel-collector-1  | 2023-11-23T08:47:09.312Z	info	exporterhelper/queued_retry.go:215	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "otlp/tracetestagent", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup host.docker.internal on 127.0.0.11:53: no such host\"", "interval": "5.52330144s"}
```

**Expected behavior**
Finish running test

**Additional context**
After adding extra_hosts in all services in docker-compose.yaml, the test finished
```yml
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Comment by danielbdias** [comment]
@mrasu, thanks for your report! We will take a look at this issue!

**Comment by mathnogueira** [comment]
Great catch @mrasu! I tested it on Linux and I was able to reproduce the issue. Thanks for opening the issue and providing a solution!

**Comment by mathnogueira** [comment]
The fix is now merged! I'll create a new card to review all examples with the agent as well. I'm closing this for now, but feel free to open new issues if you find anything.

Thanks again @mrasu!

**Comment by mrasu** [comment]
Thank you!
