### ISSUE TITLE
Sumo Logic Integration

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#3423]
Provide a direct integration for Sumo Logic to support it within Tracetest as a trace data source.

Drew Horn from Sumo Logic provided some links that can help:
https://api.us2.sumologic.com/docs/#tag/traces
https://www.sumologic.com/app-development-checklist/

**Comment by kdhamric** [comment]
@sumo-drew Want to get Drew Horn's eyes on this...

**Comment by mathnogueira** [comment]
So my understanding by reading the API docs is that I need to call these apis:

* [get trace spans](https://api.sumologic.com/docs/#operation/getSpans) until I get all spans from the trace
* [get all span events](https://api.sumologic.com/docs/#operation/getTraceLightEvents) until I get all events from that trace

**Comment by mathnogueira** [comment]
I don't know if that's possible, but could we get a free account just to run integration tests against this vendor?

**Comment by sumo-drew** [comment]
@kdhamric , @mathnogueira - Yes those are the endpoints. How many traces are we talking about pulling into TraceTest? Every trace ever created from an automated test? Do you need the entire trace and all attributes all at once?

**Comment by mathnogueira** [comment]
Basically we need to get one trace per test. We will call the first endpoint a couple of times to ensure the trace has stopped receiving new spans and then call the second endpoint for each span as we need all attributes and events from each span.

**Comment by adnanrahic** [comment]
I can take the lead on adding docs and examples for SumoLogic.
We have this page that needs more work: https://docs.tracetest.io/configuration/connecting-to-data-stores/sumologic/
And, we need an example app in the `examples` folder in the GitHub repo.

**Comment by adnanrahic** [comment]
Update on the above. We've merged the docs work for Sumo Logic.

**Comment by adnanrahic** [comment]
I think we can close this since we've added docs and examples for Sumo Logic.
