### ISSUE TITLE
Explain variable sets in UX

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#3427]
When a new user selects the 'Create a new variable set' while exploring the tool, we do not provide any information helping them understand the purpose or why they could want one. We also do not provide a link to help so they can get more information.

Lets add this at the top of the form:
Variable sets are groups of variables that can be referenced by tests using this syntax: http://${var:HOSTNAME}/api/users. Read more.

and have 'Read more' open a page in a new window and go to https://docs.tracetest.io/concepts/variable-sets.

@olha23 Can you review this and then assign it to @jorgeepc ?

![image](https://github.com/kubeshop/tracetest/assets/1385894/ab144c08-fdb7-4400-b9f3-61a33b8c2875)

**Comment by olha23** [comment]
Mockups here https://www.figma.com/file/uFNQoIl7aCF0gAvLyJM4rf/Tracetest-Cloud-(October)?type=design&node-id=742%3A427&mode=design&t=IG8EDUIVC6SdwL6K-1
