### ISSUE TITLE
Cannot cancel when in guide tour on create test

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#343]
When on [demo.tracetest.io](https://demo.tracetest.io/), 
when I click Guided Tour, 
then Create Test button, 
then the X to close the tour,
I can then not Cancel the creation of the test.  Clicking both the Cancel Button and clicking the X at the top right of the test creation form both cause the modal to flash but it relaunches the modal immediately.

https://www.loom.com/share/f19832c961714fd8b883f1591915968a

**Comment by kdhamric** [comment]
@xoscar Is this corrected?

**Comment by xoscar** [comment]
Yeah, I think we should fix this one
