### ISSUE TITLE
UX: Sumo Logic integration

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#3430]
## Description

We are adding a new integration for Sumo Logic (#3423), so we need to design a new data store screen for it to be configured.

To configure the integration, we need three fields:

**Endpoint**: https endpoint to the Sumo Logic deployment (e.g. `https://service.sumologic.com/`)
**Access ID**: id of the access key (14 characters) (e.g. `oy6MVyDivotH2M`)
**Access Key**: password of the access key (64 characters) (e.g. `nm96ldyyiJs7iEJFHfqWNC9n3UxwaCWs50O1cUyUFCYQjHyDaxfpWYblck4cnltL`)

Those values were randomly generated.

**Comment by jorgeepc** [comment]
This task is done.
