### ISSUE TITLE
Air-gapped installation of tracetest

### ISSUE THREAD

**Issue by johnqa** [kubeshop/tracetest#3435]
**Is your feature request related to a problem? Please describe.**
I am working in an air-gapped environment, where we have a proxy to enable us to use docker images, but does not allow us to use urls to install from github or other places.

**Describe the solution you'd like**
I would like to be able to install tracetest cli on an air-gapped workstations.

**Describe alternatives you've considered**
Have a docker only installation for tracetest.

Thank you

**Comment by adnanrahic** [comment]
Hey @johnqa ! 👋 

Have you tried running the CLI from a Docker image?
This docs page explains how to do it: https://docs.tracetest.io/cli/configuring-your-cli#running-tracetest-cli-from-docker

Let me know if that solves your issue. 🙌

**Comment by johnqa** [comment]
Hi, this is good enough for me.

Thanks for pointing me to that page.
