### ISSUE TITLE
bug with component timeline

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#346]
There are multiple scroll going on the test detail page, this cause confusion for the user draging the the component timeline component

**Comment by kdhamric** [comment]
@olha23 any idea what this bug is / was?  If we are not sure, lets just close the issue.

**Comment by cescoferraro** [comment]
@kdhamric 
#429  solves this issue by making extensive use of the flex-grow css propriety. 
Avoiding hardcoded height calculation, we can avoid unnecessary scroll bars that were causing the issue
