### ISSUE TITLE
Replace all mentions of Discord with Slack

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#3479]
Since we are moving the community to Slack, we need to replace all the mentions, logos, and links of Discord to Slack and the new Slack Community invite.

- https://dub.sh/tracetest-community

**Comment by adnanrahic** [comment]
I've added a PR to update this in the docs and examples: https://github.com/kubeshop/tracetest/pull/3480

I will need help with updating it in the Tracetest app.

**Comment by xoscar** [comment]
PR for the FE changes 
- https://github.com/kubeshop/tracetest/pull/3489

**Comment by jorgeepc** [comment]
This was merged and released. Feel free to close this ticket @adnanrahic
