### ISSUE TITLE
[bug] Polling for traces from Grafana Cloud Tempo does not work

### ISSUE THREAD

**Issue by adnanrahic** [kubeshop/tracetest#3507]
**Describe the bug**
Polling for traces from Grafana Cloud Tempo does not work

**To Reproduce**
1. Go to 'settings > tracing backends'
2. Click on 'tempo'
3. Add Grafana Cloud Tempo creds
4. Connection test fails and test run fails to fetch traces

**Expected behavior**

**Screenshots**

**Browser (please complete the following information):**
 - Browser: [Firefox]
 - Version [e.g. 99]

**Additional context**

**Comment by xoscar** [comment]
@adnanrahic I was able to get it working with this setup
![Screen Shot 2024-01-09 at 5 00 32 p m](https://github.com/kubeshop/tracetest/assets/11051031/1ecf7337-a201-4833-ba04-e46501ae2839)
