### ISSUE TITLE
Docs: Break Creating Tests into different pages per trigger type

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#3593]
Currently, 'Creating Tests' is a single page that shows how to create a test with a HTTP based trigger. Tracetest supports 6 other trigger types:

1. gRPC
2. Kafka
3. TraceID
4. Cypress
5. Playwright
6. k6

For importing tests, we have a page detailing each way to import a test (definition, cURL, and Postman).

Proposal: Create detailed pages for each of the 6 trigger types above, and have 'Creating Tests' expand to show the 6 options. Each page should:
- if appropriate, discuss the why / benefit (what does Tracetest add to a Cypress test, for example). This should be brief as this is a 'how to' page and not marketing, but we should at least state it.
- detail the steps to create a test with that test type
- link to any specific recipes or examples that show how to use that trigger type. May want to link to the marketing integration page for that product if appropriate (example: https://tracetest.io/integrations/cypress or https://tracetest.io/integrations/k6)

Impetus for doing this work: We recently had a user ask how to create a TraceID based test, and we did not have a great link to point them to. In addition, having dedicated pages to create tests based on these keywords such as 'Creating a Kafka based test' will be attractive for individuals looking for solutions for particular technologies such as k6, Kafka, gRPC, Cypress and Playwright.

@adnanrahic Wanted your thoughts before we decide to work on this. Once we get that, lets have @jfermi create the pages. For topics such as Playwright, Cypress & k6 that are fully documented on separate pages, we can have a short paragraph stating what it is for an pointing to the alternative page(s).

![image](https://github.com/kubeshop/tracetest/assets/1385894/bcacd08a-0188-4ee8-9170-9b8516ab8c0d)

![image](https://github.com/kubeshop/tracetest/assets/1385894/4ff2f92f-912f-49f3-97c2-cb0c52c120c4)

![image](https://github.com/kubeshop/tracetest/assets/1385894/a90d0d85-b433-4fee-a5dd-69897fe832ae)

**Comment by adnanrahic** [comment]
@kdhamric @jfermi I like this idea a lot. Let's pull the trigger and start working on it ASAP.

**Comment by adnanrahic** [comment]
Step 1 is done!

PR: https://github.com/kubeshop/tracetest/pull/3750

**Comment by adnanrahic** [comment]
Step 2 is done!

PR: https://github.com/kubeshop/tracetest/pull/3828

**Comment by adnanrahic** [comment]
Live:

- https://docs.tracetest.io/web-ui/creating-tests
- https://docs.tracetest.io/cli/creating-tests
