### ISSUE TITLE
Configure http client to use right certificate

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#362]
This [PR](https://github.com/kubeshop/tracetest/pull/361) made the analytics module unsafe by disabling tls checks. This should not be done, but as we were in a rush, I did it to save time and deploy the demo.

We have to fix it.

**Comment by kdhamric** [comment]
Wondering what we need to do to correct this?

**Comment by mathnogueira** [comment]
Basically, we are skipping the certificate when sending the request to google docs. To solve that, we would have to:

1. get a valid certificate
2. configure the client to use it.
