### ISSUE TITLE
Enable ability to resize areas when viewing a test run

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#3665]
Currently, the Trace tab gives you full control over the three vertical areas. You can hide or resize either area on the left or right. In doing a demo today, @adnanrahic and I wanted to focus on just the trace while on the Test tab. We could close & resize the attributes area, but not the test specs area.

Proposal: Make all of the vertical sections on the Trigger, Trace, Test, and Automate tab sizable, and we may want a quicker way to focus on one vertical band (ie close the other one).

Some use case:
I am on the trigger tab, and want to view the response data fully, but I only get half the screen. I would like to be able to close (or resize) the test setup area on the left.

I am on the test tab, and I have an attribute such as tracetest.response.headers that has a lot of json in a small width column. Ideally, I could collapse the Trace and Test specs area (or resize them).

If we do this, we need an easy way to reopen the area (ie it needs to be obvious it is there and easy to reopen).

Would like to first get feedback and then have @olha23 take that feedback and implement.

![image](https://github.com/kubeshop/tracetest/assets/1385894/8cd14159-d2cc-49ca-a263-4d9851d0aee4)

**Comment by olha23** [comment]
Regarding test tab we can make  test specs section resizable like in trace tab. For the Trigger and Automate tabs, based on our current usage patterns the value of implementing resizable and collapsible sections in these particular tabs might not be as pronounced as in the Trace and Test tabs. The primary interactions within the Trigger and Automate tabs seem to be more straightforward, with less immediate need for adjusting the visibility and size of vertical sections. I think we could starting with the Trace and Test tabs, and based on user feedback, extend these features to the Trigger and Automate tabs as needed.

**Comment by adnanrahic** [comment]
To summarize, this issue would be solved by:

1. **Adding the ability to resize the right panel with test specs and test outputs on the Test tab.**
2. **Adding the ability to resize both panels on Trigger and Automate tabs.**

**Comment by kdhamric** [comment]
@olha23 We do not need to optimize the timing on enabling the sections to be have adjustability added in. It would make the panels consistent across each of the tabs (ie I can resize all of them, not just particular ones in particular spots). This would make the user experience consistent, and I would not be left wondering 'can I do it here, or just somewhere else'.

**Comment by jorgeepc** [comment]
I like the idea of allowing the user to focus on one area of a tab. I understand that resizing is an approach that we already implemented, but I would like to see some mockups before doing the coding part.

One issue that I found in the `Trace` tab is that you can end up with a screen like this:

<img width="1505" alt="Screenshot 2024-02-20 at 09 46 09" src="https://github.com/kubeshop/tracetest/assets/3879892/e3bf7c44-93ce-47a3-a24c-33aa7036fc93">

In my opinion the left and right panels are not usable with a width like that (maybe not a big issue 🤔 ), but it would be great to consider those `min-width` as part of the requirements of this ticket.

Or should we ask ourselves if there is a different way of displaying the test run information in those tabs?

**Comment by olha23** [comment]
@jorgeepc yep, you are right. We need to consider minimal width for resizable sections. I think it’s can near 300 px. After this section must be closed.

**Comment by kdhamric** [comment]
I like this, but we may want the minimum to be based on percentage rather than pixel count. If we are trying to shut it down at a set pixel count, I would suggest a lower number as I set the width to 1280 for videos... we could hit 300 pixels for a panel pretty quickly on a 3 panel screen... might suggest something more like 150 pixels or so... 
![image](https://github.com/kubeshop/tracetest/assets/1385894/a7689d90-866f-4d06-b7e5-013d93e6f234)

**Comment by kdhamric** [comment]
One other comment - on some panels, we just transistion to 'closed' at below a certain width, which feels 'natural'. Not sure if this would be good or not - just a thought: https://www.loom.com/share/4eeb737d38214eff8e546a9ed20e1f26

**Comment by xoscar** [comment]
> @olha23 We do not need to optimize the timing on enabling the sections to be have adjustability added in. It would make the panels consistent across each of the tabs (ie I can resize all of them, not just particular ones in particular spots). This would make the user experience consistent, and I would not be left wondering 'can I do it here, or just somewhere else'.

I agree with this sentiment, when playing games or using apps,  I like the idea of the whole app having standardized "mechanics" if I can do that in x part I should be able to do it in y

**Comment by xoscar** [comment]
> One other comment - on some panels, we just transistion to 'closed' at below a certain width, which feels 'natural'. Not sure if this would be good or not - just a thought: https://www.loom.com/share/4eeb737d38214eff8e546a9ed20e1f26

we can extend the pixels or % of that considers the panels as closed
