### ISSUE TITLE
Update attribute lists for assertions based on spans currently selected

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#389]
https://github.com/kubeshop/tracetest/issues/236

**Comment by olha23** [comment]
We should show attributes that exist across all the spans at the top of the list, and others are shown later in the list below a dottted line

**Comment by olha23** [comment]
design https://www.figma.com/file/0MPQK2Icv7FvqHJnlColpv/MVP?node-id=633%3A3951

**Comment by kdhamric** [comment]
@olha23 It is the list that appears in this drop down that we are wanting to alter.  We want the attributes at the top to the the ones that are in common across all the spans.  The ones at the bottom will be the attributes that exist just for this span.  Need to show some kind of grouping:

--- across all spans ---
http.status
tracetest.span.duration
--- attributes for currently selected span ---
service.name
dddds.sdsdsd


![image](https://user-images.githubusercontent.com/1385894/166262417-584bb2b3-29a1-4d0f-9413-bf92b1014d63.png)

**Comment by olha23** [comment]
design https://www.figma.com/file/0MPQK2Icv7FvqHJnlColpv/MVP?node-id=651%3A4922
