### ISSUE TITLE
Cannot run the Playwright demo

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#3913]
When trying to run the Playwright demo documented at https://docs.tracetest.io/tools-and-integrations/playwright, there is an error when doing step 7. Run npm run pw:run or npm run pw:open.

It seems this can be corrected by changing the package.json file at https://github.com/kubeshop/pokeshop/blob/master/package.json to reference the 0.041 version.

We may need a carat on this line: "@tracetest/playwright": "0.0.37", in https://github.com/kubeshop/pokeshop/blob/master/package.json.

**Comment by xoscar** [comment]
Done!
