### ISSUE TITLE
Design specific tabs showing key attributes based on type of span - HTTP

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#397]

**Comment by olha23** [comment]
@kdhamric can you provide additional info for this ticket please. Like what exactly we need to show based on type of span

**Comment by kdhamric** [comment]
I have started an issue to discuss what should go on the span detail using the HTTP span as an example.  Feel free to do a tentative design based on the information there. https://github.com/kubeshop/tracetest/issues/409

**Comment by olha23** [comment]
design here - https://www.figma.com/file/0MPQK2Icv7FvqHJnlColpv/MVP?node-id=686%3A4600
