### ISSUE TITLE
Add dropdown actions to each test table row with the delete option

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#400]
For this page
![Screen Shot 2022-05-03 at 7 51 08 a m](https://user-images.githubusercontent.com/11051031/166456079-c8bccf54-06b4-4ec9-86f3-c3837bd4e842.png)

We need to add a three dots option to the right side of each row with a delete option. 

Work with the backend team @mathnogueira & @schoren to see if the delete endpoint is available and if so integrate it when the user selects the option.

**Comment by xoscar** [comment]
Design https://www.figma.com/file/0MPQK2Icv7FvqHJnlColpv/MVP?node-id=382%3A3657

**Comment by kdhamric** [comment]
Couple questions:
 - does this include the backend work to delete a test?  
 - when you do delete a test on the backend, are you actually deleting the test and test results, or marking them as deleted?  I would recommend marking them as deleted, but not actually removing them (just not showing them any longer).

**Comment by kdhamric** [comment]
I do not see the answers to my questions above?

Also - it looks like the delete action was added to the test runs, not the tests.

**Comment by kdhamric** [comment]
https://www.loom.com/share/f67e6715aa83416a8bebc7e48334e64a

**Comment by kdhamric** [comment]
How are we doing this:
when you do delete a test on the backend, are you actually deleting the test and test results, or marking them as deleted?

**Comment by xoscar** [comment]
I think the current implementation is deleting the tests from the DB, we might need to alter the schema to support soft delete @mathnogueira

**Comment by cescoferraro** [comment]
@kdhamric the current implementation on the backend deletes the test. I have talked with @schoren about this.
he sad for "soft" deletion will be implemented in the future.
