### ISSUE TITLE
404 Not found with test on Kubernetes but working outside tracetest

### ISSUE THREAD

**Issue by JasmineCA** [kubeshop/tracetest#4002]
**Describe the bug**
I'm testing tracetest and I decided to start right away with our microservice environment product. The goal is to be able to launch tracetest tests on pipeline. I deployed tracetest pod using helm chart on the same namespace as our product, then I just tried to copy paste an url from our e2e tests already running on pipeline to see if I'm able to have an answer. Unfortunately, tracetest UI keeps returning a 404 Not Found from Nginx, while the URL works from inside the namespace and inside the busybox of tracetest. I tried to call tracetest with the api but I had no luck. 

**To Reproduce**
1. Deploy tracetest on a kubernetes namespace along an http server (with an ingress defined)
2. Connect to tracetest and create a test targeting this http server using the ip of the kube (and not the name of the service itself)
3. Run test and wait for the 404 Not Found response

**Expected behavior**
Another answer that a nginx response. 

**Screenshots**
Screenshot from tracetest UI:
![Capture du 2024-08-30 17-19-00](https://github.com/user-attachments/assets/24ec08af-3ff9-46ac-8c47-bc58db9619ce)
Screenshot from the busybox of tracetest (Status Code 400 is expected, it's the http server)
![Capture du 2024-08-30 17-21-48](https://github.com/user-attachments/assets/dc5b2181-be64-43e1-b5e4-79207b3f8e94)
Screenshot from a curl image I deployed on the same namespace. Here the http server answers me with HTTP status code 400 and a body.
![Capture du 2024-08-30 17-20-36](https://github.com/user-attachments/assets/9b13d0ef-1664-490c-9116-8d43eeb7a550)

**Browser (please complete the following information):**
 - Browser: Firefox
 - Version 129.0.2

**Additional context**
I'm not managing the kube, so I can't change anything about its configuration (even for test purpose). But this is the first tool having this kind of issues. Do you had some fluff out of tracetest which prevents the request to succeed? How can I debug that on my side (logs, sniffer)?

**Comment by xoscar** [comment]
Hey @JasmineCA, it seems that the tracetest instance can connect to Nginx as if there was an error it would cause a trigger issue problem. 

Could there be a rule on the proxy side that returns a different response?

I'm tagging the team to see if they have an idea of what could be happening @mathnogueira @danielbdias @schoren

**Comment by JasmineCA** [comment]
Hello @xoscar,

I'm not sure that a rule on server side could trigger this answer. When the same api call works from outside the kube, inside the kube in the same situation (pod in the same namespace) and even a wget is working from the tracetest image itself, I would consider looking on how I'm using tracetest and how it's deployed. Maybe something important in this setup, I'm doing a port forward with kubectl to localhost in order to access the UI, maybe the issue could be there. But I looked on the request made by the UI, it's only requests on the traceserver, so I'm looking for other ways to debug.

**Comment by JasmineCA** [comment]
Also maybe something very important, since my kubernetes instance is quite "simple" (thanks to our platform engineers), so we have to put a manual host header in our client request. Maybe tracetest is resolving my host header?

**Comment by mathnogueira** [comment]
@JasmineCA I'll take a look at your issue. I have a question about this `Host` header. Does the value differ from the actual URL in the request? Could you send me an example?

**Comment by mathnogueira** [comment]
Could you try adding the `Host` header in your `tracetest` and see if that solves the issue?

**Comment by JasmineCA** [comment]
Hello @mathnogueira ,

The examples of curl and wget contain the host header. The value differs from the actual URL targetted, that's why I'm worried this could be my issue here. I already had this issue with docker containers inside docker desktop targetting our kube. Docker Desktop was trying to resolve the value of the host header instead of the url provided in the curl command. 

About your suggestion, I already added the Host header in my tracetest test, with no luck (I will provide a screenshot). I will try to remove the header from my curl command and provide you the results.

**Comment by JasmineCA** [comment]
Here is my screenshot, so you can see that I provide the header host.

![Capture du 2024-09-03 19-30-58](https://github.com/user-attachments/assets/d0006047-ab6c-4b15-be11-38189007e59a)

And for the curl command, yes removing the header host gives the same 404 error response as the tracetest test. So we may have found the issue.

**Comment by mathnogueira** [comment]
Oh great. I'll check what's happening with this header durante the trigger phase.

**Comment by mathnogueira** [comment]
I'm releasing the new version `v1.5.4` . It should be available in about 25 minutes. Can you update and see if the problem persists?

**Comment by JasmineCA** [comment]
Hello @mathnogueira , I tested your new version and it worked as expected! I'm happy to continue testing around with tracetest now. If you don't have anything to add, I suggest closing this issue. Don't forget to update the helm chart as well. Thank you for your support!
