### ISSUE TITLE
Tracetest Server APIs not accessible

### ISSUE THREAD

**Issue by cb645j** [kubeshop/tracetest#4045]
I am running the tracetest server in a k8 environment using the official tracetest helm chart.  When I try to access any of the APIs outlined in the documentation (openapi), I receive back a javascript error or a message saying "moved permanently".  How do you access the json apis? What is the path to the api backend server? Urls ive tried are below. It seems all these paths hit the frontend javascript, i want to access the json apis directly. 

**Request**: GET http://tracetest:11633/api/testsuites/
**Response**: `<a href="/api/testsuites">Moved Permanently</a>.`

**Request**: GET http://tracetest:11633/testsuites/
**Response**: <!doctype html><html lang="en"><head><meta charset="utf-8"/><link href="./favicon.ico" rel="icon"/><meta content="width=device-width,initial-scale=1" name="viewport"/><meta content="#2f1e61" name="theme-color"/><meta content="Tracetest - Build integration and end-to-end tests in minutes, instead of days, using OpenTelemetry and trace-based testing." name="description"/><meta name="robots" content="noindex"/><link href="./logo192.png" rel="apple-touch-icon"/><link href="./manifest.json" rel="manifest"/><title>Tracetest</title><script>const parser={toArray(e){try{return JSON.parse(e)||[]}catch(e){return[]}},toBoolean:e=>"true"===e,toObject(e){try{return JSON.parse(e)||{}}catch(e){return{}}},toString:e=>e};function getTemplateValue(e,t,r){var a=String.fromCharCode(123),n=`${a}${a}`;return!e||e.startsWith(n)?r(t):r(e)}function injectVariables(){window.ENV={measurementId:getTemplateValue("X2vwYODI1vb8g6QpzL9OBxuv5vK7dGan","",parser.toString),analyticsEnabled:getTemplateValue("false","false",parser.toBoolean),serverPathPrefix:getTemplateValue("/","/",parser.toString),serverID:getTemplateValue("b33cca3ef1","",parser.toString),appVersion:getTemplateValue("v1.7.0","",parser.toString),env:getTemplateValue("main","",parser.toString),experimentalFeatures:getTemplateValue("[]","[]",parser.toArray),isTracetestDev:getTemplateValue("true","false",parser.toBoolean),posthogKey:"phc_Rg59ClPckoqa5p4onheukqHKJFPbTJkiNzECjIG4lMj"};var e=document.createElement("base");e.href=window.ENV.serverPathPrefix,document.getElementsByTagName("head")[0].appendChild(e)}injectVariables()</script><script defer="defer" src="./static/js/main.9988b10e.js"></script><link href="./static/css/main.363d60d5.css" rel="stylesheet"></head><body><noscript>**You need to enable JavaScript to run this app**.</noscript><div id="root"></div></body></html>

**To reproduce:**
start tracetest server using helm chart.  Using postman or curl or http client, try to access any of the apis outlined in the openapi docs.

**Comment by cb645j** [comment]
@adnanrahic

**Comment by mathnogueira** [comment]
Hello @cb645j. Did you install Tracetest via `helm install tracetest kubeshop/tracetest`?

Are you using a production-ready k8s or a testing one like minikube or kind?

I tried installing tracetest locally and I could access the API at `http://localhost:11633/api/testsuites`

**Comment by mathnogueira** [comment]
Oh, you are adding a trailing slash at the end. Try removing it:

```
http://tracetest:11633/api/testsuites/ ==> http://tracetest:11633/api/testsuites
```

**Comment by mathnogueira** [comment]
@cb645j did you try removing the trailing slash in your URL? Did it work?

**Comment by cb645j** [comment]
oh wow, that actually fixed it. thanks a bunch!! im surprised putting a slash at the end would cause that, usually apps can support trailing slashes... I do have another question.  Does tracetest cli support proxy if you have proxy env variables set?  When I run tracetest locally along with the tracetest cli I am able to connect fine.  However when i try to configure tracetest cli to connect to a tracetest server running in a k8 test environment I get the "Cannot reach "http://tracetest-ingress:11633". Please verify the url and enter it again." error.  I try to run the configure command with -d flag but that does nothing.  Does the cli write logs anywhere? How do you suggest debugging?

**Comment by cb645j** [comment]
@mathnogueira Thank you.  Is there a way to access the latest version of a testsuite via the api??  If I access /testsuites/{testsuiteid} it does not return any specific version nor does it return the summary (despite the documentation showing it should).  Im assuming this api is supposed to return the latest version of the specified testsuite but the documentation is unclear on that.  So the only way to get the summary block is to query a specific version, i.e.  /testsuites/{testsuiteid}/version/{versionnumber}.  

**/testsuites/{testsuiteid}  response** (does not match documenation)
`{
    "type": "TestSuite",
    "spec": {
        "id": "smokeTestsSuite",
        "name": "Smoke Tests",
        "description": "Runs all cricial test cases",
        "steps": [
            "jettyDmeNukeServer",
            "jettyDmeNukeServer_nuke"
        ]
    }
}`

**/testsuites/{testsuiteid}/version/{versionnum}  response** 

`{
    "id": "smokeTestsSuite",
    "createdAt": "2024-10-08T17:57:01.034191Z",
    "name": "Smoke Tests",
    "description": "Runs all cricial test cases",
    "version": 3,
    "steps": [
        "jettyDmeNukeServer",
        "jettyDmeNukeServer_nuke"
    ],
    "fullSteps": [
        {
            .............
            }
    ],
    "summary": {
        "runs": 12,
        "lastRun": {
            "time": "2024-10-09T19:02:14.763736Z",
            "passes": 14,
            "fails": 3,
            "analyzerScore": 0
        }
    }
}`

**Comment by cb645j** [comment]
trailing slash was the issue
