### ISSUE TITLE
Plan how to handle versioning of tests

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#414]
We need to have some discussion / planning around handling versioning of tests.  This issue is to collect these thoughts.

As the test definition is altered or test assertions are added / changed, we need to be able to:
- maintain the state of old test results.  ie results are 'final', and info about the assertions / trigger transactions should match what existed when the test was run if a user clicks on an old test.
- there will be cases where a user wants to modify a test, particularly the assertions, on a test that is older (ie not the most recent).  Example: you have tests running on every push or every hour, and you notice one ran poorly 3 days ago.  Your test did not capture this as a failure, and you want to alter the assertions so it would the next time.  It would be convenient to alter it with the failed test.  
- Some tests can take a long time - it may be interesting to be able to apply the latest (or a particular version) of a tests assertions to an older run without having to do a rerun (this may be too complex for now... discuss and see if there is a seemless way).  Perhaps there could be an 'apply new assertions' concept and it produces a new result (likely confusing).

May be something we can use from: https://github.com/kubeshop/tracetest/pull/72

**Comment by schoren** [comment]
As part of the work on implementing the selectors/assertions in the backend, we implemented the following [structure for results](https://github.com/kubeshop/tracetest/blob/main/server/assertions/assertions.go#L55):

```
testDefinition:
  "selector": [
    {assertion: "assertion 1", result: {&refToSpan, actualValue, error}}, // empty error means success, NoMatch error means no pass, other errors means errors when trying to execute the assertion
    {assertion: "assertion 2", result: {&refToSpan, actualValue, error}}
    ....
  ]
```

The concept is to replicate the given test definition (in terms of selectors and assertions), and append the assertion result.  If we persist this structure, when we want to check an old test run, it will be composed by the definition and the results.

It is my personal opinion that tests runs should be immutable, in the sense that a result must be tied to the definition that resulted in that result.

Keep in mind that the `test definition` used here is a **copy** of the test definition used to launch the test run, so you can modify the "parent" definition and it will only affect following runs, not previous ones.

**Comment by kdhamric** [comment]
Looks good.  
On: It is my personal opinion that tests runs should be immutable, in the sense that a result must be tied to the definition that resulted in that result.

You are likely right.  Since test definition is based on a run (ie uses the response and trace from a triggering transaction), I would like the 'run view' to continue to be the 'test definition editor'.  The issue is when you alter the assertions, the test is changed, resulting in the test run being altered.  We need to think how to manage this.  Perhaps changing the assertions creates a new 'test run'... even though it is utilizing the same response & trace.  If we did do this, we would need to think through how to make this visible in the UI and have a flow that makes sense to a human being.

**Comment by mathnogueira** [comment]
We have it implemented now. I'm closing this ticket.
