### ISSUE TITLE
Plan clean OTEL json format

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#415]
We need a plan on how we want to structure the OTEL data we send to the front end.  Currently, we process all the spans in a trace in the backend, converting the trace from rpc/protobuf to a json version.  This version is deeply nested and overly  complex, making some tasks with the selector logic and assertion engine more difficult.  We need to decide if we are moving to a new structure and what the format will be.

This card is to collect thoughts and ideas of how to format the trace.

**Comment by schoren** [comment]
As part of the work for the assertions in the backend, we implemented a basic [trace structure](https://github.com/kubeshop/tracetest/blob/main/server/traces/traces.go). That is all the data that is required by the assertions/selectors engine to operate. 

If that data is enough for the frontend to render the tree, we might as well keep it. We probably need to tweak it a bit so it's easy to transmit as json.

**Comment by schoren** [comment]
Resolved by [464](https://github.com/kubeshop/tracetest/issues/464)
