### ISSUE TITLE
Plan what the CLI will look like and the commands it will support

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#416]
As a USER,
We need to be able to run tests at the command line and eventually integrate them into other tools,
So I can schedule tests, add them to CI/CD processes, etc

We need to decide what commands should be supported in the first version of a CLI.  This card is to track the discussion and come up with a plan.

**Comment by schoren** [comment]
My initial thoughts on a CLI:

```bash
$ tracetest --help

tracetest CLI is a tool to interact with a tracetest server.

Available commands

test list                                         list all test (we could add filters)
test create --file testfile.yaml    create a test from a yaml definition
test delete TEST_ID                   delete an existing test
test run  TEST_ID                       start a new test run
test results --test TEST_ID       list all results for a given test (maybe filters and sorting?)
test result RESULT_ID               get a test result details
```

I think that is enough to easily manage test, and integrate any CI tool. It might be a good idea to copy the `testkube` approach of being a `kubectl` plugin, so we can easily connect to the cluster without asking the user to expose the `tracetest` instance or manually tunneling to the k8s instance.

**Comment by kdhamric** [comment]
Looks good!  I am assuming that "test run  TEST_ID" would return a RESULT_ID?

**Comment by mathnogueira** [comment]
CLI was implemented using @schoren's idea. I'm closing this.
