### ISSUE TITLE
Planning how to initially  handle improving selectors

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#417]
Determine what near term changes are needed to make selectors handle the minimal needs (ie we can test Tracetest successfully, selecting individual spans accurately and predictably)>

We have a couple related issues:
#174 #214 

The purpose of this issue is to consolidate thoughts about the changes we should make.

**Comment by schoren** [comment]
https://github.com/kubeshop/tracetest/pull/419 documents the initial implementation by @mathnogueira

**Comment by mathnogueira** [comment]
This was already implemented. Closing it.
