### ISSUE TITLE
Simple issues from implementation of new UX

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#513]
These are items we want to change in the new UI that do not require design / @olha23 input:

- We want to be able to click on 'Test Status: Finished' and have the bottom test area expand (we watch somebody do this... might as well help get them to the test if they do not see it at the bottom)
- Click an X to delete one filter does delete the filter... but it puts you in 'add a new filter' mode and prompts you for an attibute.  I think you should have to click in the filed again to start the 'add filter' process.
- When editing an assertion, the 'Add' button should say 'Save'
- If you add a second check line (ie add check), there is no way to delete that line.  Should have a trash can next to it.
- Probably should allow you to hit 'add check', not enter anything, then hit 'Add' or 'Save'
- 'Cancel' when adding an assertion closes the test area at the bottom - it should not.

**Comment by cescoferraro** [comment]
- We want to be able to click on 'Test Status: Finished' and have the bottom test area expand (we watch somebody do this... might as well help get them to the test if they do not see it at the bottom)

- Click an X to delete one filter does delete the filter... but it puts you in 'add a new filter' mode and prompts you for an attibute. I think you should have to click in the filed again to start the 'add filter' process.

- When editing an assertion, the 'Add' button should say 'Save' ✅ 

- If you add a second check line (ie add check), there is no way to delete that line. Should have a trash can next to it. ✅ 

- Probably should allow you to hit 'add check', not enter anything, then hit 'Add' or 'Save'

- 'Cancel' when adding an assertion closes the test area at the bottom - it should not.

**Comment by kdhamric** [comment]
on:
Click an X to delete one filter does delete the filter... but it puts you in 'add a new filter' mode and prompts you for an attibute. I think you should have to click in the filed again to start the 'add filter' process.
(Could not make this work ⛑️, we probably need a specific ticket for this. As it is not trivial to implement)

Communicated with you - you are going to create the issue.

**Comment by cescoferraro** [comment]
Here it is

https://github.com/kubeshop/tracetest/issues/552
