### ISSUE TITLE
Design questions from implementation of new UX

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#514]
These are issues we want to correct in the new UI that we need @olha23 to help with:
- with the DAG zoomed pretty far out, the 'selected span' was hard to distinguish.  Perhaps a bit thicker border when around the selected span (there always should be one selected!)
- We are not showing the # of selected spans when on the 'add assertion' screen any longer.  This will not matter as much once we 'gray out' non selected spans, but we still need a number that changes as we add more filters as it will help people understand they are 'filtering down' and know how many spans will be tested by any checks.

**Comment by olha23** [comment]
got it, will work on this

**Comment by olha23** [comment]
the first part about DAG [here](https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=649%3A12692)

**Comment by olha23** [comment]
the second part about  # of selected spans - [here](https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=416%3A8608)

**Comment by kdhamric** [comment]
Looks good!
