### ISSUE TITLE
Fix assertion creation

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#522]
Description in comments

**Comment by olha23** [comment]
Need to add placeholder text "Attribute" for the first input 
![Uploading Screenshot 2022-05-23 at 12.44.26 PM.png…]()

**Comment by olha23** [comment]
to avoid this situation (when user can’t delete new check line) we need to add trash icon near, like in the first line we see
<img width="852" alt="Screenshot 2022-05-23 at 1 14 29 PM" src="https://user-images.githubusercontent.com/5725840/169807496-857b7ec7-0914-43a9-94a7-43db664b3ddd.png">

**Comment by olha23** [comment]
we need to show [loader](https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=416%3A14921) after user click Add button

**Comment by olha23** [comment]
@xoscar i added here comments about improvements for creating assertion. Please assign this ticket to someone from frontend team

**Comment by olha23** [comment]
add information about the # of [selected spans](https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=416%3A8977)

**Comment by xoscar** [comment]
Thanks @olha23 we'll work on it
