### ISSUE TITLE
Add version number to test and test run

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#524]
# Problem

Today we don't have any way of knowing which version of a test was used to generate a test run. This makes it harder to understand what changed between test runs and why suddenly a passing test started failing. Was that because of a change in the system under test or has the test itself changed?

## Solution
Add a version number to both `test` and `test run`. The number in `test` changes every time a new version of the test is saved. This version should be increased only if the test has changed, otherwise, it should stay the same. 

When a test is run, its `test run` should have the same version as the test version used to run it. So when the test changes, we still know that an older test run used an older test definition.

### Other requirements:
- [ ] The version number should be an incremental number.
- [ ] Test runs should use the latest test version

**Comment by kdhamric** [comment]
Sounds good!
