### ISSUE TITLE
Create edit mode on the test details screen

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#525]
# Problem
Today we don't have any way of knowing which version of a test was used to generate a test run. This makes it harder to understand what changed between test runs and why suddenly a passing test started failing. Was that because of a change in the system under test or has the test itself changed?

## Why this is important
Our backend will now have a `version` number in the test definition. Every time the definition changes, this number will be increased. The problem is that our current interface changes the test every time a new assertion is added or removed. If a large change is made, our frontend will send multiple update requests to the backend, meaning that the version number will be increased several times for no reason. So, we want to send a big request once to the backend and ensure that after the change, the current test version is `version+1` regardless of the number of changes the user made in the test.

## Solution
To edit a test, there will be a new button to enter `edit mode`. When the user is editing the test, there will be two buttons: `Cancel` and `Publish`. `Cancel` cancels the whole operation and no changes are made to the test. `Publish` updates the test definition and the new definition is now the latest test version and it will be used to run any new test run.

When publishing a new version, the user can choose how the test will be executed: `Trigger new test run` or `Apply against this test run` (those can chance). This button could be like Github's merge button: 
![image](https://user-images.githubusercontent.com/2704737/169856287-341838e3-4f05-4c8b-93f9-34445d156813.png)

**Comment by kdhamric** [comment]
Trying to think of the wording we should use for:
trigger a new transaction or apply it against the current trace

Publish ->
  Trigger new test run
  Apply against this test run
