### ISSUE TITLE
Make rerun operation copy the request, response, and trace from the old test result

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#527]
# Problem
Today we don't have any way of knowing which version of a test was used to generate a test run. This makes it harder to understand what changed between test runs and why suddenly a passing test started failing. Was that because of a change in the system under test or has the test itself changed?

## Why this is important
Some systems have long-running tasks that might take dozens of minutes to complete and changes in the test definition will not change the trace it will generate, so, to enable users to have quicker feedback on their tests, we want to give them the option to reuse the `request`, `response`, and `trace` from an old test run to assert the new test definition.

## Solution
When the endpoint `/tests/:testID/run/:runID/rerun` is called, it will fetch that specific run, copy the `request`, `response`, and `trace` fields, create a new test run and use the latest test defiition to assert it.

**Comment by schoren** [comment]
Would it make sense to have a more generic "apply assertion version X to traces from result Y"? so we could have an endpoint like `/tests/:testID/run/:runID/assert/:testVersionNumber`

**Comment by xoscar** [comment]
@schoren would the test version number be optional? if we don't send it means to use the latest version?

**Comment by schoren** [comment]
We could do that. Also, I imagine the version number will be part of the response when you save the new version, so you can also use that.

**Comment by mathnogueira** [comment]
> Would it make sense to have a more generic "apply assertion version X to traces from result Y"? so we could have an endpoint like `/tests/:testID/run/:runID/assert-with-version/:testVersionNumber`

What if we could specify the version in the body. This is a POST endpoint, so we could use something like:

```
POST /tests/:testID/run/:runID/rerun
```
```json
{
    "version": 3, # if empty, consider it as "latest"
}

**Comment by schoren** [comment]
That's a nice approach. The only thing that I'm not convinced is the `rerun` term. I would expect a rerun to do the same thing as before, but we are actually applying a new version.

**Comment by mathnogueira** [comment]
You have a good point. Any suggestion on the term we should be using? Maybe `assert`? and then the field inside the body could be called `testVersion`.
