### ISSUE TITLE
The DAG and assertion behaviour

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#531]

**Comment by olha23** [comment]
Video with my explanation - https://www.loom.com/share/c4e56fe498e44ff4b094e3b59c489aa3

Link for mockups - https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=649%3A12389

**Comment by kdhamric** [comment]
@olha23 Can we use these names for the two views and have them on the mouseovers:
System view
Timeline view
Comments?

**Comment by kdhamric** [comment]
@olha23 Should we start the Test info area in 'open' mode?  This may help people see it and know it is there

**Comment by olha23** [comment]
updated design here https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=728%3A20427
