### ISSUE TITLE
Span signature not being set when adding an assertion

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#550]
Span signature not being set when adding an assertion. 

https://www.loom.com/share/8b1879f5043a46499b588f4287fb02e9

**Comment by kdhamric** [comment]
@olha23 Commented on this in #531.  Closing this.

**Comment by kdhamric** [comment]
I wonder if highlighting selected spans is the right way to show them when adding filters.  I think I would like 'graying out' unselected spans, but this is just a comment.  Lets try your highlight and see how it feels.

**Comment by xoscar** [comment]
I think this is something we missed in the requirements, my understanding was that by clicking on the add assertion button the idea was to start from scratch, not having the prepopulated signature in the selector space. 

We can work on this tho, it shouldn't be a big deal

**Comment by kdhamric** [comment]
Lets make it default the selction based on the currently selected span.  Pretty easy to clear the selector... but it is hard to build one.
