### ISSUE TITLE
Contains assertion does not evaluate correctly

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#617]
Contains assertion does not evaluate correctly

See https://beta.tracetest.io/test/f41e3fa9-0ed1-4449-839a-65645e0454bc/run/c00e69af-0f7f-4324-836d-293dcd5014c8

![image](https://user-images.githubusercontent.com/1385894/171473705-c2af0b95-277e-4889-90d5-c66bd3214560.png)

**Comment by schoren** [comment]
Working now!

![Screen Shot 2022-06-02 at 14 30 45](https://user-images.githubusercontent.com/314548/171689169-89c251a6-9407-4e8c-87f6-8b47e6f2c9b5.png)
