### ISSUE TITLE
Add assertion and copy buttons do not show next to attributes at all screen sizes

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#618]
The add assertion and copy buttons that appear when you hove over an assertion do not show on long lines unless the screen is very wide

![image](https://user-images.githubusercontent.com/1385894/171474549-9d18b1e5-7847-43fb-b6a5-2be9b4cb5a2f.png)

**Comment by xoscar** [comment]
What resolution are you on?

**Comment by kdhamric** [comment]
I dont think it is a screen resolution issue - just 'when my browser window is not real wide and I have an attribute with a long text, the hover buttons do not show'.

Here are a couple of screenshots as I widen my  browser window
![image](https://user-images.githubusercontent.com/1385894/171508557-690b48de-bd1e-49dd-8f7b-73e5e07b04fe.png)
![image](https://user-images.githubusercontent.com/1385894/171508635-fcab8617-39b5-4ce8-b351-22216e510181.png)
