### ISSUE TITLE
Improve headers in the Trace and Test areas

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#629]
On the Test area header, alter:
  - Add a info icon to the right of the test name
  - When hovering over it, show:
      Trace ID: e4986b3ff11bd0eef98d31d840496c91
      Trace transaction occurred: 03/23/2022 at 13:20:52....  or 23/03/2022 for europe
      Transaction execution time: 19 s
      Total trace execution time: 19 s
      Span number: 9
 - Change the header so it is now 2 lines and the url is smaller / less bold

On the Trace area, alter:
 - change the date format as shown above
 - remove the number of spans

Designs: https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=818%3A12647

**Comment by jorgeepc** [comment]
We don't have the API fields to support `Transaction execution time` and `Total trace execution time`. We will display only our current `executionTime`. I'll create a ticket for the future work.
