### ISSUE TITLE
Add transaction execution time and trace execution time

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#640]
We need to implement the following fields in the TestRun API response: 
- `Transaction execution time`: the time it takes from making the transaction call to get a response.
- `Trace execution time`: total trace execution time.

In the FE we should display those fields in the following screens:

![Screen Shot 2022-06-02 at 13 17 41](https://user-images.githubusercontent.com/3879892/171699022-c0f4d47d-cb1a-4e22-84b8-01a29344c420.png)
![Screen Shot 2022-06-02 at 13 17 48](https://user-images.githubusercontent.com/3879892/171699032-c47d52ce-4d7f-4574-8ca7-5dec3f64ab27.png)

**Comment by mathnogueira** [comment]
Do we still need to support this?

**Comment by jorgeepc** [comment]
We can close this @mathnogueira. We already support `executionTime` and `triggerTime`.
