### ISSUE TITLE
View the test definition inside the app

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#703]
**Context:** We have the ability to download the test definition via the `CLI`. 

**AC1** 
As a user I need to be able to view the test definition in the web app. 

**AC2** (`to confirm if we want this AC`)
As a user I want to be able to add a test in the UI by pasting in a definition or uploading a file.

**Comment by xoscar** [comment]
Design https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=927%3A16655
