### ISSUE TITLE
Specify http authorization details in test creation

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#704]
**Context:** The backend already supports auth details in a test creation.

**AC1** 
As a user I need to be able to add authentication details in the web app during a test creation. 

**Note:** Please take a look at [Postman Auth Request](https://learning.postman.com/docs/sending-requests/authorization/)

**Comment by cescoferraro** [comment]
@olha23 I will implement the functionality
can you please take a look at it design/ux wise?

**Comment by olha23** [comment]
@cescoferraro check design here please 👉 http authorization details in test creation[#718](https://github.com/kubeshop/tracetest/issues/718)
