### ISSUE TITLE
View the JUnit results inside the app

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#706]
**Context:** We have the ability to download the JUnit results via the `CLI`.  The `CLI` right now only supports downloading the result of the run you’re currently running. The app would make it easy to get the result for any run.

**AC1** 
As a user I need to be able to download the JUnit results in the web app.

**Comment by xoscar** [comment]
There is a new requirement.

**AC2**
As a user when clicking the JUnit option
I want to see the viewer popup described here https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=927%3A16655
And a way to download the file.
