### ISSUE TITLE
[SPIKE] Improve graph view

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#710]
Extract from the big boulder ideas:

```
Improve the information shown on the Graph view to show more detailed information about the flow. 
Add information on the arrow. 
Show information when hovering on a span showing flow. Add numbers to indicate the steps.
```

The output of this ticket should be one or more actionable items that lay down the different changes we want to make to the graph view, including design and implementation.

**Comment by jorgeepc** [comment]
The following proposal covers 3 main sections that will impact the `TestRun` Graph: 

- Data model
- Interactions
- Look & Feel

# Data model

Our graph should try to explain variations in 3 areas: `Test Validation`, `Performance` and `Errors`. But before that, we need to establish a base `data model` to represent a single span in a trace:


- Semantic convention **type**
    - `General`
    - `HTTP`
    - `Database`
    - `RPC/RMI`
    - `Messaging`
    - `FaaS`
    - `Exceptions`
    - `Compatibility`
- Operation name
- Service name
- Span kind
    - `Client`
    - `Server`
    - `Producer`
    - `Consumer`
    - `Internal`
- Span context
    - Span ID
    - Dependency (already solved by connectors in the graph)
- Set of Attributes
- Ordered list of Events (we should include `Events` in the Span Detail section)
    - Timestamp
    - Name
    - Attributes
- Programming language (`telemetry.sdk.language`)


## Test Validation, Performance and Errors overview

### Test Validation: 
With testing as our `core` capability, we should enable our users to quickly understand `failed/passed` assertions.

- Number of failed checks
- Number of passed checks

### Performance: 
It also important to provide our users the capability to troubleshoot and detect performance issues or bottlenecks with a visual tool.

- Duration (`start` - `finish` timestamps)
- Latency contribution

### Errors: 
We also have the opportunity to identify errors and broken flows in a trace. This will support the goal of converting Tracetest in one of the best trace visualization tools in the market.

- Status:
    - `Unset`
    - `Ok`
    - `Error`
- Exceptions
- Detect Errors in attributes (for example `http.status_code`)

## Mock layout

With the data model established, a single span in our graph should have the following format:

![tracetest-span](https://user-images.githubusercontent.com/3879892/174688519-510f2980-6eaa-4b94-bb04-cebfe443de69.png)

# Interactions
We could include the following user interactions in the graph:

- Minimap
- Fit view button
- Animate connector for selected span
- Create a popover to display secondary information:
    - Span context: Span ID
    - Semantic convention type
    - Number of attributes
    - Number of events
    - Programming language (telemetry.sdk.language)


| Interaction  | Demo |
| ------------- | ------------- |
|  Minimap | ![2022-06-20 18 36 13](https://user-images.githubusercontent.com/3879892/174689387-5b47cca4-569a-4312-909f-5bc02f0aee6d.gif) |
| Animate connector for selected span | ![2022-06-20 18 39 19](https://user-images.githubusercontent.com/3879892/174689460-84e8d0d3-9fc2-4001-8ae9-c603fe2a29f9.gif) |
| Popover with secondary information | ![Screen Shot 2022-06-20 at 18 45 30](https://user-images.githubusercontent.com/3879892/174689694-2210ead1-977f-437b-bbee-f94197aae622.png) |

# Look & Feel
For this part we need input from Olly, however I think there are a couple of details that we should keep in mind:

- Improve the color palette.
- Icon/Color for the semantic convention type
- Highlight the span with the longest operation (this will help to visualize performance bottlenecks)

----------

This proposal is the result of analyzing Tracing related products ([https://lightstep.com/](https://lightstep.com/), [https://logz.io/](https://logz.io/), [https://gethelios.dev/](https://gethelios.dev/), [https://aspecto.io/](https://aspecto.io/), [https://www.jaegertracing.io/](https://www.jaegertracing.io/)) and the OpenTelemetry Trace Specification [https://github.com/open-telemetry/opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification)

**Comment by xoscar** [comment]
Great job @jorgeepc. Should we move this to done?
