### ISSUE TITLE
View the test definition inside the app

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#717]

**Comment by olha23** [comment]
We have the ability to download the test definition via the CLI. We need to be able to view it in the web app. We may want to be able to add a test in the UI by pasting in a definition or uploading a file.

**Comment by olha23** [comment]
@kdhamric Can you provide more info here please? For example what kind of Information must be in this definition ?

**Comment by kdhamric** [comment]
Take a look at this video at about 45 seconds in - it shows @mathnogueira opening up a test definition file.  It is a yaml file that contains text that describes the trigger and the assertions for a test.  You can also look at https://github.com/kubeshop/tracetest/issues/160 to see the issue that defined this textual description of a test.

Each test has a 'textual description' that describes it... we just need to expose this.

**Comment by olha23** [comment]
@kdhamric what video?

**Comment by kdhamric** [comment]
Sorry - https://www.youtube.com/watch?v=Mimx5E19NSE&t=20s

**Comment by olha23** [comment]
@kdhamric check here please https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=916%3A16396
