### ISSUE TITLE
Adding span checks (Exists, # of spans)

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#724]
While adding assertions and checks sometimes we don’t want to test the span attributes data. Instead, sometimes it is good to have checks to validate the existence of a specific span, the number of times it appears.

**Comment by olha23** [comment]
@schoren maybe you can provide additional Information about this task? Ken said that you are person who can help with this

**Comment by mathnogueira** [comment]
Closing this because this already exists in the current version
