### ISSUE TITLE
🚀 Design Import screens for Postman Collections

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#731]
Design ticket for the postman plugin during the create test process.

**AC1:**
When viewing the different ways to create a test
If the postman plugin is selected
The import collection step should be displayed

**AC2:**
When viewing the different ways to create a test
If the postman plugin is selected
The import environment variables optional step should be displayed

**AC3:**
When viewing the import collection step
After uploading the collection and selecting next
The select request step should be displayed

**AC4:**
When viewing the import collection step
After uploading a corrupted or non-supported file
I should see a validation error

**AC5:**
When viewing the import collection step
After uploading the collection and selecting next
The select request step should be displayed

**AC6:**
When viewing the select collection step
As a user, I should be able to select one of the requests from the collection
And by selecting next
The create test form step should be displayed

For more information please refer to the documentation https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/527302657/Import+Postman+Collection

**Comment by olha23** [comment]
Design here https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=1124%3A21087
