### ISSUE TITLE
Reduce responses size

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#741]
The test list page, for example, ask for the tests list just to show the titles and some basic information, but the backend is returning A LOT of unused information, it could easily get to the range of 10s of megabytes. Same for the request the FE uses to display the list of test runs, the backend returns all the trace and result, when the FE just needs the title.

**Comment by schoren** [comment]
@mathnogueira You said we can "hide" fields based on the request. I.E `/api/tests` would not return the results or definitions of each test, `/api/tests/{testID}/runs` would not return trace and results, etc. I agree in theory, but in practice it seems anti-openapi to use that pattern. 

I suggest having a `?short=yes` flag that clients could use when they want a reduced version of the data.

@xoscar mentioned graphql as an option.

What solution should we use?

**Comment by mathnogueira** [comment]
I'd go with a flag for now. It seems to be too cumbersome to introduce graphql right now.

**Comment by kdhamric** [comment]
@schoren @mathnogueira Status of this?

**Comment by schoren** [comment]
On hold at the moment
