### ISSUE TITLE
Implement assertions on span collection attributes

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#777]
We need to be able to do assertions on the span collection level. Examples

1. Assert that there are less than 5 DB Queries (`span[type=db]`, `:count =5`)
2. Assert that a cached service does not go to the source again (`span[type=http url="/cache/reload"]`, `:count = 0`

**Comment by kdhamric** [comment]
Is there a frontend card needed to support this, and does it need any design work from @olha23 ?
