### ISSUE TITLE
Design RPC triggering method steps

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#810]
As part of the documentation described here https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/539328517/Triggering+Method+-+RPC we need to design the different steps for creating a test based on RPC.

AC1
As a user looking at the create test page
I should be able to select the RPC triggering method.

AC2
As a user creating a test and having selected RPC as a triggering method
I should see the different steps that define the plugin:

Select plugin.
Basic details.
Define method (proto buff).
Request details.
AC3
As a user looking at the third step of creating a test based on the RPC triggering method
I should be able to upload a proto buff file by either drag and drop or selecting it using the file explorer

AC4
As a user looking at the third step of creating a test based on the RPC triggering method
After uploading the photo buff file I should be able to select one of the supported methods from the dropdown.

AC5
As a user looking at the fourth step of creating a test based on the RPC triggering method
I should be able to add the request details like URL, message, metadata, and authorization.

**Comment by olha23** [comment]
@xoscar i combined 3 and 4 step in one. Check here please 👉 https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=973%3A22580

**Comment by xoscar** [comment]
Perfect, thanks!
