### ISSUE TITLE
[DAG] Design UI Span node

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#813]
**Context:** as explained in #710 we want to include a new `Span node` in our `DAG`. The goal of this ticket is to design the UI for the span.

**AC1**
The new span node should include the following information:
- Semantic convention **type** (icon)
    - `General`
    - `HTTP`
    - `Database`
    - `RPC/RMI`
    - `Messaging`
    - `FaaS`
    - `Exceptions`
    - `Compatibility`
- Operation name
- Service name
- Span kind
    - `Client`
    - `Server`
    - `Producer`
    - `Consumer`
    - `Internal`
- Duration

**AC2**
Generate an `icon` and `color palette` for the following span types:

| Type | Current color |
| --- | --- |
| General | #FFBB96 |
| HTTP | #C1E095 |
| Database | #EFDBFF |
| RPC/RMI | #9AD4D6 |
| Messaging | #BFBFBF |
| FaaS | #FFBB96 |
| Exceptions | #FFBB96 |
| Compatibility | #FFBB96 |

**AC3**
If the Span node has `passed/failed` checks (assertions)
the span should include an indicator of passed/failed checks

**AC4**
If the Span node has an `error` (this is not an assertion error, this is an error in the execution)
the span should be highlighted or has some UI indicator of the error

**AC5**
If the Span node has the longest duration time in the trace
the span should include a UI indicator of that
(_maybe it could be something in the same `duration` field_)

### Mockup
![tracetest-span](https://user-images.githubusercontent.com/3879892/174688519-510f2980-6eaa-4b94-bb04-cebfe443de69.png)

### Example
![2022-06-27 13 17 50](https://user-images.githubusercontent.com/3879892/176009049-e695b584-523a-45b4-9d7f-d5c50b68a32a.gif)

**Comment by olha23** [comment]
@jorgeepc i have a question about convention type icon. Are there commonly known icons for these types (like RPC/RMI, Messaging, FaaS, Exceptions, Compatibility)? If we need to create custom icons, for users it can be hard to understand what they mean

**Comment by olha23** [comment]
Design is here https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=1081%3A22959

**Comment by jorgeepc** [comment]
Thank you @olha23 I'll work on the implementation.
