### ISSUE TITLE
Improve telemetry: better naming and attributes for db spans

### ISSUE THREAD

**Issue by mathnogueira** [kubeshop/tracetest#855]
**Describe the enhancement you'd like to see**
Today our database operations are instrumented automatically, however, they are not optimal. For example, they don't follow the OTEL naming conventions for the SQL query attribute: it uses `sql.query` instead of `db.statement`.

Another thing that is not nice is the name of the generated spans:
![image](https://user-images.githubusercontent.com/2704737/177171127-85469a1f-98b1-45a5-aea9-7209c64c1e31.png)

**Comment by kdhamric** [comment]
@mathnogueira What is the state of this? If done, please close this.
