### ISSUE TITLE
Sync Spans in Test Result section & Span Detail section with DAG Span node

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#893]
**Context:** as part of the work done in #710 we updated the span node in the DAG. We want to have the same data model in the `Test Result section` and the `Span Detail section`.

**AC1**
As a user, if I have assertions 
then the `Test Result section` should contain 
spans with the same data model as the DAG Span node

**AC2**
As a user, if I select a span
then the `Span Detail section` should contain 
the same data model as the DAG Span node

**Comment by jorgeepc** [comment]
## Proposal for the Test Result section

_Note: click on the images to see them in full size._
### Current UI

<img width="1489" alt="Screen Shot 2022-07-11 at 15 00 19" src="https://user-images.githubusercontent.com/3879892/178350749-8c868b1b-70ef-4cd9-8223-65be505095cd.png">

____

### Option 1

In our current implementation we group the results by **Selector**. In addition to the selector, I propose to create a new subgroup by **Span**. With this in mind, we could have the following headers in the UI:

#### Selector header:

![selector](https://user-images.githubusercontent.com/3879892/178353279-32003a16-a5d7-4412-a6d0-5ef2c577fccb.png)

#### Span header (this matches the DAG SpanNode):

![span](https://user-images.githubusercontent.com/3879892/178354193-38b6158e-cd5b-4b9a-a071-441aac17b9b6.png)

And finally, we will display the checks in the body. The implementation could look like this: (don't worry about the `look & feel` we need to improve it with Olly)

<img width="1489" alt="Screen Shot 2022-07-11 at 14 59 25" src="https://user-images.githubusercontent.com/3879892/178355641-7d15a069-be8a-43ab-afd8-c44ad1dcdc0e.png">

____

### Option 2

The idea about creating a subgroup is similar here, with the difference that we could group by **Check** (instead of Span).

<img width="1485" alt="Screen Shot 2022-07-11 at 14 59 47" src="https://user-images.githubusercontent.com/3879892/178356565-25ad8f93-07f6-4e75-aa49-916861cf8b51.png">

____

### More examples 👀 

| Current UI  | Option 1 | Option 2 |
| ------------- | ------------- | ------------- |
| <img width="1485" alt="Screen Shot 2022-07-11 at 15 57 49" src="https://user-images.githubusercontent.com/3879892/178357271-e05d2541-f90c-4c07-975a-6de911769aaa.png"> | <img width="1482" alt="Screen Shot 2022-07-11 at 15 57 28" src="https://user-images.githubusercontent.com/3879892/178357299-266718a3-419e-48d1-9732-68325b4b907e.png"> | <img width="1495" alt="Screen Shot 2022-07-11 at 15 57 16" src="https://user-images.githubusercontent.com/3879892/178357326-66e1e86c-473f-48bf-ac1f-5fe40b03d5e4.png"> |
| <img width="1491" alt="Screen Shot 2022-07-11 at 15 57 06" src="https://user-images.githubusercontent.com/3879892/178357518-13f92cd0-8c3f-43d3-83b1-81bd8fa44fd7.png"> |  <img width="1488" alt="Screen Shot 2022-07-11 at 15 56 56" src="https://user-images.githubusercontent.com/3879892/178357515-f4683476-07e3-44b1-b776-bd2dfd66ebc1.png"> | <img width="1491" alt="Screen Shot 2022-07-11 at 15 56 42" src="https://user-images.githubusercontent.com/3879892/178357509-97c5a720-1189-4b25-b64f-326adcc08aad.png"> |

**Comment by mathnogueira** [comment]
Impressive work! @jorgeepc.

I think that option 2 is better because of checks like `tracetest.selected_spans.count = 1`. This specific check could potentially group a big number of spans depending on your test.

I also think that hierarchy makes sense:
  * Selector (what you are trying to match)
      * Span (What you matched)
         * Check (What you want to assert)

**Comment by kdhamric** [comment]
Love the work!

I tended to like #1 - it seemed to present:
Selector
  -> Spans selected
     -> Tests against each selected span
     
I would tend to say a check such as 'tracetest.selected_spans.count = 1' is a 'selector level check' and does not apply at the individual matches span level. For example, if it was the only check and there were no matching spans, the assertion that the selector will return a span count of one would fail.  It will not be associated with any particular span (in this case, there is no span), but will be tied to the selector (or tied to the overall assertion if you want to look at it that way).

Another example - lets say the selector selects 3 spans, and we have the same 'tracetest.selected_spans.count = 1' check.  I think we should still only have one check that failed, and it should be at the top level of the assertion, not tied to the detail spans.

**Comment by olha23** [comment]
I updated design here 👉 https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/V1?node-id=1219%3A28458
