### ISSUE TITLE
User is not redirected to new test run page when re-running a test

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#913]
**Describe the bug**
When a user gets a test run error (like timeout, invalid host, etc), the UI shows a `re run test` button. When I click it, the new run is actually triggered, but the user is not redirected to the new test, so it looks like nothing happened.

**To Reproduce**
1. Go to a [test with error](https://demo.tracetest.io/test/faa58586-c054-41e8-880f-17879cc9fc71/run/385d29d0-eb9c-479f-8eb7-2097597872d6)
2. Click on `Rerun Test`
4. Nothing happens visually

**Expected behavior**
Be redirected to the new test run page

**Comment by jorgeepc** [comment]
Also, the `Edit Test` button in the same error page is not working. We can fix that as part of this bug.

**Comment by xoscar** [comment]
This should be fixed in the beta env https://beta.tracetest.io/test/65524796-fcd5-46f7-9489-efdb2e0a11bf/run/088c41ae-0e34-4bd8-9f8d-6f26d15a1fc3
