### ISSUE TITLE
[Wildcard #2] OTEL demo contribution

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#917]
We need to get more involved with the Open Telemetry community and for that, we want to start looking at the demo app they are putting together https://opentelemetry.io/blog/2022/demo-announcement/. See where we can contribute and make ourselves useful.

Steps:
1. Research and understand the demo app.
2. Find a ticket to work on their board.
3. Talk to the team.
4. Contribute to the repo.

**Comment by xoscar** [comment]
That sounds very interesting @cartersocha
I'd like to know more about the front end development piece, I think we can be instrumental on that front to start with.
If you don't mind I'll ping you on slack tomorrow morning so we can discuss it in more depth.

**Comment by cartersocha** [comment]
Sounds good! The related issue is here: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/39

**Comment by xoscar** [comment]
Per a conversation with Carter, I'm going to start working on a proposal to move the front end to a SPA application instead of the current GO SSR app. The proposal will be presented at one of the SIG meetings.

**Comment by cartersocha** [comment]
Hey @xoscar, for whatever reason I can't add you on the demo repo issue. Could you comment on it? That should add your username to potential owners for me

**Comment by xoscar** [comment]
PR https://github.com/open-telemetry/opentelemetry-demo/pull/236
