### ISSUE TITLE
[SPIKE] How can we bring the OTEL demo app to Tracetest

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#918]
As part of us getting move involved with the Open Telemetry community we want to include the demo app https://opentelemetry.io/blog/2022/demo-announcement/ into our ecosystem that way we can demonstrate how to create Trace Based Tests using tracetest.

**Comment by agardnerIT** [comment]
Another lightweight app to use is from the CNCF TAG app-delivery group: https://github.com/podtato-head/podtato-head

**Comment by xoscar** [comment]
Steps to add the OTel demo to the Tracetest K8 cluster
1. Install the otel demo heml chart following the steps here https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/README.md
2. Reinstall Tracetest in the cluster pointing it to the jaeger instance from the Otel demo (the otel demo doesn't have an option to specify the jaeger instance).
3. Reinstall the pokeshop charts pointing to the same otel demo jaeger instance

**Comment by xoscar** [comment]
Links for the instances:
http://otel-demo.tracetest.io
http://tracetest-otel-demo.tracetest.io/
