### ISSUE TITLE
Search capability for traces needs improvements

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#958]
The search capability for a trace needs improvement & some thought.  I could not see the highlighting in my loom recording below.  Secondly, I might expect the "< > 0 of 0 total" to allow me to cycle through the selected spans once I do a search.  Wanted to start an issue so we could brainstorm how to improve it.

 https://www.loom.com/share/4c6209adc5a04ba9b2af4e529ffe60be

**Comment by kdhamric** [comment]
One idea that I am not sure I like, but I wanted to throw out there to see if somebody else could improve on it:

Have the 'search in a trace' be 'overloaded' and accept both a plain text search and a span selector query.

Change the 'select span' and 'select assertion' logos to be a magnifying glass, and say 'search for span' and 'search for spans impacted by this assertion'.  Clicking the 'search for spans impacted by this assertion' magnifying glass would add the advanced query string into the 'Search in trace' field, and execute it.  The 1or 3 paging would then work on the results of that query.  Similar for the 'select span' - it may just put in a query that targets the span by span id.

Good part of allowing 'selector language' in the search field is it would make it more used... if you wanted to see all http spans, you could type span[tracetest.span.type = "http"] and hit return.

Users could also enter a plan text search.  Hitting enter would search all the spans for those words.  The 0 of 0 would update to show the number of spans that match, and you could scroll through them.

I would question what to do when you are typing a selector as part of building an assertion.  Currently, as we have a valid selector, the search is changing the top to show what is under selection by this assertion.  Might be weird (ie a bad idea), but changing the search field to match the 'in process' query definition as you change it to a valid query and executing the search is the best thought I have.

Not saying we should do this - just an idea to shoot at.

**Comment by xoscar** [comment]
I think what is described here can now be done as part of the `Trace` mode in the test run details page. i.e https://beta.tracetest.io/test/dc1c234e-44f6-49eb-b4ec-c4ce19a8360e/run/e2a767d2-120a-4f90-903b-e9a14ceae95f/trace
