### ISSUE TITLE
Remove JS errors in console

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#975]
It seems that the changes introduced to support the [custom server prefix](https://github.com/kubeshop/tracetest/pull/701) are generating JS errors when you load a `Test Run` page.

The app tries to load the main bundle from a route that does not exists, then the index.html runs the inner script and loads the bundle from the correct route.

We need to avoid the first try in order to remove the JS errors in the console.

![Screen Shot 2022-07-22 at 16 15 51](https://user-images.githubusercontent.com/3879892/180569865-f40172aa-5153-4287-bb89-1a7e5be4d704.png)

**Comment by cescoferraro** [comment]
@jorgeepc we need to get rid of the warnings we get when running the project

**Comment by kdhamric** [comment]
@cescoferraro Can you address this?

**Comment by cescoferraro** [comment]
sure @kdhamric

**Comment by cescoferraro** [comment]
I have opened this issue because #1102 did not fix the main issue
The problem is that we need to be able to choose the base path at run time and the proper solution for this requires us to have the information at build time. I need more time to research workarounds!

**Comment by kdhamric** [comment]
@xoscar @jorgeepc Would you review this issue and close it if not needed or finished?
