### ISSUE TITLE
Issue with test definition file showing blank definitions for other trigger types

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#976]
A test triggered by a gRPC event is still showing a 'httpRequest' area in the trigger definition.  It is blank, but it probably should not be there.  

Conversely, a test triggered by a http trigger shows a blank grpc trigger info.

It will be cleaner if we do not show the 'blank' definitions for the unused trigger type

A grpc triggered test
`description: Import a Pokemon
id: 79ad313c-7504-45a3-96f7-c27fb2933cbe
name: GRPC - Pokemon - Import
trigger:
    grpc:
        address: demo-pokemon-api.demo.svc.cluster.local:8082
        authentication:
            apiKey:
                in: ""
                key: ""
                value: ""
            basic:
                password: ""
                user: ""
            bearer:
                token: ""
        method: pokeshop.Pokeshop.importPokemon
        protobufFile: |
            syntax = "proto3";

            option java_multiple_files = true;
            option java_outer_classname = "PokeshopProto";
            option objc_class_prefix = "PKS";

            package pokeshop;

            service Pokeshop {
              rpc getPokemonList (GetPokemonRequest) returns (GetPokemonListResponse) {}
              rpc createPokemon (Pokemon) returns (Pokemon) {}
              rpc importPokemon (ImportPokemonRequest) returns (ImportPokemonRequest) {}
            }

            message ImportPokemonRequest {
              int32 id = 1;
            }

            message GetPokemonRequest {
              optional int32 skip = 1;
              optional int32 take = 2;
            }

            message GetPokemonListResponse {
              repeated Pokemon items = 1;
              int32 totalCount = 2;
            }

            message Pokemon {
              optional int32 id = 1;
              string name = 2;
              string type = 3;
              bool isFeatured = 4;
              optional string imageUrl = 5;
            }
        request: '{"id":52}'
    httpRequest:
        authentication:
            apiKey:
                in: ""
                key: ""
                value: ""
            basic:
                password: ""
                user: ""
            bearer:
                token: ""
        method: ""
        url: ""
    type: grpc`
    
A http triggered test    
    `description: Get a Pokemon
id: e848f98a-75e1-4ea6-bcf0-473dc86065a4
name: Pokemon - List
trigger:
    grpc:
        address: ""
        authentication:
            apiKey:
                in: ""
                key: ""
                value: ""
            basic:
                password: ""
                user: ""
            bearer:
                token: ""
        method: ""
        protobufFile: ""
    httpRequest:
        authentication:
            apiKey:
                in: ""
                key: ""
                value: ""
            basic:
                password: ""
                user: ""
            bearer:
                token: ""
        headers:
            - key: Content-Type
              value: application/json
        method: GET
        url: http://demo-pokemon-api.demo.svc.cluster.local/pokemon?take=20&skip=0
    type: http`

**Comment by kdhamric** [comment]
@mathnogueira I am still seeing this when I look at a test definition. A http triggered test still shows both a httpRequest block and a blank grpc trigger:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1385894/189603925-b0483bf0-45a3-410e-9284-f320eebb647c.png">

**Comment by mathnogueira** [comment]
#1197 was merged and fixes this issue. I'll close this
