### ISSUE TITLE
Cannot easily cancel out of a create test flow

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#980]
When creating a test, there is not a clear way to cancel out of the flow if you choose to abandon / stop during the process. If you go back to the tracetest main screen from deep in the creation wizard, you are returned to your original spot.  The video shows it best:

https://www.loom.com/share/4e6b91f6322041f08a661c5a80ca2dfc

Not sure the best way to handle this - probably would like @olha23 thoughts. If the team is fine with it 'as is', I am ok with that also.

**Comment by xoscar** [comment]
@olha23 do you mind taking a quick look at this? thanks!

**Comment by kdhamric** [comment]
@olha23 Can you help on this? Adding a 'Cancel' button is fine or whatever you want. Once you do this, assign the issue to @cescoferraro

**Comment by olha23** [comment]
i propose add "close" button near the 'next' button, and move "previous" button to the left side (it's very common usage for this pattern). design here https://www.figma.com/file/5E7yr3kIPk1B08He0w9juk/tracetest?node-id=1533%3A40651

**Comment by cescoferraro** [comment]
here it is #1083  @olha23  @kdhamric
