### ISSUE TITLE
Google Analytics Secret in plain text

### ISSUE THREAD

**Issue by agardnerIT** [kubeshop/tracetest#984]
**Describe the bug**
https://github.com/kubeshop/tracetest/blob/8ed3cccdfab1ca9a8469fafe0bca5f720b0562b0/setup.sh#L184 lists a GA secret.

Google [suggest keeping this private](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/?client_type=firebase) or rotating regularly (this might already be happening):

```
We recommend that you keep these private to your organization. If you deploy the measurement protocol client-side, you should regularly rotate api_secrets to avoid excessive SPAM.
```

**Comment by schoren** [comment]
@agardnerIT Thanks for bringing this up. We are currently migrationg away from GA, so this is not really critical at the moment. We did this as a quick and dirty test, but we are aware this is not the correct way to do it. For our improved implementation, we'll inject the secrets as part of our build process
