### ISSUE TITLE
Competitor Analysis

### ISSUE THREAD

**Issue by olha23** [kubeshop/tracetest#994]

**Comment by olha23** [comment]
https://kubeshop.atlassian.net/wiki/spaces/KUBESHOP/pages/562954364/Competitor+Analysis+work+in+progress

**Comment by agardnerIT** [comment]
Is this document publicly available?

**Comment by kdhamric** [comment]
It is not - it was an internal review of tools in the area - we probably should not have included it in github.  Closing the issue.
