### ISSUE TITLE
Test Definition File Timing

### ISSUE THREAD

**Issue by agardnerIT** [kubeshop/tracetest#995]
**Describe the enhancement you'd like to see**
Make timing more explicit:

https://kubeshop.github.io/tracetest/test-definition-file/ lists `tracetest.span.duration <= 500` whereas this should probably be:

```
tracetest.span.duration <= 500ms
```

For better readability.

**Comment by mathnogueira** [comment]
Nice catch @agardnerIT! I'll update the docs to use the time unit. Right now you already can use the following units: `ns`, `us`, `ms`, `s`, `m`, and `h` in your test definition.

**Comment by mathnogueira** [comment]
I'll close it. Feel free to reopen it if you think something else needs to be done.
